/***************************************************************************
- File: gmaps.js
- Version: 14.7.16
***************************************************************************/

$m.trick.gmaps={};
$m.t.gmaps={name:"gmaps",data_att:"gmaps",data_att_config:"data-mjf_gmaps",google_maps_js_link:"https://maps.googleapis.com/maps/api/js?v=3.exp&callback=$m.t.gmaps.init",all_maps:{},info_window:!1,construct:function(a){if($m.is.alive(a)===!1)return $m.de.throw_browser_error("Gmaps: $m.trick.gmaps.config not declared!"),!1;for(var b=$m.attr.get_tags_with($m.tags.all,$m.data_att,$m.t.gmaps.data_att),d="",e="",c="",c=!1,f=0,g=b.length;f<g;f++)if(d=$m.attr.get(b[f],"id"),gmap_config_string=$m.attr.get(b[f],
$m.t.gmaps.data_att_config),e=$m.try_json_unpack(gmap_config_string),e===!1)$m.de.throw_browser_error("Gmaps: Config cannot be unpacked during $m.t.gmaps.init()");else{$m.t.gmaps.all_maps[d]={};if($m.is.alive(e.config.json_file)===!0)c=new $m.ajax,c.init(d),c.config.url=e.config.json_file,c.config.callback="handle_json",c.exec(),c=!0;if($m.is.alive(e.config.json_var)===!0)c=window[e.config.json_var],$m.is.object(c)===!0?$m.t.gmaps.all_maps[d].json=c:$m.de.throw_browser_error("Gmaps: JSON var is not formatted correctly"),
c=!0;c===!0?$m.t.gmaps.all_maps[d].config=e.config:$m.de.throw_browser_error("Gmaps: JSON file or var cannot be found during $m.t.gmaps.construct()")}this.config=a.config;$m.is.alive(this.config.api_key)===!0&&(this.google_maps_js_link+="&key="+this.config.api_key);$m.insert_link.script(this.google_maps_js_link)},init:function(){var a="",b;for(b in $m.t.gmaps.all_maps)if(a=b,this_gmap=$m.t.gmaps.all_maps[b],$m.t.gmaps.all_maps[b].google_map=new google.maps.Map($m.id(a),{zoom:this_gmap.config.zoom,
center:new google.maps.LatLng(this_gmap.config.start_lat,this_gmap.config.start_lon)}),$m.is.alive(this_gmap.json)===!0)for(var d in this_gmap.json.markers)$m.t.gmaps.markers.create(a,this_gmap.json.markers[d],this_gmap.json.format_function)},markers:{create:function(a,b,d){var e={position:new google.maps.LatLng(b.Latitude,b.Longitude),map:$m.t.gmaps.all_maps[a].google_map,title:b.Name},b=window[d](b);if($m.t.gmaps.all_maps[a].config.animate)e.animation=google.maps.Animation.DROP;var c=new google.maps.Marker(e),
f=new google.maps.InfoWindow({content:b});google.maps.event.addListener(c,"click",function(){$m.t.gmaps.info_window&&$m.t.gmaps.info_window.close();f.open($m.t.gmaps.all_maps[a].google_map,c);$m.t.gmaps.info_window=f});c.setMap($m.t.gmaps.all_maps[a].google_map);$m.t.gmaps.all_maps[a].marker=c;$m.t.gmaps.all_maps[a].info_window=f}},handle_json:function(a,b){var d=$m.try_json_unpack(b);d===!1?$m.de.throw_browser_error("Gmaps: JSON file cannot be unpacked during $m.t.gmaps.handle_json()"):$m.t.gmaps.all_maps[a].json=
d}};function handle_json(a){$m.t.gmaps.handle_json(a.config.element_id,a.request.response_text)};
