/***************************************************************************
- File: motion.js
- Version: 14.7.28
***************************************************************************/

$m.trick.motion={};
$m.t.motion={name:"motion",construct:function(){},vslider:{name:"vslider",data_att:"motion_vslider",data_att_link:"motion_vslider_link",sliders:{},css_rules:"",create:function(a){var b=$m.id(a),c=$m.attr.get(a,"data-mjf_mvs_dims").split("x"),d=$m.attr.get(a,"data-mjf_mvs_links_id"),e=$m.attr.get(a,"data-mjf_mvs_scroll_to"),f="",h=c[0],c=c[1],g="",i=0,g=0,k="",a=a+"_"+$m.ut.rand_num(),j=f="";$m.t.motion.vslider.sliders[a]=[];j=a+"_nav";f=$m.tag.init("p",{"class":"motion_vslider_ctrls",id:j});$m.is.alive(d)===
!0?j=d:b.parentNode.insertBefore(f,b.nextSibling);f=$m.is.alive(e)===!0&&e=="true"?"true":"false";b.style.width=h+"px";b.style.height=c+"px";d=0;for(e=b.childNodes.length;d<e;d++)if(g=$m.attr.get(b.childNodes[d],"data-mjf_mvs_panel"),panel_title=$m.attr.get(b.childNodes[d],"data-mjf_mvs_link"),g=="true")i==0?(g="0",k="motion_vslider_ctrls_link motion_vslider_ctrls_active"):(g="-"+c*i,k="motion_vslider_ctrls_link"),i++,b.childNodes[d].style.width=h+"px",b.childNodes[d].style.height=c+"px",panel_link_title=
$m.is.alive(panel_title)===!0?panel_title+"<br>":i,$m.tag.create(j,"a",{href:"#","data-mjf":"motion_vslider_link|return_false","data-mjf_mvs_id":a,"data-mjf_mvs_scroll_to":f,"data-mjf_mvs_pos":g,"class":k,id:a+"_a"+i},panel_link_title),$m.t.motion.vslider.sliders[a].push(a+"_a"+i);b.innerHTML='<div class="motion_vslider_cont" id="'+a+'">'+b.innerHTML+"</div>";$m.t.motion.vslider.css_rules+="#"+a+"{height:"+c+"px;width:"+h*i+"px;}"},construct:function(){for(var a=$m.attr.get_tags_with($m.tags.all,
$m.data_att,this.data_att),b=!1,c=0,d=a.length;c<d;c++)a[c].style.visibility="hidden",b=a[c].getAttribute("id"),this.create(b),a[c].style.visibility="visible";a=document.createElement("style");$m.vd.is_msie8_or_lower===!0?a.style.cssText=$m.t.motion.vslider.css_rules:a.innerHTML=$m.t.motion.vslider.css_rules;document.body.appendChild(a);$m.elements.bind($m.tags.a,this.data_att_link,"click",this.exec)},exec:function(a){var b=$m.attr.get(a,"data-mjf_mvs_scroll_to"),c=$m.attr.get(a,"data-mjf_mvs_id"),
d=$m.attr.get(a,"data-mjf_mvs_pos"),e=$m.attr.get(a,"data-mjf_ga_track"),f="";if(c!==null&&d!==null){$m.vd.is_gecko===!0&&(f="-moz-transform:translate(0px, "+d+"px)");$m.vd.is_webkit===!0&&(f="-webkit-transform:translate(0px, "+d+"px)");$m.vd.is_opera===!0&&(f="-o-transform:translate(0px, "+d+"px)");$m.vd.is_msie===!0?$m.vd.is_msie9_or_lower===!0&&($m.id(c).style.top=d+"px"):$m.attr.set(c,{style:f});d=0;for(f=$m.t.motion.vslider.sliders[c].length;d<f;d++)$m.css_class.remove($m.t.motion.vslider.sliders[c][d],
"motion_vslider_ctrls_active");$m.css_class.add(a,"motion_vslider_ctrls_active");$m.id(a).blur();$m.is.alive(b)===!0&&b=="true"&&$m.smooth_scroll.construct(c,50)}e!==null&&$m.track.ga({category:"MJS Motion Vertical Slider",action:a+"  Click",label:$m.tags.strip.from_id(a)})}},hslider:{name:"hslider",data_att:"motion_hslider",data_att_link:"motion_hslider_link",data_att_img:"motion_hslider_link_image",data_att_cont:"motion_hslider_cont",sliders:[],css_rules:"",create:function(a){var b=$m.id(a),c=$m.attr.get(a,
"data-mjf_mhs_autostart"),d=$m.attr.get(a,"data-mjf_mhs_delay"),e=$m.attr.get(a,"data-mjf_mhs_links_id"),f=$m.attr.get(a,"data-mjf_mhs_scroll_to"),h="",g="",i=g="",k="",j=0,n=0,o="",a=a+"_"+$m.ut.rand_num(),l=h="",m=[];$m.t.motion.hslider.sliders[a]={autostart:$m.is.alive(c)===!0?!0:!1,delay:$m.is.alive(d)===!0?d*1E3:0,timeout:!1,links:[],cnt:0};l=a+"_nav";h=$m.tag.init("p",{"class":"motion_hslider_ctrls",id:l});$m.is.alive(e)===!0?l=e:b.parentNode.insertBefore(h,b.nextSibling);h=$m.is.alive(f)===
!0&&f=="true"?"true":"false";c=0;for(i=b.childNodes.length;c<i;c++)g=$m.attr.get(b.childNodes[c],"data-mjf_mhs_panel"),g=="true"&&m.push(b.childNodes[c]);d=m.length;e=100/d;for(c=0;c<d;c++)$m.attr.get(b.childNodes[c],"data-mjf_mhs_panel"),g=$m.attr.get(b.childNodes[c],"data-mjf_mhs_link"),i=$m.attr.get(b.childNodes[c],"data-mjf_mhs_link_img"),k=$m.attr.get(b.childNodes[c],"data-mjf_mhs_link_img_on"),j=c,j==0?(n="0",o="motion_hslider_ctrls_link motion_hslider_ctrls_active"):(n="-"+e*j,o="motion_hslider_ctrls_link"),
panel_link_title=$m.is.alive(g)===!0?g:j+1,panel_image_on_html=k===null?"":'data-mjf_mhs_link_img_on="'+k+'" data-mjf_mhs_link_img_default="'+i+'"',panel_link_title=$m.is.alive(i)===!0?'<img src="'+i+'" alt="'+panel_link_title+'" data-mjf="motion_hslider_link_image" '+panel_image_on_html+' id="'+a+"_img"+j+'">':panel_link_title,$m.vd.is_msie9_or_lower===!1&&$m.tag.create(l,"a",{href:"#","data-mjf":"motion_hslider_link|return_false","data-mjf_mhs_id":a,"data-mjf_mhs_scroll_to":h,"data-mjf_mhs_pos":n,
"class":o,id:a+"_a"+j},panel_link_title),$m.css_class.add(m[c],"motion_hslider_box_"+a),m[c].style.zIndex=100-j,$m.t.motion.hslider.sliders[a].links.push(a+"_a"+j);b.innerHTML='<div class="motion_hslider_cont" data-mjf="motion_hslider_cont" id="'+a+'">'+b.innerHTML+"</div>";$m.t.motion.hslider.css_rules+=" #"+a+"{width:"+d*100+"%;}";$m.t.motion.hslider.css_rules+=" .motion_hslider_box_"+a+"{position:relative; width:"+e+"%;}"},construct:function(){for(var a=$m.attr.get_tags_with($m.tags.all,$m.data_att,
this.data_att),b=!1,c=0,d=a.length;c<d;c++)$m.css_class.add(a[c],"visibility_hidden"),b=a[c].getAttribute("id"),this.create(b);b=document.createElement("style");b.setAttribute("type","text/css");b.setAttribute("media","screen");$m.vd.is_msie8_or_lower===!0?b.style.cssText=$m.t.motion.hslider.css_rules:b.innerHTML=$m.t.motion.hslider.css_rules;$m.head_tag.appendChild(b);c=0;for(d=a.length;c<d;c++)$m.css_class.remove(a[c],"visibility_hidden");$m.elements.bind($m.tags.img,this.data_att_img,"mouseover",
this.img_hover);$m.elements.bind($m.tags.img,this.data_att_img,"mouseout",this.img_hover);$m.elements.bind($m.tags.img,this.data_att_img,"click",this.img_hover);$m.elements.bind($m.tags.a,this.data_att_link,"click",this.exec);c=0;for(c in $m.t.motion.hslider.sliders)$m.t.motion.hslider.sliders[c].autostart===!0&&$m.t.motion.hslider.cycle(c,0),setTimeout(function(){$m.css_class.add(c,"motion_slider_animation")},500)},img_hover:function(a){var b=$m.attr.get(a,"src"),c=$m.attr.get(a,"data-mjf_mhs_link_img_on");
if(c!==null)$m.id(a).src=c,$m.attr.set(a,{"data-mjf_mhs_link_img_on":b})},img_reset:function(a){var b=$m.attr.get(a,"src"),c=$m.attr.get(a,"data-mjf_mhs_link_img_default");if(b!=c)$m.id(a).src=c,$m.attr.set(a,{"data-mjf_mhs_link_img_on":b})},exec:function(a,b){var c=$m.attr.get(a,"data-mjf_mhs_scroll_to"),d=$m.attr.get(a,"data-mjf_mhs_id"),e=$m.attr.get(a,"data-mjf_mhs_pos"),f=$m.attr.get(a,"data-mjf_ga_track"),h="";$m.is.alive(b)===!0&&$m.is.alive($m.t.motion.hslider.sliders[d])===!0&&clearTimeout($m.t.motion.hslider.sliders[d].timeout);
if(d!==null&&e!==null){$m.vd.is_gecko===!0&&(h="-moz-transform:translate("+e+"%, 0px)");$m.vd.is_webkit===!0&&(h="-webkit-transform:translate("+e+"%, 0px)");$m.vd.is_opera===!0&&(h="-o-transform:translate("+e+"%, 0px)");$m.vd.is_trident===!0?$m.vd.is_msie9_or_lower===!0?($m.id(d).style.left=e+"%",$m.de.add_item("$m.id("+d+").style.left = "+$m.id(d).style.left)):$m.attr.set(d,{style:"-ms-transform:translate("+e+"%, 0px)"}):$m.attr.set(d,{style:h});e=0;for(h=$m.t.motion.hslider.sliders[d].links.length;e<
h;e++)$m.t.motion.hslider.img_reset(d+"_img"+(e+1)),$m.css_class.remove($m.t.motion.hslider.sliders[d].links[e],"motion_hslider_ctrls_active");$m.css_class.add(a,"motion_hslider_ctrls_active");$m.id(a).blur();$m.is.alive(c)===!0&&c=="true"&&$m.smooth_scroll.construct(d,50)}f!==null&&$m.track.ga({category:"MJS Motion Horizontal Slider",action:a+"  Click",label:$m.tags.strip.from_id(a)})},cycle:function(a,b){$m.t.motion.hslider.sliders[a].timeout=setTimeout(function(){$m.t.motion.hslider.exec($m.t.motion.hslider.sliders[a].links[b]);
b++;b>=$m.t.motion.hslider.sliders[a].links.length&&(b=0);$m.t.motion.hslider.sliders[a].cnt=b;$m.t.motion.hslider.cycle(a,b)},$m.t.motion.hslider.sliders[a].delay)},play:function(a){$m.t.motion.hslider.cycle(a,$m.t.motion.hslider.sliders[a].cnt)},pause:function(a){clearTimeout($m.t.motion.hslider.sliders[a].timeout)}},fade_inout:{name:"fade_inout",data_att:"motion_fade_inout",data_att_delay:"data-mjf_fade_inout_delay",data_att_box:"motion_fade_inout_box",groups:[],delays:[],timeouts:[],cnts:[],lengths:[],
increments:50,construct:function(a){if($m.is.string(a)===!0)this.increments=a;for(var a=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),b="",c=[],d=0,e=a.length;d<e;d++){b=a[d].getAttribute("id");this.groups[b]=[];this.delays[b]=a[d].getAttribute(this.data_att_delay)*1E3;this.timeouts[b]=!1;this.cnts[b]=-1;c=$m.attr.get_tags_with($m.tags.get(b,"*"),$m.data_att,this.data_att_box);this.lengths[b]=c.length;for(var f=0;f<this.lengths[b];f++)this.groups[b].push(c[f].getAttribute("id"));$m.t.motion.fade_inout.exec(b)}},
exec:function(a){$m.t.motion.fade_inout.cnts[a]++;$m.t.motion.fade_inout.cnts[a]==$m.t.motion.fade_inout.lengths[a]&&($m.t.motion.fade_inout.cnts[a]=0);for(var b=0;b<$m.t.motion.fade_inout.lengths[a];b++)$m.css_class.has($m.t.motion.fade_inout.groups[a][b],"display_block")===!0&&$m.animate.opaque($m.t.motion.fade_inout.groups[a][b],"down",$m.t.motion.fade_inout.increments,function(){$m.css_class.remove($m.t.motion.fade_inout.groups[a][b],"display_block")}),$m.css_class.has($m.t.motion.fade_inout.groups[a][b],
"display_none")===!1&&$m.css_class.add($m.t.motion.fade_inout.groups[a][b],"display_none");var c=$m.t.motion.fade_inout.groups[a][$m.t.motion.fade_inout.cnts[a]];current_box_id=$m.id(c);$m.css_class.replace(c,"display_none","display_block");$m.animate.opaque(current_box_id,"up",$m.t.motion.fade_inout.increments);$m.t.motion.fade_inout.timeouts[a]=setTimeout(function(){$m.t.motion.fade_inout.exec(a)},$m.t.motion.fade_inout.delays[a])}},move:{name:"move",data_att:"motion_move",data_att_dir:"data-mjf_mmove_dir",
data_att_amt:"data-mjf_mmove_amt",data_att_delay:"data-mjf_mmove_delay",data_att_speed:"data-mjf_mmove_speed",data_att_steps:"data-mjf_mmove_steps",construct:function(){for(var a=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),b=!1,c=!1,d=!1,e,f=!1,h,g=0,i=a.length;g<i;g++)tmp_ele=a[g],b=$m.attr.get(a[g],$m.t.motion.move.data_att_dir),c=$m.attr.get(a[g],$m.t.motion.move.data_att_amt),c.match("-")?($m.attr.set(a[g],{"data-mjf_mmove_is_positive":"false"}),e=!1):($m.attr.set(a[g],{"data-mjf_mmove_is_positive":"true"}),
e=!0),d=parseInt(c.replace(/[^\d.]/g,"")),tmp_delay=parseInt($m.attr.get(a[g],$m.t.motion.move.data_att_delay))*1E3,f=parseInt($m.attr.get(a[g],$m.t.motion.move.data_att_speed)),h=parseInt($m.attr.get(a[g],$m.t.motion.move.data_att_steps)),setTimeout(function(){$m.t.motion.move.exec({el:tmp_ele,style:b,amt:d,is_positive:e,speed:f,steps:h,timeout:!1})},tmp_delay)},exec:function(a){var b=$m.id(a.el),c=b["offset"+$m.ut.uppercase_first(a.style)],d=$m.attr.get(b,"data-mjf_mmove_final"),e=a.is_positive===
!0?c+a.amt:c-a.amt;$m.is.alive(d)===!1&&(d=e,$m.attr.set(b,{"data-mjf_mmove_final":e}));a.is_positive===!0?c<d?(b.style[a.style]=c+a.steps+"px",a.timeout=setTimeout(function(){$m.t.motion.move.exec(a)},a.speed)):(clearTimeout(a.timeout),b.style[a.style]=$m.attr.get(b,"data-mjf_mmove_final")+"px"):c>d?(b.style[a.style]=c-a.steps+"px",a.timeout=setTimeout(function(){$m.t.motion.move.exec(a)},a.speed)):(clearTimeout(a.timeout),b.style[a.style]=$m.attr.get(b,"data-mjf_mmove_final")+"px")}},vscroller:{name:"vscroller",
data_att:"vscroller",da_autostart:"data-mjf_vscroller_autostart",da_delay:"data-mjf_vscroller_delay",padding:5,items:{},scrollers:{},div_class:"motion_vscroller_box",create:function(a){for(var b=$m.id(a),c=[],d=0,e=b.childNodes.length;d<e;d++)b.childNodes[d].nodeName!="#text"&&b.childNodes[d].nodeName!="#comment"&&c.push('<div class="'+$m.t.motion.vscroller.div_class+'">'+b.childNodes[d].innerHTML+"</div>");$m.t.motion.vscroller.items[a]=c;b.innerHTML='<div class="'+$m.t.motion.vscroller.div_class+
'" id="'+a+'_visible"></div><div class="'+$m.t.motion.vscroller.div_class+'" style="" id="'+a+'_hidden"></div>';b=$m.attr.get(a,this.da_autostart)=="true"?!0:!1;c=$m.attr.get(a,this.da_delay);$m.t.motion.vscroller.scrollers[a]={parent:$m.id(a),visible:$m.id(a+"_visible"),hidden:$m.id(a+"_hidden"),autostart:b,delay:c===null?3E3:c*1E3,current:1,paused:!1};$m.t.motion.vscroller.scrollers[a].visible.innerHTML=$m.t.motion.vscroller.items[a][0];$m.t.motion.vscroller.scrollers[a].hidden.innerHTML=$m.t.motion.vscroller.items[a][1]},
set_top:function(a,b){a.style.top=$m.t.motion.vscroller.padding+"px";b.style.top=Math.max(a.parentNode.offsetHeight,a.offsetHeight)+"px"},swap:function(a){var a=$m.t.motion.vscroller.scrollers[a],b=a.visible;a.visible=a.hidden;a.hidden=b},construct:function(){for(var a=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),b=!1,c=0,d=a.length;c<d;c++)b=a[c].getAttribute("id"),this.create(b),this.init(b);$m.elements.bind(a,this.data_att,"mouseover",this.stop);$m.elements.bind(a,this.data_att,
"mouseout",this.start)},init:function(a){var b=$m.t.motion.vscroller.scrollers[a];$m.t.motion.vscroller.set_top(b.visible,b.hidden);b.autostart===!0&&setTimeout(function(){$m.t.motion.vscroller.slide_up(a)},b.delay)},slide_up:function(a){var b=$m.t.motion.vscroller.scrollers[a];parseInt(b.hidden.style.top)>$m.t.motion.vscroller.padding+5?(b.visible.style.top=parseInt(b.visible.style.top)-5+"px",b.hidden.style.top=parseInt(b.hidden.style.top)-5+"px",setTimeout(function(){$m.t.motion.vscroller.slide_up(a)},
15)):($m.t.motion.vscroller.set_top(b.hidden,b.visible),$m.t.motion.vscroller.swap(a),setTimeout(function(){$m.t.motion.vscroller.rotate(a)},b.delay))},rotate:function(a){var b=$m.t.motion.vscroller.scrollers[a];if($m.t.motion.vscroller.scrollers[a].paused===!0)setTimeout(function(){$m.t.motion.vscroller.rotate(a)},1E3);else{var c=b.current;$m.t.motion.vscroller.scrollers[a].current=c+1>$m.t.motion.vscroller.items[a].length-1?0:c+1;b.hidden.innerHTML=$m.t.motion.vscroller.items[a][b.current];$m.t.motion.vscroller.slide_up(a)}},
start:function(a){$m.t.motion.vscroller.scrollers[a].paused=!1;$m.t.motion.vscroller.scrollers[a].autostart===!1&&setTimeout(function(){$m.t.motion.vscroller.slide_up(a)},$m.t.motion.vscroller.scrollers[a].delay)},stop:function(a){$m.t.motion.vscroller.scrollers[a].paused=!0}},swipe:{name:"swipe",eid:"motion_swipe",inside_id:"motion_swipe_inside",left_id:"motion_swipe_left",right_id:"motion_swipe_right",div_class:"motion_swipe_box",end_id:"motion_end_id",cylon:{},timeout:!1,speed:0,update_kids:function(){var a=
$m.id($m.t.motion.swipe.inside_id),b=!1;if(a===!1)return!1;for(var c=0,d=a.childNodes.length;c<d;c++)if(a.childNodes[c].nodeName!="#text"&&a.childNodes[c].nodeName!="#comment")a.childNodes[c].className=$m.t.motion.swipe.div_class,b=c;if($m.id(a.childNodes[b].id)===!1)a.childNodes[b].id=$m.t.motion.swipe.end_id;else return!1;$m.css_class.add($m.t.motion.swipe.eid,"background_none");$m.css_class.remove($m.t.motion.swipe.inside_id,"visibility_hidden");$m.css_class.remove($m.t.motion.swipe.left_id,"visibility_hidden");
$m.css_class.remove($m.t.motion.swipe.right_id,"visibility_hidden");return!0},construct:function(){if(this.update_kids()===!1)return $m.de.throw_browser_error("trick.motion.swipe is not initialized correctly"),!1;this.eid=$m.id(this.eid);this.inside_id=$m.id(this.inside_id);this.inside_id.style.left=$m.id(this.left_id).offsetWidth+"px";var a=this.inside_id.offsetLeft,b=this.eid.offsetWidth-$m.id($m.t.motion.swipe.end_id).offsetWidth-15,c=b-$m.id(this.end_id).offsetLeft-32;this.cylon={left:a,width:b,
xpos_min:c,xpos_max:a};$m.element.bind(this.left_id,"mousedown",this.slide_start);$m.element.bind(this.left_id,"mouseup",this.slide_stop);$m.element.bind(this.right_id,"mousedown",this.slide_start);$m.element.bind(this.right_id,"mouseup",this.slide_stop)},slide_start:function(){clearTimeout($m.t.motion.swipe.timeout);var a=this.id,b=$m.id(a),c=0;if(a=="motion_swipe_right")c=Math.floor(b.offsetLeft/1),$m.t.motion.swipe.speed=-1*c,$m.t.motion.swipe.speed=Math.max(-10,$m.t.motion.swipe.speed);else if(c=
10-Math.floor(b.offsetLeft/5),$m.t.motion.swipe.speed=1*c,$m.t.motion.swipe.speed=Math.min(20,$m.t.motion.swipe.speed),$m.t.motion.swipe.speed<0)$m.t.motion.swipe.speed=10;$m.t.motion.swipe.slide_do()},slide_do:function(){var a=$m.t.motion.swipe.inside_id.offsetLeft,a=a/1+$m.t.motion.swipe.speed;a>$m.t.motion.swipe.cylon.xpos_max?(a=$m.t.motion.swipe.cylon.xpos_max,$m.t.motion.swipe.speed=0):a<$m.t.motion.swipe.cylon.xpos_min?(a=$m.t.motion.swipe.cylon.xpos_min,$m.t.motion.swipe.speed=0):($m.t.motion.swipe.inside_id.style.left=
a+"px",$m.t.motion.swipe.timeout=setTimeout(function(){$m.t.motion.swipe.slide_do()},35))},slide_stop:function(){clearTimeout($m.t.motion.swipe.timeout);$m.t.motion.swipe.speed=0}},flick:{name:"flick",eid:"motion_flick",inside_id:"motion_flick_inside",top_id:"motion_flick_top",bottom_id:"motion_flick_bottom",div_class:"motion_flick_box",end_id:"motion_end_id",data_att_autostart:"data-mjf_mflick_autostart",autostart:!1,cylon:{},timeout:!1,speed:!1,increment:0,update_kids:function(){var a=$m.id($m.t.motion.flick.inside_id),
b=!1;if(a===!1)return!1;for(var c=0,d=a.childNodes.length;c<d;c++)if(a.childNodes[c].nodeName!="#text"&&a.childNodes[c].nodeName!="#comment")a.childNodes[c].className=$m.t.motion.flick.div_class,b=c;if($m.id(a.childNodes[b].id)===!1)a.childNodes[b].id=$m.t.motion.flick.end_id;else return!1;$m.css_class.add($m.t.motion.flick.eid,"background_none");$m.css_class.remove($m.t.motion.flick.inside_id,"visibility_hidden");$m.css_class.remove($m.t.motion.flick.top_id,"visibility_hidden");$m.css_class.remove($m.t.motion.flick.bottom_id,
"visibility_hidden");return!0},construct:function(){if(this.update_kids()===!1)return $m.de.throw_browser_error("trick.motion.flick is not initialized correctly"),!1;var a=this.eid;this.eid=$m.id(this.eid);this.inside_id=$m.id(this.inside_id);this.inside_id.style.top=$m.id(this.top_id).offsetHeight+"px";var b=this.inside_id.offsetTop,c=this.eid.offsetHeight-$m.id($m.t.motion.flick.end_id).offsetHeight-15,d=c-$m.id(this.end_id).offsetTop-32;this.cylon={top:b,height:c,ypos_min:d,ypos_max:b};if($m.attr.get(a,
this.data_att_autostart)!==null)this.autostart=!0,$m.t.motion.flick.timeout=setTimeout(function(){$m.t.motion.flick.slide_start($m.t.motion.flick.bottom_id)},5E3);$m.element.bind(this.top_id,"mousedown",this.slide_start);$m.element.bind(this.top_id,"mouseup",this.slide_stop);$m.element.bind(this.bottom_id,"mousedown",this.slide_start);$m.element.bind(this.bottom_id,"mouseup",this.slide_stop);$m.element.bind(a,"mouseover",this.slide_stop)},slide_start:function(a){clearTimeout($m.t.motion.flick.timeout);
$m.is.object(a)===!0?(a=this.id,$m.t.motion.flick.speed=15):$m.t.motion.flick.speed=150;var b=$m.id(a),c=0;if(a=="motion_flick_bottom")c=Math.floor(b.offsetTop/5),$m.t.motion.flick.increment=-1*c,$m.t.motion.flick.increment=Math.max(-10,$m.t.motion.flick.increment);else if(c=10-Math.floor(b.offsetTop/5),$m.t.motion.flick.increment=1*c,$m.t.motion.flick.increment=Math.min(10,$m.t.motion.flick.increment),$m.t.motion.flick.increment<0)$m.t.motion.flick.increment=100;$m.t.motion.flick.slide_do()},slide_do:function(){var a=
$m.t.motion.flick.inside_id.offsetTop,a=a/1+$m.t.motion.flick.increment;if(a>$m.t.motion.flick.cylon.ypos_max){if(a=$m.t.motion.flick.cylon.ypos_max,$m.t.motion.flick.increment=0,$m.t.motion.flick.autostart===!0)clearTimeout($m.t.motion.flick.timeout),$m.t.motion.flick.timeout=setTimeout(function(){$m.t.motion.flick.slide_start($m.t.motion.flick.bottom_id)},5E3)}else if(a<$m.t.motion.flick.cylon.ypos_min){if(a=$m.t.motion.flick.cylon.ypos_min,$m.t.motion.flick.increment=0,$m.t.motion.flick.autostart===
!0)clearTimeout($m.t.motion.flick.timeout),$m.t.motion.flick.timeout=setTimeout(function(){$m.t.motion.flick.slide_start($m.t.motion.flick.top_id)},5E3)}else $m.t.motion.flick.inside_id.style.top=a+"px",$m.t.motion.flick.timeout=setTimeout(function(){$m.t.motion.flick.slide_do()},$m.t.motion.flick.speed)},slide_stop:function(){clearTimeout($m.t.motion.flick.timeout);$m.t.motion.flick.increment=0}}};
