/***************************************************************************
- File: magic_ratings.js
- Version: 13.4.22
***************************************************************************/

$m.trick.magic_ratings={};
$m.t.magic_ratings={name:"magic_ratings",construct:function(){},links:{name:"links",data_att:"magic_rating_links",data_att_state:"data-mjf_magic_ratings_state",data_att_parent:"data-mjf_magic_ratings_parent",data_att_value:"data-mjf_magic_ratings_value",data_att_click:"magic_ratings_links_click",groups:[],construct:function(){this.groups=[];for(var c=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),a="",b=[],d=[],e="",f=0,h=c.length;f<h;f++){a=$m.attr.get(c[f],"id");$m.is.array(this.groups[a])===
!1&&(this.groups[a]=[]);for(var b=$m.tags.get(c[f],"a"),g=0,i=b.length;g<i;g++)d.push(b[g]),e=$m.attr.get(b[g],this.data_att_state)=="on"?"on":"off",$m.is.alive($m.attr.get(b[g],this.data_att_parent))===!1&&$m.attr.set(b[g],{"data-mjf_magic_ratings_parent":a,"class":"magic_rating_link magic_rating_link_"+e}),this.groups[a].push($m.attr.get(b[g],"id"))}$m.elements.bind(d,this.data_att_click,"mouseover",this.over);$m.elements.bind(d,this.data_att_click,"mouseout",this.out);$m.elements.bind(d,this.data_att_click,
"click",this.click)},over:function(c){for(var a=$m.attr.get(c,$m.t.magic_ratings.links.data_att_parent),a=$m.t.magic_ratings.links.groups[a],b=!1,d=0,e=a.length;d<e;d++)a[d]==c&&(b=!0),b===!0?$m.css_class.add(a[d],"magic_rating_link_off_tmp"):$m.css_class.add(a[d],"magic_rating_link_hover")},out:function(c){for(var c=$m.attr.get(c,$m.t.magic_ratings.links.data_att_parent),c=$m.t.magic_ratings.links.groups[c],a=0,b=c.length;a<b;a++)$m.css_class.remove(c[a],"magic_rating_link_off_tmp"),$m.css_class.remove(c[a],
"magic_rating_link_hover")},click:function(c){var a=$m.attr.get(c,$m.t.magic_ratings.links.data_att_value),b="magic_rating="+encodeURIComponent(a),a=$m.attr.get(c,$m.t.magic_ratings.links.data_att_parent),d=$m.attr.get(a,"data-mjf_ajax_query"),e=$m.t.magic_ratings.links.groups[a],f=!1,d=$m.is.alive(d)===!0?d+"&"+b:b;$m.attr.set(a,{"data-mjf_ajax_query":d});b=0;for(d=e.length;b<d;b++)e[b]==c?($m.css_class.replace(e[b],"magic_rating_link_off","magic_rating_link_on"),f=!0):f===!0?$m.css_class.replace(e[b],
"magic_rating_link_on","magic_rating_link_off"):$m.css_class.replace(e[b],"magic_rating_link_off","magic_rating_link_on");c=new $m.ajax;c.init(a);c.exec();return!1}}};
