/***************************************************************************
- File: magic_editor.js
- Version: 14.1.12
***************************************************************************/

$m.trick.magic_editor={};
$m.t.magic_editor={name:"magic_editor",data_att:"magic_editor",idiv:!1,debug:!1,config:{},all:{},dds:[],cur_ed:!1,cur_cmd:!1,cur_selection:!1,cur_image:!1,cur_anchor:!1,cur_table:!1,cur_iframe_height:0,cur_iframe_width:0,attributes:["id","class","href","src","alt","title","style","size","rel","param","width","height","colspan","rowspan","align","valign","cols","rows","tabindex","onmouseover","onmousedown","onmouseup","onmousemove","onblur","onfocus","onkeypress","onkeydown","onkeyup","target","longdesc",
"usemap","bgcolor","background","border","lang"],newlines_after:["h\\d","p","div","pre","form","table","ol","ul","li","blockquote","center","dl","dt","dd","dir","fieldset","noscript","iframe","noscript","tr","td","tbody","head"],unsupported:{msie:["undo","redo"]},buttons:{},button_styles:{},types:{simple:["undo","redo","separator","bold","italic","underline","strikethrough","separator","hyperlink","image","separator","list_ordered","list_unordered","separator","indent","outdent","separator","justify_left",
"justify_center","justify_right"],advanced:["undo","redo","separator","bold","italic","underline","strikethrough","separator","content_style","font_family","font_size","font_color","hilite_color","remove_formatting","separator","hyperlink","image","table","video","special_characters","paste_msword","separator","list_ordered","list_unordered","superscript","subscript","separator","indent","outdent","blockquote","separator","justify_left","justify_center","justify_right","separator","view_full","search",
"code_view","separator","help"]},construct:function(a){$m.is.alive($m.lang.magic_editor)===!1&&$m.ajax_init===!1?($m.insert_link.script($m.config.basedir+"tricks/magic_editor/pages/special_character_list.13.6.24.js"),$m.insert_link.script($m.config.basedir+"tricks/magic_editor/pages/word_html_cleaner.js"),$m.insert_link.script($m.config.basedir+"tricks/magic_editor/lang/"+$m.config.lang+".js",function(){$m.t.magic_editor.init(a)})):$m.t.magic_editor.init(a)},init:function(a){if($m.is.alive(a)===!1)return $m.de.throw_browser_error("Magic Editor: $m.trick.magic_editor.config not declared!"),
!1;this.config=a.config;this.load_btns();for(var b=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),c=!1,e=!1,a=0,f=b.length;a<f;a++)c=$m.attr.get(b[a],"id"),e=$m.tag.get_name(c),e=="div"||e=="textarea"?this.load(b[a]):$m.de.throw_browser_error("Magic Editor says `"+c+"` is not a <div> or <textarea> and therefore will be ignored.");if($m.ajax_init===!1&&($m.tag.create($m.body_tag,"div",{id:"magic_editor_idiv","class":"display_none"}),this.idiv=$m.id("magic_editor_idiv"),a=$m.tag.init("iframe",
{id:"magic_editor_palette",name:"magic_editor_palette",src:$m.config.basedir+"tricks/magic_editor/pages/palette.html",scrolling:"no"}),a.style.cssText=$m.vd.is_msie===!0?"height:175px;width:125px;overflow:hidden;":"height:170px;width:119px;",a.style.cssText+="border:1px solid #bcbecd;position:absolute;top:0;left:0;visibility:hidden;z-index:99999;",$m.body_tag.appendChild(a),$m.vd.is_msie===!0))a=$m.id("magic_editor_palette"),a.style.height="175px",a.style.width="125px";b=$m.attr.get_tags_with($m.tags.all,
$m.data_att,"magic_editor_dd_b");a=0;for(f=b.length;a<f;a++)$m.t.magic_editor.dds.push($m.attr.get(b[a],"id"));$m.element.bind($m.body_id,"mousedown",$m.t.magic_editor.hide_everything);$m.elements.bind($m.tags.a,"magic_editor_btn","mouseover",this.over);$m.elements.bind($m.tags.a,"magic_editor_btn","mouseout",this.out);$m.elements.bind($m.tags.a,"magic_editor_btn","click",this.click);$m.elements.bind($m.tags.get($m.document,"div"),"magic_editor_dd","mouseover",this.over);$m.elements.bind($m.tags.get($m.document,
"div"),"magic_editor_dd","mouseout",this.out);$m.elements.bind($m.tags.get($m.document,"div"),"magic_editor_dd","click",this.toggle_dropdown);$m.elements.bind($m.tags.a,"magic_editor_dd_item","mousedown",this.click);$m.elements.bind($m.tags.a,"magic_editor_pa","mouseover",this.over);$m.elements.bind($m.tags.a,"magic_editor_pa","mouseout",this.out);$m.elements.bind($m.tags.a,"magic_editor_pa","click",this.show_palette);$m.elements.bind($m.tags.a,"magic_editor_dr","mouseover",this.over);$m.elements.bind($m.tags.a,
"magic_editor_dr","mouseout",this.out);$m.elements.bind($m.tags.a,"magic_editor_dr","click",this.click_dr);$m.elements.bind($m.tags.form,"magic_editor_form","submit",this.send);$m.shortcut.bind("esc",function(){$m.t.magic_editor.hide_everything()});$m.t.darkroom.init()},load:function(a){var b=$m.attr.get(a,"id"),c=$m.id(b);$m.t.magic_editor.all[b]=b;if($m.is.alive($m.attr.get(b,"data-mjf_magic_editor_has"))===!1){$m.css_class.add(b,"display_none");$m.css_class.add(b,"magic_editor_code");var e=$m.tag.get_name(b)==
"textarea"?!0:!1,f="magic_editor_"+b+"_1_c",h=$m.tag.init("div",{"class":"display_none magic_editor_container",id:f});a.parentNode.insertBefore(h,c);var k=$m.id(f),h="magic_editor_"+b+"_1_tb",l=$m.tag.init("div",{"class":"magic_editor_toolbar magic_editor_toolbar_1st",id:h});k.appendChild(l);var j="magic_editor_"+b,l=$m.tag.init("iframe",{"class":"magic_editor_iframe display_none",id:j,name:j,"data-mjf":"magic_editor_frame",height:e===!0?a.rows*15:"400",src:"about:blank"});k.appendChild(l);var c=
e===!0?c.value:c.innerHTML,g=$m.id(j).contentWindow.document;g.open();g.write(c);g.close();g.body.contentEditable=!0;$m.element.attach(g,"mousedown",$m.t.magic_editor.hide_everything);$m.element.attach(g,"keypress",$m.t.magic_editor.hide_everything);setTimeout(function(){for(var a=g.getElementsByTagName("head"),e=$m.t.magic_editor.config.css_links,c=!1,f=0,h=e.length;f<h;f++)c=g.createElement("link"),c.setAttribute("href",e[f]),c.setAttribute("rel","stylesheet"),c.setAttribute("type","text/css"),
a[0].appendChild(c);a=g.getElementsByTagName("body")[0];$m.attr.set(a,{id:"magic_editor_content_body"});$m.element.attach(a,"mousedown",function(a){$m.t.magic_editor.cur_image=!1;$m.t.magic_editor.cur_anchor=!1;$m.t.magic_editor.cur_table=!1;$m.t.magic_editor.find_element(b,a)});$m.element.attach(a,"mouseup",function(a){$m.t.magic_editor.selection.save(j,a);$m.t.magic_editor.bind_iframe_elements(b)});$m.element.attach(a,"dblclick",function(a){$m.t.magic_editor.selection.save(j,a);$m.t.magic_editor.bind_iframe_elements(b)});
$m.element.attach(a,"keyup",function(a){$m.t.magic_editor.selection.save(j,a);$m.t.magic_editor.bind_iframe_elements(b)});parent.$m.shortcut.bind("esc",function(){parent.$m.t.darkroom.hide_all()},{target:g});$m.t.magic_editor.bind_iframe_elements(b);$m.css_class.remove(j,"display_none")},0);this.load_toolbar(h,b,g);$m.css_class.remove(f,"display_none");$m.attr.set(a,{"data-mjf_magic_editor_has":"true"});setTimeout(function(){try{g.execCommand("enableInlineTableEditing",!1,!1)}catch(a){}},100)}},find_element:function(a,
b){var c=$m.event.get_target(b),e=$m.tag.get_name(c),f=c.parentNode;$m.tag.get_name(f);var h=!1;$m.t.magic_editor.btns_deactivate(a);$m.t.magic_editor.btns_activate(c,a);if(e=="table")$m.t.magic_editor.cur_table=c;for(;f!=null;)if($m.t.magic_editor.btns_activate(f,a),f=f.parentNode,$m.tag.get_name(f),$m.tag.get_name(f)=="table"&&h===!1)$m.t.magic_editor.cur_table=f,h=!0},btns_deactivate:function(a){for(var b=$m.tags.get("magic_editor_"+a+"_1_tb","a"),a=$m.tags.get("magic_editor_"+a+"_1_tb","div"),
c=null,e=0,f=b.length;e<f;e++)$m.t.magic_editor.out($m.attr.get(b[e],"id"));e=0;for(f=a.length;e<f;e++)c=$m.attr.get(a[e],"id"),$m.is.alive(c)===!0&&$m.t.magic_editor.out($m.attr.get(a[e],"id"))},btns_activate:function(a,b){var c=$m.is.string(a)===!0?$m.id(a):a,e=$m.tag.get_name(c),f=!1;if($m.is.alive(c.style)===!0)switch(c.style.fontWeight=="bold"&&$m.t.magic_editor.over("magic_editor_btn_bold_"+b),c.style.textDecoration=="underline"&&$m.t.magic_editor.over("magic_editor_btn_underline_"+b),c.style.textDecoration==
"line-through"&&$m.t.magic_editor.over("magic_editor_btn_strikethrough_"+b),$m.is.alive(c.style.fontFamily)===!0&&$m.t.magic_editor.over("magic_editor_dd_font_family_"+b),$m.is.alive(c.style.fontSize)===!0&&$m.t.magic_editor.over("magic_editor_dd_font_size_"+b),$m.is.alive(c.style.color)===!0&&$m.t.magic_editor.over("magic_editor_btn_font_color_"+b),$m.is.alive(c.style.backgroundColor)===!0&&$m.t.magic_editor.over("magic_editor_btn_hilite_color_"+b),c.style.textAlign){case "center":$m.t.magic_editor.over("magic_editor_btn_justify_center_"+
b);break;case "right":$m.t.magic_editor.over("magic_editor_btn_justify_right_"+b);break;case "left":$m.t.magic_editor.over("magic_editor_btn_justify_left_"+b)}switch(e){case "b":case "strong":f="bold";break;case "i":case "em":f="italic";break;case "u":f="underline";break;case "a":f="hyperlink";break;case "img":f="image";break;case "table":f="table";break;case "ol":f="list_ordered";break;case "ul":f="list_unordered";break;case "sup":f="superscript";break;case "sub":f="subscript";break;case "blockquote":f=
"blockquote"}f!==!1&&$m.t.magic_editor.over("magic_editor_btn_"+f+"_"+b)},bind_iframe_elements:function(a){for(var b=$m.tag.get_iframe_doc("magic_editor_"+a),c=b.images,b=b.getElementsByTagName("a"),e=!1,f=0,e=c.length;f<e;f++)$m.vd.is_msie===!0?c[f].onclick=function(){$m.t.magic_editor.cur_image=this;$m.exec.go("magic_editor_btn_image_"+a,"onclick");return!1}:$m.element.attach(c[f],"dblclick",function(){$m.t.magic_editor.cur_image=this;$m.exec.go("magic_editor_btn_image_"+a,"onclick");return!1});
f=0;for(c=b.length;f<c;f++){for(var e=!1,h=0,k=children_len=b[f].childNodes.length;h<k;h++)if(b[f].childNodes[h].nodeName=="IMG"){e=!0;break}if(e!==!0)$m.vd.is_msie===!0?b[f].ondblclick=function(){$m.t.magic_editor.selection.txt=this.innerHTML;$m.t.magic_editor.cur_anchor=this;$m.exec.go("magic_editor_btn_hyperlink_"+a,"onclick");return!1}:$m.element.attach(b[f],"dblclick",function(){$m.t.magic_editor.selection.txt=this.innerHTML;$m.t.magic_editor.cur_anchor=this;$m.exec.go("magic_editor_btn_hyperlink_"+
a,"onclick");return!1})}},load_toolbar:function(a,b,c){var e=$m.t.magic_editor.types[$m.t.magic_editor.config.type],f=$m.t.magic_editor.btns,h="",k={},l={},j="",g;for(g in e)if(e[g]=="separator")h+='<div class="magic_editor_btn magic_editor_seperator"></div>';else switch(f[e[g]].command_type){case "dropdown":h+='<div title="'+f[e[g]].title+'" class="magic_editor_btn magic_editor_btn_'+e[g]+'" data-mjf="magic_editor_dd" data-mjf_me_cmd="'+e[g]+'" data-mjf_me_editor="editor_'+b+'" data-mjf_me_taid="'+
b+'" id="magic_editor_dd_'+e[g]+"_"+b+'"><p class="magic_editor_dd_list" data-mjf="magic_editor_dd_b" id="magic_editor_dd_'+e[g]+"_"+b+'_b">';for(var j=0,m=f[e[g]].options.length;j<m;j++)h+='<a href="#" style="'+f[e[g]].styles[j]+'" data-mjf="magic_editor_dd_item" data-mjf_me_editor="editor_'+b+'" data-mjf_me_cmd="'+e[g]+'" data-mjf_me_cmd_opt="'+j+'" data-mjf_me_parent="magic_editor_dd_'+e[g]+"_"+b+'_b" data-mjf_me_taid="'+b+'" id="magic_editor_dd_item_'+e[g]+"_"+b+j+'">'+f[e[g]].options[j]+"</a>";
h+="</p></div>";break;case "palette":h+='<a href="#" title="'+f[e[g]].title+'" class="magic_editor_btn magic_editor_btn_'+e[g]+'" data-mjf="magic_editor_pa" data-mjf_me_cmd="'+e[g]+'" data-mjf_me_editor="editor_'+b+'" data-mjf_me_taid="'+b+'" id="magic_editor_btn_'+e[g]+"_"+b+'"></a>';break;case "darkroom":h+='<a href="#" title="'+f[e[g]].title+'" class="magic_editor_btn magic_editor_btn_'+e[g]+'" data-mjf="magic_editor_dr|darkroom|return_false" data-mjf_dr_type="iframe" data-mjf_dr_iframe_src="'+
f[e[g]].darkroom_url+'" data-mjf_dr_iframe_dim="'+f[e[g]].darkroom_dims+'" data-mjf_me_cmd="'+e[g]+'" data-mjf_me_editor="editor_'+b+'" data-mjf_me_taid="'+b+'" id="magic_editor_btn_'+e[g]+"_"+b+'"></a>';break;default:if($m.vd.is_msie===!0&&$m.is.in_array($m.t.magic_editor.unsupported.msie,e[g])!==!1)continue;j="magic_editor_btn_"+e[g]+"_"+b;if($m.is.alive(f[e[g]].win_keystroke)===!0)k[j]=f[e[g]].win_keystroke;if($m.is.alive(f[e[g]].mac_keystroke)===!0)l[j]=f[e[g]].mac_keystroke;h+='<a href="#" title="'+
f[e[g]].title+'" class="magic_editor_btn magic_editor_btn_'+e[g]+'" data-mjf="magic_editor_btn" data-mjf_me_cmd="'+e[g]+'" data-mjf_me_editor="editor_'+b+'" data-mjf_me_taid="'+b+'" id="'+j+'"></a>'}$m.id(a).innerHTML=h+'<br class="clear_both">';if($m.vd.is_windows===!0||$m.vd.is_linux===!0)for(l in l=!1,k)$m.shortcut.bind(k[l],"$m.t.magic_editor.click('"+l+"');",{target:c});else if($m.vd.is_macintosh===!0)for(k in k=!1,l)$m.shortcut.bind(l[k],"$m.t.magic_editor.click('"+k+"');",{target:c})},click:function(a,
b){var c=$m.id(a),e="magic_"+$m.attr.get(a,"data-mjf_me_editor"),f=$m.id(e).contentWindow.document,h=$m.attr.get(a,"data-mjf_me_cmd"),k=$m.tag.get_iframe_doc("magic_"+$m.attr.get(a,"data-mjf_me_editor"));$m.vd.is_msie===!1&&($m.t.magic_editor.btns[h].use_css===!0?f.execCommand("styleWithCSS",null,!0):f.execCommand("styleWithCSS",null,!1));switch($m.t.magic_editor.btns[h].command_type){case "default":f.execCommand($m.t.magic_editor.btns[h].command(),!1,null);break;case "dropdown":$m.vd.is_msie===!0&&
$m.t.magic_editor.selection.restore(e);f.execCommand($m.t.magic_editor.btns[h].command(),!1,$m.t.magic_editor.btns[h].values[$m.attr.get(a,"data-mjf_me_cmd_opt")]);break;case "custom":$m.t.magic_editor.btns[h].command(a,b)}c.blur();$m.t.magic_editor.set_cur_ed(a);$m.t.magic_editor.btns_deactivate($m.attr.get(a,"data-mjf_me_taid"));k.body.focus();return!1},click_dr:function(a,b){var c=$m.attr.get(a,"data-mjf_me_taid"),e="magic_"+$m.attr.get(a,"data-mjf_me_editor");$m.id(a).blur();$m.t.magic_editor.set_cur_ed(a);
$m.is.alive($m.id(c).value)===!1&&($m.tag.get_iframe_doc(e).body.focus(),$m.t.magic_editor.selection.save(e,b))},over:function(a){$m.id(a).style.borderColor="#b2bcd0"},out:function(a){$m.id(a).style.borderColor=$m.vd.is_msie6_or_lower===!0?"#dbdbda":"transparent"},toggle_dropdown:function(a,b){$m.css_class.add(a+"_b","visibility_visible");$m.id("magic_editor_palette").style.visibility="hidden";$m.id(a).focus();$m.stop_bubble(b);return!1},show_palette:function(a,b){var c=$m.id(a),e=$m.position.get_xy(a),
f=$m.id("magic_editor_palette");$m.t.magic_editor.hide_dropdowns();f.style.left=e[0]+"px";f.style.top=e[1]+19+"px";c.style.borderColor="#bcbecd";$m.t.magic_editor.set_cur_ed(a);f.style.visibility="visible";$m.stop_bubble(b);return!1},set_cur_ed:function(a){$m.t.magic_editor.cur_ed=$m.attr.get(a,"data-mjf_me_editor");$m.t.magic_editor.cur_cmd=$m.attr.get(a,"data-mjf_me_cmd")},hide_dropdowns:function(){for(var a=0,b=$m.t.magic_editor.dds.length;a<b;a++)$m.css_class.remove($m.t.magic_editor.dds[a],"visibility_visible")},
hide_everything:function(){$m.id("magic_editor_palette").style.visibility="hidden";$m.t.magic_editor.hide_dropdowns()},selection:{txt:"",html:"",save:function(a,b){var c=$m.id(a).contentWindow,e=c.document;$m.vd.is_msie8_or_lower?($m.t.magic_editor.cur_selection=e.selection.createRange(),$m.t.magic_editor.selection.html=$m.t.magic_editor.cur_selection.htmlText):($m.t.magic_editor.cur_selection=c.getSelection(),$m.t.magic_editor.idiv.innerHTML="",$m.t.magic_editor.idiv.appendChild($m.t.magic_editor.cur_selection.getRangeAt(0).cloneContents()),
$m.t.magic_editor.selection.html=$m.t.magic_editor.idiv.innerHTML);$m.t.magic_editor.selection.txt=$m.t.magic_editor.selection.get_as_text(a);if($m.is.alive(b)===!0)$m.t.magic_editor.selection.event=$m.event.get(b),$m.t.magic_editor.selection.event_target=$m.event.get_target($m.t.magic_editor.selection.event)},restore:function(a){a=$m.id(a).contentWindow.document;if(a.selection&&a.selection.createRange)try{var b=a.body.createTextRange();b.findText($m.t.magic_editor.selection.html);b.select()}catch(c){}},
get_as_text:function(a){var a=$m.id(a).contentWindow,b=a.document,c=$m.t.magic_editor.cur_selection;if(a.getSelection)return c.toString();else if(b.selection&&b.selection.createRange)return c.text}},replace_entities:function(a){var b="",c;for(c in $m.t.magic_editor.entities)for(var e in $m.t.magic_editor.entities[c])b=RegExp(String.fromCharCode($m.t.magic_editor.entities[c][e][1]),"gm"),a=a.replace(b,"&"+e+";");return a},clean:function(a){var b="",c="";a.replace(/^\s+|\s+$/g,"");c="<$1$2";a=a.replace(RegExp("<(/?)([A-Z]+)",
"g"),function(a){return a.toLowerCase()});b=String.fromCharCode(8226);c=String.fromCharCode(183);a=a.replace(RegExp("<p class=MsoHeading.*?>(.*?)</p>","gim"),"<p><strong>$1</strong></p>");a=a.replace(RegExp("<span>(.*?)</span>","gim"),"$1");a=a.replace(/<o:p><\/o:p>/gim,"");a=a.replace(RegExp(' class="?MsoNormal"?',"gim"),"");a=a.replace(RegExp(' class="?NormalWeb7"?',"gim"),"");a=a.replace(RegExp(' style="margin: 0in 0in 0pt;?"',"gim"),"");a=a.replace(RegExp(' style=""',"gim"),"");a=a.replace(RegExp("mso-bidi-font-weight",
"gim"),"font-weight");a=a.replace(RegExp('<b style="font-weight: normal">(.+?)</b>',"gim"),"$1");a=a.replace(RegExp(' style="mso-tab-count: [0-9]+"',"gim"),"");a=a.replace(RegExp('tab-stops: list [0-9]+.0pt">',"gim"),'">--list--');a=a.replace(RegExp(b+"(.*?)<BR>","gim"),"<p>"+c+"$1</p>");a=a.replace(RegExp('<SPAN style="mso-list: Ignore">',"gim"),"<span>"+b);a=a.replace(RegExp("<b>(.*?)</b>","gim"),"<strong>$1</strong>");a=a.replace(RegExp("<i>(.*?)</i>","gim"),"<em>$1</em>");a=a.replace(RegExp("-moz-background-inline-policy:",
"gim"),"");a=a.replace(RegExp("-moz-background-origin:","gim"),"");a=a.replace(RegExp("-moz-background-clip:","gim"),"");a=a.replace(RegExp("\\s-moz-initial;","gim"),"");a=a.replace(RegExp(' class="?Apple-style-span"?',"gim"),"");a=a.replace(RegExp(' class="?webkit-block-placeholder"?',"gim"),"");for(i=0;i<$m.t.magic_editor.attributes.length;i++)b=RegExp("\\s"+$m.t.magic_editor.attributes[i]+"=([\\w|-]+)\\b","gim"),c=" "+$m.t.magic_editor.attributes[i]+'="$1"',a=a.replace(b,c);c='style="$1"';a=a.replace(RegExp('style="([\\w+-?\\w+\\s?:\\s?\\w+;?]+)"',
"g"),function(a){return a.toLowerCase()});i=0;for(len=$m.t.magic_editor.newlines_after.length;i<len;i++)b=RegExp("</("+$m.t.magic_editor.newlines_after[i]+")>(?!\\n|\\r)","gim"),c="</$1>\n",a=a.replace(b,c);return $m.t.magic_editor.replace_entities(a)},inject_html:function(a,b){var c=$m.tag.get_iframe_doc("magic_"+$m.t.magic_editor.cur_ed),e=c.body;if(e.innerHTML==""||e.innerHTML=="<br>")return e.innerHTML=a,!0;if($m.vd.is_msie8_or_lower===!0)try{switch(b){case "block":a="<div>"+a+"</div>";break;
case "inline":a="<span>"+a+"</span>"}return $m.t.magic_editor.cur_selection.pasteHTML(a)}catch(f){return $m.de.throw_browser_error("$m.t.magic_editor.inject_html() --- cannot pasteHTML()"),!1}else return $m.selection.get(c)==""&&$m.t.magic_editor.selection.restore("magic_"+$m.t.magic_editor.cur_ed),$m.selection.replace(a,c),!0},send:function(a){$m.config.global_debug!==!1&&$m.de.add_item("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \n Executing >>> $m.t.magic_editor.send("+a+
")");$m.id(a);var a=$m.t.magic_editor.all,b="",c="",c="",e;for(e in a)if(b=$m.id(a[e]),c=$m.tag.get_iframe_doc("magic_editor_"+e),!($m.is.alive(b)===!1||c===!1))if(c=$m.css_class.has(b,"display_none")===!0?c.body.innerHTML:c=b.value,b.value=$m.t.magic_editor.clean(c),b.value=b.value.replace(RegExp('<span class="magic_editor_search_results">(.*?)</span>',"gim"),"$1"),b.value=="<br>")b.value="";if($m.t.magic_editor.debug===!0)return!1},load_btns:function(){$m.t.magic_editor.btns={bold:{name:"bold",
use_css:!1,title:$m.lang.magic_editor.btn_titles.bold,win_keystroke:"Ctrl+B",mac_keystroke:"Cmd+B",command_type:"default",command:function(){return"bold"}},italic:{name:"italic",use_css:!1,title:$m.lang.magic_editor.btn_titles.italic,win_keystroke:"Ctrl+I",mac_keystroke:"Cmd+I",command_type:"default",command:function(){return"italic"}},underline:{name:"underline",use_css:!1,title:$m.lang.magic_editor.btn_titles.underline,win_keystroke:"Ctrl+U",mac_keystroke:"Cmd+U",command_type:"default",command:function(){return"underline"}},
strikethrough:{name:"strikethrough",use_css:!0,title:$m.lang.magic_editor.btn_titles.strikethrough,win_keystroke:"",mac_keystroke:"",command_type:"default",command:function(){return"strikethrough"}},justify_left:{name:"justify_left",use_css:!0,title:$m.lang.magic_editor.btn_titles.justify_left,win_keystroke:"",mac_keystroke:"",command_type:"default",command:function(){return"justifyleft"}},justify_center:{name:"justify_center",use_css:!0,title:$m.lang.magic_editor.btn_titles.justify_center,win_keystroke:"",
mac_keystroke:"",command_type:"default",command:function(){return"justifycenter"}},justify_right:{name:"justify_right",use_css:!0,title:$m.lang.magic_editor.btn_titles.justify_right,win_keystroke:"",mac_keystroke:"",command_type:"default",command:function(){return"justifyright"}},list_ordered:{name:"list_ordered",use_css:!1,title:$m.lang.magic_editor.btn_titles.list_ordered,win_keystroke:"",mac_keystroke:"",command_type:"default",command:function(){return"insertorderedlist"}},list_unordered:{name:"list_unordered",
use_css:!1,title:$m.lang.magic_editor.btn_titles.list_unordered,win_keystroke:"",mac_keystroke:"",command_type:"default",command:function(){return"insertunorderedlist"}},indent:{name:"indent",use_css:!0,title:$m.lang.magic_editor.btn_titles.indent,win_keystroke:"",mac_keystroke:"",command_type:"default",command:function(){return"indent"}},outdent:{name:"outdent",use_css:!0,title:$m.lang.magic_editor.btn_titles.outdent,win_keystroke:"",mac_keystroke:"",command_type:"default",command:function(){return"outdent"}},
superscript:{name:"superscript",use_css:!1,title:$m.lang.magic_editor.btn_titles.superscript,win_keystroke:"",mac_keystroke:"",command_type:"default",command:function(){return"superscript"}},subscript:{name:"subscript",use_css:!1,title:$m.lang.magic_editor.btn_titles.subscript,win_keystroke:"",mac_keystroke:"",command_type:"default",command:function(){return"subscript"}},content_style:{name:"content_style",use_css:!1,title:$m.lang.magic_editor.btn_titles.content_style,win_keystroke:"",mac_keystroke:"",
options:[$m.lang.magic_editor.btn_titles.content_style_paragraph,$m.lang.magic_editor.btn_titles.content_style_heading_1,$m.lang.magic_editor.btn_titles.content_style_heading_2,$m.lang.magic_editor.btn_titles.content_style_heading_3],values:["<p>","<h1>","<h2>","<h3>"],styles:["font-size: 12px;","font-size: 18px;","font-size: 16px;","font-size: 14px;"],command_type:"dropdown",command:function(){return"formatblock"}},font_family:{name:"font_family",use_css:!0,title:$m.lang.magic_editor.btn_titles.font_family,
win_keystroke:"",mac_keystroke:"",options:["Arial","Courier New","Georgia","Tahoma","Times New Roman","Verdana"],values:["Arial","Courier New","Georgia","Tahoma","Times New Roman","Verdana"],styles:["font-family: Arial, sans-serif;","font-family: Courier New, monospace;","font-family: Tahoma, sans-serif;","font-family: Times New Roman, serif;","font-family: Georgia, serif;","font-family: Verdana, serif;"],command_type:"dropdown",command:function(){return"fontname"}},font_size:{name:"font_size",use_css:!0,
title:$m.lang.magic_editor.btn_titles.font_size,win_keystroke:"",mac_keystroke:"",options:[$m.lang.magic_editor.btn_titles.font_size_small,$m.lang.magic_editor.btn_titles.font_size_normal,$m.lang.magic_editor.btn_titles.font_size_large,$m.lang.magic_editor.btn_titles.font_size_huge],values:["1","3","5","7"],styles:["font-size: 9px;","font-size: 12px;","font-size: 16px;","font-size: 22px;"],command_type:"dropdown",command:function(){return"fontsize"}},font_color:{name:"font_color",use_css:!0,title:$m.lang.magic_editor.btn_titles.font_color,
win_keystroke:"",mac_keystroke:"",command_type:"palette",command:function(){return"forecolor"}},hilite_color:{name:"hilite_color",use_css:!0,title:$m.lang.magic_editor.btn_titles.hilite_color,win_keystroke:"",mac_keystroke:"",command_type:"palette",command:function(){return $m.vd.is_msie===!0?"backcolor":"hilitecolor"}},blockquote:{name:"blockquote",use_css:!1,title:$m.lang.magic_editor.btn_titles.blockquote,win_keystroke:"",mac_keystroke:"",command_type:"custom",command:function(a,c){$m.t.magic_editor.set_cur_ed(a);
$m.t.magic_editor.selection.save("magic_"+$m.t.magic_editor.cur_ed,c);if($m.vd.is_msie===!0)$m.t.magic_editor.inject_html("<blockquote>"+$m.t.magic_editor.selection.html+"</blockquote>","block");else{var e=$m.attr.get(a,"data-mjf_me_editor"),f=$m.id($m.t.magic_editor.all[$m.attr.get(a,"data-mjf_me_taid")]),e=$m.tag.get_iframe_doc("magic_"+e);f.value=e.body.innerHTML.replace($m.t.magic_editor.selection.html,"MAGIC_EDITOR_PLACEHOLDER");e.body.innerHTML=f.value.match("<p>MAGIC_EDITOR_PLACEHOLDER</p>")?
f.value.replace("<p>MAGIC_EDITOR_PLACEHOLDER</p>","<blockquote><p>"+$m.t.magic_editor.selection.html+"</p></blockquote>"):f.value.replace("MAGIC_EDITOR_PLACEHOLDER","<blockquote>"+$m.t.magic_editor.selection.html+"</blockquote>")}}},remove_formatting:{name:"remove_formatting",use_css:!1,title:$m.lang.magic_editor.btn_titles.remove_formatting,win_keystroke:"",mac_keystroke:"",command_type:"custom",command:function(a){if(confirm($m.lang.magic_editor.confirm_clean_content))a=$m.attr.get(a,"data-mjf_me_editor"),
a=$m.tag.get_iframe_doc("magic_"+a),d=a.body.innerHTML,a.body.innerHTML=cleanHTML(),a.execCommand("removeFormat",!1,null)}},hyperlink:{name:"hyperlink",use_css:!1,title:$m.lang.magic_editor.btn_titles.hyperlink,win_keystroke:"",mac_keystroke:"",command_type:"darkroom",darkroom_url:$m.config.basedir+"tricks/magic_editor/pages/hyperlink.html",darkroom_dims:"400x250",command:function(){}},image:{name:"image",use_css:!1,title:$m.lang.magic_editor.btn_titles.image,win_keystroke:"",mac_keystroke:"",command_type:"darkroom",
darkroom_url:$m.config.basedir+"tricks/magic_editor/pages/image.html",darkroom_dims:"500x565",command:function(){}},video:{name:"video",use_css:!1,title:$m.lang.magic_editor.btn_titles.video,win_keystroke:"",mac_keystroke:"",command_type:"darkroom",darkroom_url:$m.config.basedir+"tricks/magic_editor/pages/video.html",darkroom_dims:"500x320",command:function(){}},paste_msword:{name:"paste_msword",use_css:!1,title:$m.lang.magic_editor.btn_titles.paste_msword,win_keystroke:"",mac_keystroke:"",command_type:"darkroom",
darkroom_url:$m.config.basedir+"tricks/magic_editor/pages/paste_msword.html",darkroom_dims:"850x565",command:function(){}},special_characters:{name:"special_characters",use_css:!1,title:$m.lang.magic_editor.btn_titles.special_characters,win_keystroke:"",mac_keystroke:"",command_type:"darkroom",darkroom_url:$m.config.basedir+"tricks/magic_editor/pages/special_characters.html",darkroom_dims:"505x230",command:function(){}},table:{name:"table",use_css:!1,title:$m.lang.magic_editor.btn_titles.table,win_keystroke:"",
mac_keystroke:"",command_type:"darkroom",darkroom_url:$m.config.basedir+"tricks/magic_editor/pages/table.html",darkroom_dims:"400x540",command:function(){}},view_full:{name:"view_full",use_css:!1,title:$m.lang.magic_editor.btn_titles.view_full,win_keystroke:"",mac_keystroke:"",command_type:"custom",command:function(a){var c=$m.attr.get(a,"data-mjf_me_editor");$m.attr.get(a,"data-mjf_me_taid");var e="magic_"+c+"_1_c",f="magic_"+c+"_1_tb",c=$m.id("magic_"+c);$m.css_class.has(a,"magic_editor_border_4986fe")===
!0?($m.css_class.remove($m.body_id,"overflow_hidden"),$m.css_class.remove(e,"magic_editor_view_full"),$m.css_class.remove(f,"width_full"),c.style.height=$m.t.magic_editor.cur_iframe_height,c.style.width=$m.t.magic_editor.cur_iframe_width,$m.css_class.remove(a,"magic_editor_border_4986fe"),$m.smooth_scroll.construct(e)):($m.smooth_scroll.construct($m.body_id),$m.css_class.add($m.body_id,"overflow_hidden"),$m.css_class.add(e,"magic_editor_view_full"),$m.css_class.add(f,"width_full"),$m.t.magic_editor.cur_iframe_height=
c.style.height,$m.t.magic_editor.cur_iframe_width=c.style.width,$m.vd.get_view_port(),c.style.height=$m.vd.visible_page_height-70+"px",$m.css_class.add(a,"magic_editor_border_4986fe"))}},code_view:{name:"mode_code",use_css:!1,title:$m.lang.magic_editor.btn_titles.code_view,win_keystroke:"",mac_keystroke:"",command_type:"darkroom",darkroom_url:$m.config.basedir+"tricks/magic_editor/pages/code_view.html",darkroom_dims:"850x540",command:function(){}},clean_code:{name:"clean_code",use_css:!1,title:$m.lang.magic_editor.btn_titles.clean_code,
win_keystroke:"",mac_keystroke:"",command_type:"custom",command:function(a){current_iframe="magic_"+$m.attr.get(a,"data-mjf_me_editor");current_textarea=$m.t.magic_editor.all[$m.attr.get(a,"data-mjf_me_taid")];current_iframe_id=$m.id(current_iframe);current_textarea_id=$m.id(current_textarea);iframe_doc=$m.tag.get_iframe_doc(current_iframe);$m.css_class.has(current_textarea,"display_none")===!0?iframe_doc.body.innerHTML=$m.t.magic_editor.clean(iframe_doc.body.innerHTML):current_textarea_id.value=
$m.t.magic_editor.clean(current_textarea_id.value)}},undo:{name:"undo",use_css:!1,title:$m.lang.magic_editor.btn_titles.undo,win_keystroke:"",mac_keystroke:"Cmd+Z",command_type:"default",command:function(){return"undo"}},redo:{name:"redo",use_css:!1,title:$m.lang.magic_editor.btn_titles.redo,win_keystroke:"",mac_keystroke:"Shift+Cmd+Z",command_type:"default",command:function(){return"redo"}},search:{name:"search",use_css:!1,title:$m.lang.magic_editor.btn_titles.search,win_keystroke:"",mac_keystroke:"",
command_type:"darkroom",darkroom_url:$m.config.basedir+"tricks/magic_editor/pages/search.html",darkroom_dims:"400x250",command:function(){}},help:{name:"help",use_css:!1,title:$m.lang.magic_editor.btn_titles.help,win_keystroke:"",mac_keystroke:"",command_type:"darkroom",darkroom_url:$m.vd.is_macintosh===!0?$m.config.basedir+"tricks/magic_editor/pages/help_mac.html":$m.config.basedir+"tricks/magic_editor/pages/help_pc.html",darkroom_dims:"600x500",command:function(){}},separator:{name:"separator"}};
for(var a in $m.t.magic_editor.buttons)$m.t.magic_editor.btns[a]=$m.t.magic_editor.buttons[a]}};
