/***************************************************************************
- File: string_deposit.js
- Version: 13.1.25
***************************************************************************/

$m.trick.string_deposit={};
$m.t.string_deposit={name:"string_deposit",data_att:"string_deposit",data_att_url:"data-mjf_string_deposit_url",data_att_dims:"data-mjf_string_deposit_dims",data_att_has:"data-mjf_strdep_has",data_att_parent:"data-mjf_strdep_parent",data_att_set:"set_strdep",data_att_action:"data-mjf_string_deposit_action",cur:{input:"",cursor:"",action:"insert",deposits:{},deposit_id:!1,deposit_template:!1,deposit_action:"overwrite"},config:{title:"String Deposit",url:"strdep_ex.html",dims:"400x265"},construct:function(){var a=
{},b=!1,c=!1,d=!1,d=!1;if($m.is.alive($m.trick.string_deposit.config)===!0){if($m.is.alive($m.trick.string_deposit.config.title)===!0)this.config.title=$m.trick.string_deposit.config.title;if($m.is.alive($m.trick.string_deposit.config.url)===!0)this.config.url=$m.trick.string_deposit.config.url;if($m.is.alive($m.trick.string_deposit.config.dims)===!0)this.config.dims=$m.trick.string_deposit.config.dims}$m.is.alive($m.trick.magic_editor)===!0&&$m.ajax_init===!1&&($m.t.magic_editor.buttons.string_deposit=
{name:"string_deposit",use_css:!1,title:this.config.title,win_keystroke:"",mac_keystroke:"",command_type:"custom",darkroom_url:this.config.url,darkroom_dims:this.config.dims,command:function(a){var d=$m.attr.get(a,"data-mjf_me_taid");b=$m.attr.get(d,$m.t.string_deposit.data_att_url);c=$m.attr.get(d,$m.t.string_deposit.data_att_dims);$m.attr.set(a,{"data-mjf_dr_type":"iframe","data-mjf_dr_iframe_src":$m.is.alive(b)?b:$m.t.string_deposit.config.url,"data-mjf_dr_iframe_dim":$m.is.alive(c)?c:$m.t.string_deposit.config.dims});
$m.t.darkroom.exec(a)}});$m.is.in_array($m.t.magic_editor.types[$m.trick.magic_editor.config.type],"string_deposit")===!1&&$m.t.magic_editor.types[$m.trick.magic_editor.config.type].push("string_deposit");for(var f=0,g=$m.tags.form.length;f<g;f++)for(var a=$m.attr.get_fields_with($m.tags.form[f],["text","textarea"],$m.data_att,this.data_att),e=0,h=a.length;e<h;e++)$m.attr.has_value(a[e],$m.data_att,"magic_editor")!==!0&&(b=$m.attr.get(a[e],this.data_att_url),c=$m.attr.get(a[e],this.data_att_dims),
d=$m.attr.get(a[e],this.data_att_has),$m.is.alive(d)===!1&&(d=a[e].id+"_link_"+$m.ut.rand_num(5),$m.tag.insert_after(a[e],$m.tag.init("a",{"data-mjf":"set_strdep|darkroom|return_false","data-mjf_dr_type":"iframe","data-mjf_dr_iframe_src":$m.is.alive(b)?b:this.config.url,"data-mjf_dr_iframe_dim":$m.is.alive(c)?c:this.config.dims,"data-mjf_strdep_parent":a[e].id,href:"#","class":"strdep_icon",title:this.config.title,id:d})),$m.tag.create(d,"img",{src:$m.config.basedir+"tricks/string_deposit/icon_string_deposit.png",
alt:""}),$m.attr.set(a[e],{"data-mjf_strdep_has":"true"})));$m.elements.bind($m.tags.a,this.data_att_set,"click",this.set);$m.t.darkroom.init()},set:function(a){$m.t.string_deposit.cur.input=$m.attr.get(a,$m.t.string_deposit.data_att_parent);$m.t.string_deposit.cur.cursor=$m.cursor.get($m.t.string_deposit.cur.input);$m.t.string_deposit.cur.action=$m.attr.has_value($m.t.string_deposit.cur.input,$m.t.string_deposit.data_att_action,"overwrite")===!0?"overwrite":"insert";if($m.is.alive($m.trick.magic_editor)===
!0)$m.t.magic_editor.cur_ed=!1},write:function(){var a="",b="",a="",c;for(c in $m.t.string_deposit.cur.deposits){var a=$m.t.string_deposit.cur.deposit_template,d;for(d in $m.t.string_deposit.cur.deposits[c])a=a.replace(d,$m.t.string_deposit.cur.deposits[c][d]),a=a.replace(/string_deposit="(.+?)"/,"onclick=\"parent.$m.t.string_deposit.exec('$1');return false;\"");b+=a}switch($m.t.string_deposit.cur.deposit_action){case "append":a=$m.t.string_deposit.cur.deposit_id.innerHTML+b;break;case "prepend":a=
b+$m.t.string_deposit.cur.deposit_id.innerHTML;break;default:a=b}if($m.tag.get_name($m.t.string_deposit.cur.deposit_id)=="table"&&$m.vd.is_msie===!0){b="<table";d=$m.attr.get_all($m.t.string_deposit.cur.deposit_id);var f=$m.tag.init("div",!1,$m.tag.get_iframe_doc($m.t.darkroom.ids.iframe_div_iframe));for(c in d)b+=" "+c+'="'+d[c]+'"';f.innerHTML=b+">"+a+"</table>";$m.tag.replace($m.t.string_deposit.cur.deposit_id,f)}else $m.t.string_deposit.cur.deposit_id.innerHTML=a},exec:function(a){$m.is.alive(a)===
!1&&(a="");if($m.is.alive($m.trick.magic_editor)===!0&&$m.is.alive($m.t.magic_editor.cur_ed)===!0)$m.t.magic_editor.selection.save("magic_"+$m.t.magic_editor.cur_ed),$m.t.magic_editor.inject_html(a,"inline");else{var b=$m.id($m.t.string_deposit.cur.input),c="";$m.t.string_deposit.cur.action=="overwrite"?b.value=a:(c=b.value.substr(0,$m.t.string_deposit.cur.cursor)+a+b.value.substr($m.t.string_deposit.cur.cursor,b.value.length),b.value=c,$m.t.string_deposit.cur.cursor=b.value.length);$m.cursor.set($m.t.string_deposit.cur.input,
$m.t.string_deposit.cur.cursor)}$m.t.darkroom.hide("mjf_darkroom_iframe_div");return!1}};
