/***************************************************************************
- File: magic_calendar.js
- Version: 14.6.3
***************************************************************************/

$m.trick.magic_calendar={};
$m.t.magic_calendar={name:"magic_calendar",data_att:"magic_calendar",data_att_has:"data-mjf_mcal_has",data_att_parent:"data-mjf_mcal_parent",data_att_dformat:"data-mjf_mcal_date_format",data_att_tformat:"data-mjf_mcal_time_format",iframe_id:"",cur:{input:"",format:"",year:0,month:0,day:0,hour:0,minute:0,second:0,ampm:""},ori:{year:"",month:"",day:"",hour:"",minute:"",second:"",ampm:""},format:{date:["MM-dd-yyyy","MM/dd/yyyy","yyyy-MM-dd","yyyy/MM/dd","MMM dd, yyyy","MMMM dd, yyyy"],time:["H:mm:ss ampm",
"H:mm ampm"]},uses_time:!1,uses_time_seconds:!1,final_height:0,increments:25,construct:function(){$m.dt.get_date_now();if($m.is.alive(this.earliest_year)===!1)this.earliest_year=$m.dt.current_year-100;if($m.is.alive(this.furthest_year)===!1)this.furthest_year=$m.dt.current_year+50;var d={};has_calendar=!1;for(var c=0,a=$m.tags.form.length;c<a;c++)for(var d=$m.attr.get_fields_with($m.tags.form[c],["text"],$m.data_att,this.data_att),e=0,b=d.length;e<b;e++)if(has_calendar=$m.attr.get(d[e],this.data_att_has),
$m.is.alive(has_calendar)===!1){var f=d[e].id+"_link_"+$m.ut.rand_num(5);$m.tag.insert_after(d[e],$m.tag.init("a",{"data-mjf":"magic_calendar|return_false","data-mjf_mcal_parent":d[e].id,href:"#","class":"mcal_icon",id:f}));$m.tag.create(f,"img",{src:$m.config.basedir+"images/icons/icon_calendar.png",alt:""});$m.attr.set(d[e],{"data-mjf_mcal_has":"true"})}if($m.ajax_init===!1){this.iframe_id="magic_cal"+$m.ut.rand_num(5);d=$m.tag.init("iframe",{id:this.iframe_id,name:this.iframe_id,src:$m.config.basedir+
"tricks/magic_calendar/mcal.html","class":"mcal_iframe",frameborder:"0",scrolling:"no"});d.style.cssText=$m.vd.is_msie7_or_lower===!0?"overflow:hidden;":"";d.style.cssText+="height:260px;left:0;top:0;visibility:hidden;";$m.id($m.body_id).appendChild(d);d=$m.id(this.iframe_id);if($m.vd.is_msie7_or_lower===!0)d.style.height="300px",d.style.width="350px";this.final_height=parseInt($m.id(d).style.height)}$m.dt.get_date_now();$m.elements.bind($m.tags.a,this.data_att,"click",this.exec);$m.element.attach($m.body_id,
"mousedown",$m.t.magic_calendar.hide);$m.element.attach($m.body_id,"keydown",$m.t.magic_calendar.hide);$m.element.attach($m.body_id,"keydown",$m.t.magic_calendar.hide);$m.element.attach($m.body_id,"touchstart",$m.t.magic_calendar.hide)},exec:function(d){$m.t.magic_calendar.cur.input=$m.attr.get(d,$m.t.magic_calendar.data_att_parent);$m.t.magic_calendar.cur.dformat=$m.attr.get($m.t.magic_calendar.cur.input,$m.t.magic_calendar.data_att_dformat);$m.t.magic_calendar.cur.tformat=$m.attr.get($m.t.magic_calendar.cur.input,
$m.t.magic_calendar.data_att_tformat);$m.t.magic_calendar.reset();if($m.t.magic_calendar.parse_date()==!1)return!1;$m.t.magic_calendar.write();var c=$m.id($m.t.magic_calendar.iframe_id),d=$m.position.get_xy(d),a=d[0]+22,e=d[1]-20;$m.vd.get_view_port();c.style.top=e+$m.t.magic_calendar.final_height<=$m.vd.scrolled_top+$m.vd.visible_page_height?e+"px":d[1]-$m.t.magic_calendar.final_height+30+"px";c.style.left=$m.vd.visible_page_width-a<325?a-385+"px":a+"px";$m.vd.is_mobile_touch===!0?c.style.visibility=
"visible":(c.style.opacity=0,c.style.visibility="visible",$m.animate.opaque(c,"up",$m.t.magic_calendar.increments));$m.css_class.add($m.t.magic_calendar.cur.input,"mcal_field_on");$m.tag.get_iframe_doc($m.t.magic_calendar.iframe_id).getElementById("mcal_date_picked").focus()},reset:function(){$m.t.magic_calendar.cur.year=0;$m.t.magic_calendar.cur.month=0;$m.t.magic_calendar.cur.day=0;$m.t.magic_calendar.cur.hour=0;$m.t.magic_calendar.cur.minute=0;$m.t.magic_calendar.cur.second=0;$m.t.magic_calendar.cur.ampm=
""},hide:function(){var d=$m.id($m.t.magic_calendar.iframe_id);d.style.visibility="hidden";d.style.top="-1000px";d.style.left="-1000px";$m.css_class.remove($m.t.magic_calendar.cur.input,"mcal_field_on")},parse_date:function(){var d=$m.id($m.t.magic_calendar.cur.input).value,c=$m.is.in_array($m.t.magic_calendar.format.date,$m.t.magic_calendar.cur.dformat),a="",a=!1,e={year:$m.dt.current_year,month:$m.dt.obj_date.getMonth(),day:$m.dt.obj_date.getDate(),hour:$m.dt.obj_date.getHours(),minute:$m.dt.obj_date.getMinutes(),
second:$m.dt.obj_date.getSeconds()},b="",b=b=b="";ampm_str=e.hour>11?"pm":"am";if($m.is.alive(d)===!1){if($m.is.alive($m.t.magic_calendar.cur.tformat)===!0&&($m.t.magic_calendar.uses_time=!0,$m.t.magic_calendar.cur.tformat.length==12))$m.t.magic_calendar.uses_time_seconds=!0}else{$m.is.alive($m.t.magic_calendar.cur.tformat)===!0&&(a=$m.is.in_array($m.t.magic_calendar.format.time,$m.t.magic_calendar.cur.tformat));if(a===!1){if($m.t.magic_calendar.uses_time=!1,$m.t.magic_calendar.uses_time_seconds=
!1,c===!1)return!1}else{$m.t.magic_calendar.uses_time=!0;b=d.split(" ");ampm_str=b[b.length-1];b=b[b.length-2];if($m.is.alive(b)===!0&&(b=b.split(":"),$m.is.alive(b)===!0&&(ampm_str=="pm"&&(b[0]=parseInt(b[0])+12),b[0]==24&&(b[0]=12),e.hour=b[0],e.minute=b[1],$m.is.alive(b[2])===!0)))e.second=b[2],$m.t.magic_calendar.uses_time_seconds=!0;if(a==0)$m.t.magic_calendar.uses_time_seconds=!0}switch(c){case 0:b=d.split("-");e.year=a!==!1?b[2].split(" ")[0]:b[2];e.month=b[0]-1;e.day=b[1];break;case 1:b=d.split("/");
e.year=a!==!1?b[2].split(" ")[0]:b[2];e.month=b[0]-1;e.day=b[1];break;case 2:b=d.split("-");e.year=b[0];e.month=b[1]-1;e.day=a!==!1?b[2].split(" ")[0]:b[2];break;case 3:b=d.split("/");e.year=b[0];e.month=b[1]-1;e.day=a!==!1?b[2].split(" ")[0]:b[2];break;case 4:d=d.replace(",","");b=d.split(" ");e.year=a!==!1?b[2].split(" ")[0]:b[2];e.month=$m.is.in_array($m.dt.month_names_short,b[0]);e.day=b[1];break;case 5:d=d.replace(",",""),b=d.split(" "),e.year=a!==!1?b[2].split(" ")[0]:b[2],e.month=$m.is.in_array($m.dt.month_names,
b[0]),e.day=b[1]}}a=new Date(e.year,e.month,e.day,e.hour,e.minute,e.second);isNaN(a.getYear())===!0?($m.t.magic_calendar.cur.year=$m.dt.current_year,$m.t.magic_calendar.cur.month=$m.dt.obj_date.getMonth(),$m.t.magic_calendar.cur.day=$m.dt.obj_date.getDate(),$m.t.magic_calendar.cur.hour=$m.dt.obj_date.getHours(),$m.t.magic_calendar.cur.minute=$m.dt.obj_date.getMinutes(),$m.t.magic_calendar.cur.second=$m.dt.obj_date.getSeconds()):($m.t.magic_calendar.cur.year=a.getFullYear(),$m.t.magic_calendar.cur.month=
a.getMonth(),$m.t.magic_calendar.cur.day=a.getDate(),$m.t.magic_calendar.cur.hour=a.getHours(),$m.t.magic_calendar.cur.minute=a.getMinutes(),$m.t.magic_calendar.cur.second=a.getSeconds());$m.t.magic_calendar.cur.ampm=ampm_str;$m.t.magic_calendar.ori.ampm=ampm_str;$m.t.magic_calendar.ori.year=$m.t.magic_calendar.cur.year;$m.t.magic_calendar.ori.month=$m.t.magic_calendar.cur.month;$m.t.magic_calendar.ori.day=$m.t.magic_calendar.cur.day;$m.t.magic_calendar.ori.hour=$m.t.magic_calendar.cur.hour;$m.t.magic_calendar.ori.minute=
$m.t.magic_calendar.cur.minute;$m.t.magic_calendar.ori.second=$m.t.magic_calendar.cur.second},set:function(){var d=$m.is.in_array($m.t.magic_calendar.format.date,$m.t.magic_calendar.cur.dformat),c=parseInt($m.t.magic_calendar.cur.month),a=parseInt($m.t.magic_calendar.cur.day),e=c<9?"0"+(c+1):c+1,b=a<10?"0"+a:a,c=a="";switch(d){case 0:a=e+"-"+b+"-"+$m.t.magic_calendar.cur.year;break;case 1:a=e+"/"+b+"/"+$m.t.magic_calendar.cur.year;break;case 2:a=$m.t.magic_calendar.cur.year+"-"+e+"-"+b;break;case 3:a=
$m.t.magic_calendar.cur.year+"/"+e+"/"+b;break;case 4:if($m.t.magic_calendar.cur.day.length==1)$m.t.magic_calendar.cur.day="0"+$m.t.magic_calendar.cur.day;a=$m.dt.month_names_short[$m.t.magic_calendar.cur.month]+" "+$m.t.magic_calendar.cur.day+", "+$m.t.magic_calendar.cur.year;break;case 5:a=$m.dt.month_names[$m.t.magic_calendar.cur.month]+" "+b+", "+$m.t.magic_calendar.cur.year}$m.is.alive($m.t.magic_calendar.cur.tformat)===!0&&(d=$m.is.in_array($m.t.magic_calendar.format.time,$m.t.magic_calendar.cur.tformat),
e=b=e="",e=$m.t.magic_calendar.cur.hour>12?$m.t.magic_calendar.cur.hour-12:$m.t.magic_calendar.cur.hour,b=$m.t.magic_calendar.cur.minute<10?"0"+$m.t.magic_calendar.cur.minute:$m.t.magic_calendar.cur.minute,c+=" "+e+":"+b,d==0&&(e=$m.t.magic_calendar.cur.second<10?"0"+$m.t.magic_calendar.cur.second:$m.t.magic_calendar.cur.second,c+=":"+e),c+=" "+$m.t.magic_calendar.cur.ampm);$m.id($m.t.magic_calendar.cur.input).value=a+c;$m.vd.is_mobile_touch===!1&&$m.cursor.set($m.t.magic_calendar.cur.input,"end");
$m.t.magic_calendar.hide()},pick:function(d,c){var a=c.id;$m.t.magic_calendar.cur[d]=c.value;$m.t.magic_calendar.write();a!==!1&&$m.tag.get_iframe_doc($m.t.magic_calendar.iframe_id).getElementById(a).focus()},go:function(d,c){var a=c.id;$m.t.magic_calendar.cur.month=d=="prev"?$m.t.magic_calendar.cur.month-1:$m.t.magic_calendar.cur.month+1;if($m.t.magic_calendar.cur.month<0)$m.t.magic_calendar.cur.month=11,$m.t.magic_calendar.cur.year--;if($m.t.magic_calendar.cur.month>11)$m.t.magic_calendar.cur.month=
0,$m.t.magic_calendar.cur.year++;$m.t.magic_calendar.write();a!==!1&&$m.tag.get_iframe_doc($m.t.magic_calendar.iframe_id).getElementById(a).focus()},update:function(d,c){$m.t.magic_calendar.pick(d,{id:!1,value:c});$m.t.magic_calendar.set()},today:function(){var d={id:!1,value:$m.dt.current_year};$m.t.magic_calendar.pick("year",d);d.value=$m.dt.obj_date.getMonth();$m.t.magic_calendar.pick("month",d);d.value=$m.dt.obj_date.getDate();$m.t.magic_calendar.pick("day",d);$m.t.magic_calendar.write();(d=$m.tag.get_iframe_doc($m.t.magic_calendar.iframe_id).getElementById("mcal_date_current"))&&
d.focus()},write:function(){var d=$m.tag.get_iframe_doc($m.t.magic_calendar.iframe_id).getElementById("mcal_cont"),c="",a=0,e="",b="",f=e="",i="",g="",g="";c+='<table cellpadding="0" cellspacing="0" border="0" class="mcal_table"><tr><th colspan="7">';c+='<a href="#" onclick="parent.$m.t.magic_calendar.go(\'prev\', this);return false;" tabIndex="1" title="Previous Month" id="mcal_pmonth_picker"><img src="'+$m.config.basedir+'images/icons/icon_arrow_left.png" alt=""></a> ';c+='<select name="mcal_month" class="mcal_select" onchange="parent.$m.t.magic_calendar.pick(\'month\', this);" onkeyup="parent.$m.t.magic_calendar.pick(\'month\', this);" tabIndex="2" id="mcal_month_picker"> ';
for(a=0;a<12;a++)g=a==$m.t.magic_calendar.cur.month?'selected="selected"':"",c+='<option value="'+a+'" '+g+">"+$m.dt.month_names[a]+"</option>";c+='</select><input type="hidden" name="mcal_day" value="';for(a=1;a<32;a++)a==$m.t.magic_calendar.cur.day&&(c+=a);c+='"> <select name="mcal_year" class="mcal_select" onchange="parent.$m.t.magic_calendar.pick(\'year\', this);" onkeyup="parent.$m.t.magic_calendar.pick(\'year\', this);" tabIndex="3" id="mcal_year_picker">';for(a=$m.t.magic_calendar.earliest_year;a<
$m.t.magic_calendar.furthest_year;a++)g=a==$m.t.magic_calendar.cur.year?'selected="selected"':"",c+='<option value="'+a+'" '+g+">"+a+"</option>";c+='</select> <a href="#" onclick="parent.$m.t.magic_calendar.go(\'next\', this);return false;" tabIndex="4" title="Next Month" id="mcal_nmonth_picker"><img src="'+$m.config.basedir+'images/icons/icon_arrow_right.png" alt=""></a></td></tr>';b=(new Date($m.t.magic_calendar.cur.year,$m.t.magic_calendar.cur.month,1)).getDay();if($m.t.magic_calendar.cur.year%
4==0&&$m.t.magic_calendar.cur.year%100!=0||$m.t.magic_calendar.cur.year%400==0)$m.dt.month_days[1]=29;c+='<tr class="mcal_subhead">';for(a=0;a<7;a++)c+="<td>"+$m.dt.weekdays[a]+"</td>";c+="</tr><tr>";var h=0,f=$m.t.magic_calendar.cur.month-1,g=5;f==-1&&(f=11);for(a=0;a<b;a++)e=$m.dt.month_days[f]-b+a+1,c+='<td class="mcal_other_month">'+e+"</td>",h++;for(a=1;a<=$m.dt.month_days[$m.t.magic_calendar.cur.month];a++)e="0"+a,b=parseInt($m.t.magic_calendar.cur.month)+1,i=f="",e==$m.dt.current_date&&b==
$m.dt.current_month&&$m.t.magic_calendar.cur.year==$m.dt.current_year&&(f+=" mcal_date_cur",i='id="mcal_date_current"'),a==$m.t.magic_calendar.ori.day&&$m.t.magic_calendar.cur.month==$m.t.magic_calendar.ori.month&&$m.t.magic_calendar.cur.year==$m.t.magic_calendar.ori.year&&(f+=" mcal_date_sel",i='id="mcal_date_picked"'),c+='<td class="mcal_date'+f+'"><strong><a href="#" onclick="parent.$m.t.magic_calendar.update(\'day\', \''+a+'\');return false;" tabIndex="'+g+'" '+i+">"+a+"</a></strong></td>",h++,
g++,h==7&&(c+="</tr><tr>",h=0);if(h>0)for(a=1;h<7;a++)c+='<td class="mcal_other_month">'+a+"</td>",h++;g++;c+='</tr><tr><td class="mcal_subhead" colspan="7"><a href="#" onclick="parent.$m.t.magic_calendar.today(this);return false;" tabIndex="'+g+'" title="Go to Today" id="mcal_today_picker"><img src="'+$m.config.basedir+'images/icons/icon_calendar_today.png" alt=""></a> ';g++;if($m.t.magic_calendar.uses_time===!0){e=h=f=b=f=b=f=b="";c+='<select name="mcal_hour" class="mcal_select" onchange="parent.$m.t.magic_calendar.pick(\'hour\', this);" tabIndex="'+
g+'" id="mcal_hour_picker">';g++;b=$m.t.magic_calendar.cur.hour>12?$m.t.magic_calendar.cur.hour-12:$m.t.magic_calendar.cur.hour;for(a=1;a<13;a++)f=a==b?'selected="selected"':"",c+='<option value="'+a+'" '+f+">"+a+"</option>";c+='</select> : <select name="mcal_minute" class="mcal_select" onchange="parent.$m.t.magic_calendar.pick(\'minute\', this);" tabIndex="'+g+'" id="mcal_minute_picker">';g++;for(a=0;a<61;a++)b=a==$m.t.magic_calendar.cur.minute?'selected="selected"':"",f=a<10?"0"+a:a,c+='<option value="'+
a+'" '+b+">"+f+"</option>";c+="</select> ";if($m.t.magic_calendar.uses_time_seconds===!0){c+=' : <select name="mcal_second" class="mcal_select" onchange="parent.$m.t.magic_calendar.pick(\'second\', this);" tabIndex="'+g+'" id="mcal_second_picker">';g++;for(a=0;a<61;a++)b=a==$m.t.magic_calendar.cur.second?'selected="selected"':"",f=a<10?"0"+a:a,c+='<option value="'+a+'" '+b+">"+f+"</option>";c+="</select> "}c+='<select name="mcal_ampm" class="mcal_select" onchange="parent.$m.t.magic_calendar.pick(\'ampm\', this);" tabIndex="'+
g+'" id="mcal_ampm_picker">';g++;$m.t.magic_calendar.cur.ampm=="am"&&(h='selected="selected"');$m.t.magic_calendar.cur.ampm=="pm"&&(e='selected="selected"');c+='<option value="am" '+h+">am</option>";c+='<option value="pm" '+e+">pm</option>";c+="</select> "}c+='<a href="#" onclick="parent.$m.t.magic_calendar.set();return false;" title="Update form field"><img src="'+$m.config.basedir+'images/icons/icon_calendar_done.png" alt="" tabIndex="'+g+'"></a></td></tr></table>';d.innerHTML=c.replace("<tr></tr>",
"")}};
