/***************************************************************************
- File: darkroom.js
- Version: 13.5.28
***************************************************************************/

$m.trick.darkroom={};
$m.t.darkroom={name:"darkroom",data_att:"darkroom",data_att_content:"data-mjf_dr_id",data_att_xy:"data-mjf_dr_xy",data_att_overlay:"data-mjf_dr_overlay",data_att_form:"data-mjf_dr_form",data_att_type:"data-mjf_dr_type",data_att_iframe_src:"data-mjf_dr_iframe_src",data_att_iframe_dim:"data-mjf_dr_iframe_dim",data_att_dim:"data-mjf_dr_dim",data_att_cancel:"dr_cancel",dr_contents:[],dr_forms:[],css:{all:"mjf_darkroom_content",current:"mjf_darkroom_content_current",close_img:"mjf_darkroom_close_img"},ids:{overlay:"mjf_darkroom_overlay",
iframe_div:"mjf_darkroom_iframe_div",iframe_div_iframe:"mjf_darkroom_iframe",img_only_p:"mjf_darkroom_img_only_p",img_only_cache:"mjf_darkroom_img_only_cache",img_only_cache_id:!1,img_only_img:"mjf_darkroom_img_only",img_only_title:"mjf_darkroom_img_only_title"},buffer:20,buffer_top:10,is:{image:!1,iframe:!1},construct:function(){$m.is.alive($m.lang.darkroom)===!1&&$m.ajax_init===!1?$m.insert_link.script($m.config.basedir+"tricks/darkroom/lang/"+$m.config.lang+".js",function(){$m.t.darkroom.init()}):
$m.t.darkroom.init()},init:function(){for(var a=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),b=$m.id($m.body_id),d=!1,c=!1,g=0,f=a.length;g<f;g++){var e=$m.attr.get(a[g],this.data_att_content),h=$m.id(e),i=$m.attr.get(a[g],this.data_att_type),j=$m.vd.is_msie8_or_lower===!0?this.css.all+" mjf_darkroom_content_noshadow":this.css.all;if($m.is.alive(i)===!0)switch(i){case "image":d=!0;this.dr_contents.push(this.ids.img_only_p);this.create_img_cache();$m.t.darkroom.ids.img_only_cache_id.innerHTML+=
'<img src="'+$m.attr.get(a[g],"href")+'" alt="">';break;case "iframe":c=!0,this.dr_contents.push(this.ids.iframe_div)}else $m.is.in_array(this.dr_contents,e)===!1&&(this.dr_contents.push(e),this.insert_cancel_img(e),$m.vd.is_msie8_or_lower===!0&&$m.css_class.add(e,"mjf_darkroom_content_noshadow"),$m.css_class.add(e,"visibility_hidden"),$m.css_class.remove(e,"display_none"),$m.attr.set(e,{"data-mjf_dr_width":h.offsetWidth+20,"data-mjf_dr_height":h.offsetHeight+10,"data-mjf":"drag_n_drop_free"}),$m.css_class.add(e,
this.css.all),$m.css_class.remove(e,"visibility_hidden"));e=$m.attr.get(a[g],this.data_att_form);$m.is.alive(e)===!0&&$m.is.in_array(this.dr_forms,e)===!1&&this.dr_forms.push(e)}$m.id(this.ids.overlay)===!1&&(g=$m.tag.init("div",{id:this.ids.overlay}),$m.vd.is_msie6_or_lower===!0&&(g.style.cssText+="filter: alpha(opacity = 85);"),b.appendChild(g),$m.win.bind("resize",function(){$m.t.darkroom.resize_overlay()}));d===!0&&$m.id(this.ids.img_only_p)===!1&&($m.tag.create($m.body_id,"p",{"data-mjf":"drag_n_drop_free",
"class":j,id:this.ids.img_only_p}),$m.tag.create(this.ids.img_only_p,"img",{alt:"",id:this.ids.img_only_img}),$m.tag.create(this.ids.img_only_p,"br"),$m.tag.create(this.ids.img_only_p,"span",{id:this.ids.img_only_title}),this.insert_cancel_img(this.ids.img_only_p));c===!0&&$m.id(this.ids.iframe_div)===!1&&($m.tag.create($m.body_id,"div",{"data-mjf":"drag_n_drop_free","class":j,id:this.ids.iframe_div}),$m.tag.create(this.ids.iframe_div,"iframe",{frameBorder:0,border:0,src:"about:blank",id:this.ids.iframe_div_iframe}),
this.insert_cancel_img(this.ids.iframe_div),$m.is.alive($m.t.drag_n_drop)===!0&&($m.element.attach(this.ids.iframe_div_iframe,"dragover",$m.t.drag_n_drop.free.drag_over),$m.element.attach(this.ids.iframe_div_iframe,"drop",$m.t.drag_n_drop.free.drag_drop),$m.element.attach(this.ids.iframe_div_iframe,"load",$m.t.darkroom.iframe_events)));$m.elements.bind(a,this.data_att,"click",this.exec);$m.elements.bind($m.tags.img,this.data_att_cancel,"mousedown",this.hide);$m.shortcut.bind("esc",function(){$m.t.darkroom.hide_all()});
$m.is.alive($m.t.drag_n_drop)===!0&&$m.t.drag_n_drop.free.construct()},iframe_events:function(){$m.css_class.remove($m.t.darkroom.ids.iframe_div_iframe,"mjf_darkroom_iframe_loading");var a=$m.tag.get_iframe_doc($m.t.darkroom.ids.iframe_div_iframe);if($m.is.alive(a)===!0&&(a=$m.tag.get_body(a),$m.element.attach(a,"dragover",$m.t.drag_n_drop.free.drag_over),$m.element.attach(a,"drop",$m.t.drag_n_drop.free.drag_drop_frame),$m.shortcut.bind("esc",function(){parent.$m.t.darkroom.hide_all()},{target:a}),
$m.vd.is_mobile_touch===!0))$m.id($m.t.darkroom.ids.iframe_div).style.height=a.offsetHeight+50+"px",$m.attr.set($m.t.darkroom.ids.iframe_div_iframe,{height:a.offsetHeight})},exec:function(a){var b=$m.id(a),d=$m.attr.get(a,$m.t.darkroom.data_att_content),c=$m.id(d),g=$m.attr.get(a,$m.t.darkroom.data_att_xy),f="",e=$m.attr.get(a,$m.t.darkroom.data_att_type);if($m.tag.get_name(a)=="a"){var f=$m.attr.get(a,"href"),h=$m.attr.get(a,"data-mjf_ga_track");$m.is.alive(f)===!0&&h===null&&$m.track.ga({category:"MJF Darkroom",
action:a+" Click",label:d});b.blur()}$m.vd.get_view_port();if($m.attr.has_value(b,$m.t.darkroom.data_att_overlay,"true")===!0)f=$m.id($m.t.darkroom.ids.overlay),f.style.height=$m.vd.total_page_height+"px",f.style.width=$m.vd.total_page_width+"px",f.style.display="block";if($m.is.alive(e)===!0)switch(h=0,e){case "image":f=$m.attr.get(a,"href");c=$m.id($m.t.darkroom.ids.img_only_p);e=$m.id($m.t.darkroom.ids.img_only_img);b=$m.attr.get(a,"title");d=new Image;$m.t.darkroom.is.image=!0;d.src=f;$m.css_class.add(c,
"dr_visibility_hidden");$m.css_class.add(c,$m.t.darkroom.css.current);e.src=d.src;$m.id($m.t.darkroom.ids.img_only_title).innerHTML=$m.is.alive(b)===!0?b:"";c.style.height="auto";$m.t.darkroom.set_xy(c,d.width,c.offsetHeight);break;case "iframe":$m.attr.set($m.t.darkroom.ids.iframe_div_iframe,{src:"about:blank"});$m.t.darkroom.is.iframe=!0;var c=$m.id($m.t.darkroom.ids.iframe_div),h=$m.attr.get(a,$m.t.darkroom.data_att_dim),i=$m.attr.get(a,$m.t.darkroom.data_att_iframe_dim),f=$m.vd.is_msie===!0?5:
10,e=$m.id($m.t.darkroom.ids.iframe_div_iframe),d=b=0;$m.css_class.add($m.t.darkroom.ids.iframe_div_iframe,"mjf_darkroom_iframe_loading");$m.css_class.add(c,"dr_visibility_hidden");$m.css_class.add(c,$m.t.darkroom.css.current);$m.is.alive(i)===!0&&(h=i);h.match("x")?(iframe_dims=h.split("x"),b=parseInt(iframe_dims[0]),d=parseInt(iframe_dims[1]),$m.t.darkroom.set_xy(c,b+f,d+20),h=parseInt(c.style.width),b>h&&(b=h-f)):(d=$m.vd.visible_page_height-60,c.style.height=d+"px",$m.t.darkroom.set_xy(c,$m.vd.total_page_width,
d),b=parseInt(c.style.width)-f,d=parseInt(d)-20);$m.attr.set(e,{src:$m.attr.get(a,$m.t.darkroom.data_att_iframe_src),width:b,height:d})}else $m.css_class.add(c,"dr_visibility_hidden"),$m.css_class.add(c,$m.t.darkroom.css.current),e=$m.attr.get(a,$m.t.darkroom.data_att_dim),b="",f=$m.vd.is_msie===!0?5:10,$m.is.alive(e)===!0?e.match("x")?(cont_dims=e.split("x"),b=parseInt(cont_dims[0]),cont_new_height=parseInt(cont_dims[1]),c.style.overflow="auto",$m.t.darkroom.set_xy(c,b+f,cont_new_height+20)):(d=
$m.vd.visible_page_height-60,c.style.height=d+"px",$m.t.darkroom.set_xy(c,$m.vd.total_page_width,d)):$m.t.darkroom.set_xy(c,$m.attr.get(c,"data-mjf_dr_width"),$m.attr.get(c,"data-mjf_dr_height"));$m.css_class.remove(c,"dr_visibility_hidden");if($m.is.alive(g)===!0)a=$m.position.get_xy(a),f=g.split("x"),g=f[0].match("-")?a[0]-parseInt(f[0].replace("-","")):a[0]+parseInt(f[0]),a=f[1].match("-")?a[1]-parseInt(f[1].replace("-","")):a[1]+parseInt(f[1]),c.style.left=g+"px",c.style.top=a+"px";$m.t.darkroom.is.image=
!1;$m.t.darkroom.is.iframe=!1},resize_overlay:function(){var a=$m.id($m.t.darkroom.ids.overlay);if(a.style.display=="block")a.style.display="none",$m.vd.get_view_port(),a.style.height=$m.vd.total_page_height+"px",a.style.width=$m.vd.total_page_width+"px",a.style.display="block"},set_xy:function(a,b,d){b=parseInt(b);$m.vd.total_page_width>=b+$m.t.darkroom.buffer?(a.style.left=parseInt($m.vd.total_page_width/2)-parseInt(b/2)-10+"px",a.style.width=b+"px"):(a.style.left=$m.t.darkroom.buffer+"px",a.style.width=
$m.vd.total_page_width-$m.t.darkroom.buffer*2-10+"px");d=parseInt(d);b=0;$m.vd.visible_page_height>=d+$m.t.darkroom.buffer_top?(b=parseInt($m.vd.visible_page_height/2)-parseInt(d/2)+$m.vd.scrolled_top,b<10&&(b=20),a.style.height=d+10+"px"):(b=$m.t.darkroom.buffer_top+$m.vd.scrolled_top,a.style.height=d+($m.t.darkroom.is.image===!0?30:10)+"px");a.style.top=b+"px"},create_img_cache:function(){if($m.id($m.t.darkroom.ids.img_only_cache)===!1)$m.tag.create($m.body_id,"p",{id:$m.t.darkroom.ids.img_only_cache}),
$m.t.darkroom.ids.img_only_cache_id=$m.id($m.t.darkroom.ids.img_only_cache)},insert_cancel_img:function(a){var b=$m.id(a);if($m.is.alive(b)===!1)return!1;if($m.is.alive($m.lang.darkroom)===!1)$m.lang.darkroom={close:"Close"};$m.tag.create(b,"span",{"data-mjf":"drag_n_drop_handle","class":"mjf_darkroom_handle",id:a+".handle"},null,"first");$m.tag.create(b,"img",{src:$m.config.basedir+"images/icons/icon_close_16x16.png",alt:$m.lang.darkroom.close,title:$m.lang.darkroom.close,height:"16",width:"16",
"data-mjf":$m.t.darkroom.data_att_cancel,"class":$m.t.darkroom.css.close_img,id:a+".close_img"},null,"first")},hide:function(a){if($m.is.alive(a)===!1)return!1;var b=a.split(".")[0];dr_id_obj=$m.id(b);dr_id_obj.style.top=parseInt(dr_id_obj.style.top)+75+"px";dr_id_obj.style.opacity=0.5;setTimeout(function(){$m.css_class.remove(b,$m.t.darkroom.css.current);dr_id_obj.style.opacity=1},250);$m.id($m.t.darkroom.ids.overlay).style.display="none"},hide_all:function(){for(var a=0,b=$m.t.darkroom.dr_contents.length;a<
b;a++)$m.css_class.remove($m.t.darkroom.dr_contents[a],$m.t.darkroom.css.current);$m.id($m.t.darkroom.ids.overlay).style.display="none"}};
