/***************************************************************************
- File: ajax_lookup.js
- Version: 11.4.29
***************************************************************************/

$m.trick.ajax_lookup={};
$m.t.ajax_lookup={name:"ajax_lookup",construct:function(){$m.ajax_init===false&&$m.insert_link.stylesheet($m.config.basedir+"tricks/ajax_lookup.css")},ajax_suggest:{name:"ajax_suggest",data_att:"ajax_suggest",timer:"",filter_speed:750,update_id:"",is_good_lookup_keycode:function(a){return a>=48&&a<=90?true:a>=96&&a<=105?true:a==8||a==46?true:false},construct:function(){var a=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att);$m.elements.bind(a,this.data_att,"keyup",this.search);$m.elements.bind(a,
this.data_att,"blur",this.decide)},search:function(a,b){clearTimeout($m.t.ajax_lookup.ajax_suggest.timer);var c=$m.get_keycode(b);if(c=="40"){c=$m.id($m.attr.get(a,"data-mjf_suggest_id"));if(c!==false){c.focus();c.selectedIndex=0}}else if($m.t.ajax_lookup.ajax_suggest.is_good_lookup_keycode(c)===true)$m.t.ajax_lookup.ajax_suggest.timer=setTimeout(function(){$m.t.ajax_lookup.ajax_suggest.filter(a,b)},$m.t.ajax_lookup.ajax_suggest.filter_speed);else if(c=="27"){c=$m.id(a);$m.id(c.getAttribute("data-mjf_ajax_update_id")).style.display=
"none"}},filter:function(a){var b=$m.id(a),c=$m.ajax.init_settings(b);c.query+="&"+b.name+"="+b.value+"&eparent="+a+"&eid="+c.update_id;c.callback_success="$m.t.ajax_lookup.ajax_suggest.update('"+a+"')";$m.ajax.request.element_id=a;$m.ajax.send(c)},update:function(a){$m.ajax.simple_content_update();a=$m.id(a);$m.id(a.getAttribute("data-mjf_ajax_update_id")).style.display="block"},decide:function(a,b){b=$m.get_keycode(b);if(b=="9"||b=="27")$m.t.ajax_lookup.ajax_suggest.hide(a);b!="40"&&$m.returnd.set(a,
"blur","true")},hide:function(a){a=$m.id(a);a=$m.id(a.getAttribute("data-mjf_ajax_update_id"));a.style.display="none"}},suggest_select:{name:"suggest_select",data_att:"suggest_select",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"blur",this.change);$m.elements.bind($m.tags.all,this.data_att,"change",this.change);$m.elements.bind($m.tags.all,this.data_att,"click",this.click);$m.elements.bind($m.tags.all,this.data_att,"keypress",this.keystroke)},change:function(a){var b=$m.id(a),
c=b.selectedIndex,d=b.options[c];c=d.value;d=d.text;b=$m.id(b.getAttribute("data-mjf_ss_parent"));b.value=d;b=$m.id(a+"_hidden");if(b!==false)$m.id(b+"_hidden").value=c;$m.returnd.set(a,"change","true");$m.returnd.set(a,"blur","true")},keystroke:function(a,b){b=$m.get_keycode(b);if(b=="13"||b=="27")$m.t.ajax_lookup.suggest_select.click(a)},click:function(a){a=$m.id(a);$m.id(a.getAttribute("data-mjf_ss_update")).style.display="none";$m.id(a.getAttribute("data-mjf_ss_parent")).focus()}}};
