/***************************************************************************
- File: image.js
- Version: 12.12.21
***************************************************************************/

var $me_image={img_html:!1,cur_img:!1,parent_anchor:!1,construct:function(){if(parent.$m.is.alive(parent.$m.t.magic_editor.selection.txt)===!1)parent.$m.t.magic_editor.selection.txt="";this.cur_img=parent.$m.t.magic_editor.cur_image;this.nimg_url_id=document.getElementById("img_url");this.nimg_title_id=document.getElementById("img_title");this.nimg_title_id.value=parent.$m.t.magic_editor.selection.txt;if(this.nimg_title_id.value=="false")this.nimg_title_id.value="";this.nimg_alt_id=document.getElementById("img_alt");
this.nimg_alt_id.value=parent.$m.t.magic_editor.selection.txt;if(this.nimg_alt_id.value=="false")this.nimg_alt_id.value="";this.nimg_margin_top_id=document.getElementById("img_margin_top");this.nimg_margin_right_id=document.getElementById("img_margin_right");this.nimg_margin_bottom_id=document.getElementById("img_margin_bottom");this.nimg_margin_left_id=document.getElementById("img_margin_left");this.nimg_float_none_id=document.getElementById("img_float_none");this.nimg_float_left_id=document.getElementById("img_float_left");
this.nimg_float_right_id=document.getElementById("img_float_right");this.nimg_border_id=document.getElementById("img_border");this.nimg_link_id=document.getElementById("img_link");this.nimg_link_target_id=document.getElementById("img_link_target");if(this.cur_img!==!1){document.getElementById("img_create").value="Update Image";var a=this.cur_img.getAttribute("src");if(parent.$m.is.alive(a)===!0)this.nimg_url_id.value=a;a=this.cur_img.getAttribute("title");if(parent.$m.is.alive(a)===!0)this.nimg_title_id.value=
a;a=this.cur_img.getAttribute("alt");if(parent.$m.is.alive(a)===!0)this.nimg_alt_id.value=a;a=parseInt(this.cur_img.style.marginTop);this.nimg_margin_top_id.value=isNaN(a)?"0":a;a=parseInt(this.cur_img.style.marginRight);this.nimg_margin_right_id.value=isNaN(a)?"0":a;a=parseInt(this.cur_img.style.marginBottom);this.nimg_margin_bottom_id.value=isNaN(a)?"0":a;a=parseInt(this.cur_img.style.marginLeft);this.nimg_margin_left_id.value=isNaN(a)?"0":a;var a=this.cur_img.style.cssFloat,b=this.cur_img.style.styleFloat;
if(parent.$m.is.alive(a)===!0||parent.$m.is.alive(b)===!0){if(a=="left"||b=="left")this.nimg_float_left_id.checked=!0;if(a=="right"||b=="right")this.nimg_float_right_id.checked=!0}a=this.cur_img.getAttribute("border");if(parent.$m.is.alive(a)===!0)this.nimg_border_id.value=a;this.parent_anchor=this.cur_img.parentNode;if(parent.$m.is.alive(this.parent_anchor)===!0)if(parent.$m.tag.get_name(this.parent_anchor)=="a"){a=this.parent_anchor.getAttribute("href");if(parent.$m.is.alive(a)===!0)this.nimg_link_id.value=
a;a=this.parent_anchor.getAttribute("target");if(parent.$m.is.alive(a)===!0&&a=="_blank")this.nimg_link_target_id.checked=!0}else this.parent_anchor=!1;else this.parent_anchor=!1}},create:function(){if($me_image.cur_img!==!1){parent.$m.t.magic_editor.cur_image.src=$me_image.nimg_url_id.value;parent.$m.t.magic_editor.cur_image.title=$me_image.nimg_title_id.value;parent.$m.t.magic_editor.cur_image.alt=$me_image.nimg_alt_id.value;var a="float: ";a+=$me_image.nimg_float_left_id.checked==!0?$me_image.nimg_float_left_id.value:
$me_image.nimg_float_right_id.checked==!0?$me_image.nimg_float_right_id.value:$me_image.nimg_float_none_id.value;a+="; ";parent.$m.is.alive($me_image.nimg_margin_top_id.value)===!0&&(a+="margin-top: "+parseInt($me_image.nimg_margin_top_id.value)+"px; ");parent.$m.is.alive($me_image.nimg_margin_bottom_id.value)===!0&&(a+="margin-bottom: "+parseInt($me_image.nimg_margin_bottom_id.value)+"px; ");parent.$m.is.alive($me_image.nimg_margin_right_id.value)===!0&&(a+="margin-right: "+parseInt($me_image.nimg_margin_right_id.value)+
"px; ");parent.$m.is.alive($me_image.nimg_margin_left_id.value)===!0&&(a+="margin-left: "+parseInt($me_image.nimg_margin_left_id.value)+"px; ");parent.$m.t.magic_editor.cur_image.style.cssText=a;parent.$m.t.magic_editor.cur_image.border=$me_image.nimg_border_id.value;if($me_image.parent_anchor!==!1)$me_image.nimg_link_id.value.length>7?($me_image.parent_anchor.href=$me_image.nimg_link_id.value,$me_image.nimg_link_target_id.checked==!0?$me_image.parent_anchor.setAttribute("target","_blank"):$me_image.parent_anchor.removeAttribute("target")):
parent.$m.tag.replace($me_image.parent_anchor,parent.$m.t.magic_editor.cur_image);else if($me_image.nimg_link_id.value.length>7)if(parent.$m.vd.is_msie7_or_lower)alert("Oops. This won't work with your current browser.");else{var a=parent.$m.tag.clone(parent.$m.t.magic_editor.cur_image),b=parent.$m.tag.init("a",{href:$me_image.nimg_link_id.value});$me_image.nimg_link_target_id.checked==!0&&b.setAttribute("target","_blank");b.appendChild(a);parent.$m.tag.replace(parent.$m.t.magic_editor.cur_image,b)}}else{$me_image.img_html=
'<img src="';a=$me_image.nimg_url_id.value.split(".");a=a[a.length-1].toLowerCase();if(a=="gif"||a=="jpg"||a=="jpeg"||a=="jpe"||a=="png")$me_image.img_html+=$me_image.nimg_url_id.value+'" ';$me_image.img_html+='title="'+$me_image.nimg_title_id.value+'" ';$me_image.img_html+='alt="'+$me_image.nimg_alt_id.value+'" ';$me_image.img_html+='style="float: ';$me_image.img_html+=$me_image.nimg_float_left_id.checked==!0?$me_image.nimg_float_left_id.value:$me_image.nimg_float_right_id.checked==!0?$me_image.nimg_float_right_id.value:
$me_image.nimg_float_none_id.value;$me_image.img_html+="; ";parent.$m.is.alive($me_image.nimg_margin_top_id.value)===!0&&($me_image.img_html+="margin-top: "+parseInt($me_image.nimg_margin_top_id.value)+"px; ");parent.$m.is.alive($me_image.nimg_margin_bottom_id.value)===!0&&($me_image.img_html+="margin-bottom: "+parseInt($me_image.nimg_margin_bottom_id.value)+"px; ");parent.$m.is.alive($me_image.nimg_margin_right_id.value)===!0&&($me_image.img_html+="margin-right: "+parseInt($me_image.nimg_margin_right_id.value)+
"px; ");parent.$m.is.alive($me_image.nimg_margin_left_id.value)===!0&&($me_image.img_html+="margin-left: "+parseInt($me_image.nimg_margin_left_id.value)+"px; ");$me_image.img_html+='" border="'+$me_image.nimg_border_id.value+'">';if($me_image.nimg_link_id.value.length>7)a='<a href="'+$me_image.nimg_link_id.value+'"',$me_image.nimg_link_target_id.checked===!0&&(a+=' target="_blank"'),$me_image.img_html=a+">"+$me_image.img_html+"</a>";parent.$m.t.magic_editor.inject_html($me_image.img_html,"inline")}parent.$m.t.magic_editor.cur_image=
!1;parent.$m.t.darkroom.hide("mjf_darkroom_iframe_div.link")},cancel:function(){parent.$m.t.magic_editor.cur_image=!1;parent.$m.t.darkroom.hide("mjf_darkroom_iframe_div.link")}};window.onload=function(){$me_image.construct()};
