/***************************************************************************
- File: special_characters.js
- Version: 13.6.24
- java -jar compiler2.jar --js special_characters.src.js --js_output_file special_characters.VERSION.js
***************************************************************************/

$m.t.magic_editor.entities = {
"Punctuation" : {
 "lsquo" : ["Open single quote","8216"]
,"rsquo" : ["Close single quote","8217"]
,"ldquo" : ["Open double quotes","8220"]
,"rdquo" : ["Close double quotes","8221"]
,"sbquo" : ["Single low-9 quote","8218"]
,"bdquo" : ["Double low-9 quote","8222"]
,"prime" : ["Prime/minutes/feet","8242"]
,"Prime" : ["Double prime/seconds/inches","8243"]
,"nbsp" : ["Non-breaking space","160"]
,"ndash" : ["En dash","8211"]
,"mdash" : ["Em dash","8212"]
,"ensp" : ["En space","8194"]
,"emsp" : ["Em space","8195"]
,"thinsp" : ["Thin space","8201"]
,"brvbar" : ["Broken vertical bar","166"]
,"bull" : ["Bullet","8226"]
,"hellip" : ["Horizontal ellipsis","8230"]
,"circ" : ["Circumflex","710"]
,"uml" : ["Umlaut or dieresis","168"]
,"tilde" : ["Small tilde","732"]
,"lsaquo" : ["Single left angle quote","8249"]
,"rsaquo" : ["Single right angle quote","8250"]
,"laquo" : ["Left angle quote; guillemotleft","171"]
,"raquo" : ["Right angle quote; guillemotright","187"]
,"oline" : ["Overline","8254"]
,"iquest" : ["Inverted question mark","191"]
,"iexcl" : ["Inverted exclamation","161"]
}

,"Latin Accent Characters" : {
 "Agrave" : ["A, accent grave","192"]
,"Aacute" : ["A, accent acute","193"]
,"Acirc" : ["A, circumflex","194"]
,"Atilde" : ["A, tilde","195"]
,"Auml" : ["A, umlaut or dieresis","196"]
,"Aring" : ["A, ring","197"]
,"AElig" : ["A-E ligature","198"]
,"Ccedil" : ["C, cedilla","199"]
,"Egrave" : ["E, accent grave","200"]
,"Eacute" : ["E, accent acute","201"]
,"Ecirc" : ["E, circumflex","202"]
,"Euml" : ["E, umlaut or dieresis","203"]
,"Igrave" : ["I, accent grave","204"]
,"Iacute" : ["I, accent acute","205"]
,"Icirc" : ["I, circumflex","206"]
,"Iuml" : ["I, umlaut or dieresis","207"]
,"ETH" : ["Eth, capital (Icelandic)","208"]
,"Ntilde" : ["N, tilde","209"]
,"Ograve" : ["O, accent grave","210"]
,"Oacute" : ["O, accent acute","211"]
,"Ocirc" : ["O, circumflex","212"]
,"Otilde" : ["O, tilde","213"]
,"Ouml" : ["O, umlaut or dieresis","214"]
,"Oslash" : ["O, slash","216"]
,"OElig" : ["O-E ligature","338"]
,"Scaron" : ["S, with caron","352"]
,"Ugrave" : ["U, accent grave","217"]
,"Uacute" : ["U, accent acute","218"]
,"Ucirc" : ["U, circumflex","219"]
,"Uuml" : ["U, umlaut or dieresis","220"]
,"Yacute" : ["Y, accent acute","221"]
,"THORN" : ["Thorn, capital (Icelandic)","222"]
,"szlig" : ["Sharp s (German s-z ligature)","223"]
,"agrave" : ["a, accent grave","224"]
,"aacute" : ["a, accent acute","225"]
,"acirc" : ["a, circumflex","226"]
,"atilde" : ["a, tilde","227"]
,"auml" : ["a, umlaut or dieresis","228"]
,"aring" : ["a, ring","229"]
,"aelig" : ["a-e ligature","230"]
,"ccedil" : ["c, cedilla","231"]
,"egrave" : ["e, accent grave","232"]
,"eacute" : ["e, accent acute","233"]
,"ecirc" : ["e, circumflex","234"]
,"euml" : ["e, umlaut or dieresis","235"]
,"igrave" : ["i, accent grave","236"]
,"iacute" : ["i, accent acute","237"]
,"icirc" : ["i, circumflex","238"]
,"iuml" : ["i, umlaut or dieresis","239"]
,"eth" : ["eth, lower-case (Icelandic)","240"]
,"ntilde" : ["n, tilde","241"]
,"ograve" : ["o, accent grave","242"]
,"oacute" : ["o, accent acute","243"]
,"ocirc" : ["o, circumflex","244"]
,"otilde" : ["o, tilde","245"]
,"ouml" : ["o, umlaut or dieresis","246"]
,"oslash" : ["o, slash","248"]
,"oelig" : ["o-e ligature","339"]
,"scaron" : ["s, with caron","353"]
,"ugrave" : ["u, accent grave","249"]
,"uacute" : ["u, accent acute","250"]
,"ucirc" : ["u, circumflex","251"]
,"uuml" : ["u, umlaut or dieresis","252"]
,"yacute" : ["y, accent acute","253"]
,"yuml" : ["y, umlaut or dieresis","255"]
,"thorn" : ["thorn, lower-case (Icelandic)","254"]
}

,"Greek Letters" : {
 "Alpha" : ["Alpha, capital","913"]
,"Beta" : ["Beta, capital","914"]
,"Gamma" : ["Gamma, capital","915"]
,"Delta" : ["Delta, capital","916"]
,"Epsilon" : ["Epsilon, capital","917"]
,"Zeta" : ["Zeta, capital","918"]
,"Eta" : ["Eta, capital","919"]
,"Theta" : ["Theta, capital","920"]
,"Iota" : ["Iota, capital","921"]
,"Kappa" : ["Kappa, capital","922"]
,"Lambda" : ["Lambda, capital","923"]
,"Mu" : ["Mu, capital","924"]
,"Nu" : ["Nu, capital","925"]
,"Xi" : ["Xi, capital","926"]
,"Omicron" : ["Omicron, capital","927"]
,"Pi" : ["Pi, capital","928"]
,"Rho" : ["Rho, capital","929"]
,"Sigma" : ["Sigma, capital","931"]
,"Tau" : ["Tau, capital","932"]
,"Upsilon" : ["Upsilon, capital","933"]
,"Phi" : ["Phi, capital","934"]
,"Chi" : ["Chi, capital","935"]
,"Psi" : ["Psi, capital","936"]
,"Omega" : ["Omega, capital","937"]
,"alpha" : ["Alpha, lower-case","945"]
,"beta" : ["Beta, lower-case","946"]
,"gamma" : ["Gamma, lower-case","947"]
,"delta" : ["Delta, lower-case","948"]
,"epsilon" : ["Epsilon, lower-case","949"]
,"zeta" : ["Zeta, lower-case","950"]
,"eta" : ["Eta, lower-case","951"]
,"theta" : ["Theta, lower-case","952"]
,"iota" : ["Iota, lower-case","953"]
,"kappa" : ["Kappa, lower-case","954"]
,"lambda" : ["Lambda, lower-case","955"]
,"mu" : ["Mu, lower-case","956"]
,"nu" : ["Nu, lower-case","957"]
,"xi" : ["Xi, lower-case","958"]
,"omicron" : ["Omicron, lower-case","959"]
,"pi" : ["Pi, lower-case","960"]
,"rho" : ["Rho, lower-case","961"]
,"sigma" : ["Sigma, lower-case","963"]
,"sigmaf" : ["Small letter final sigma","962"]
,"tau" : ["Tau, lower-case","964"]
,"upsilon" : ["Upsilon, lower-case","965"]
,"phi" : ["Phi, lower-case","966"]
,"chi" : ["Chi, lower-case","967"]
,"psi" : ["Psi, lower-case","968"]
,"omega" : ["Omega, lower-case","969"]
}

,"Symbols" : {
 "sect" : ["Section","167"]
,"copy" : ["Copyright","169"]
,"reg" : ["Registered trademark","174"]
,"trade" : ["Trademark","8482"]
,"ordf" : ["Feminine ordinal","170"]
,"ordm" : ["Masculine ordinal","186"]
,"not" : ["Not sign","172"]
,"shy" : ["Soft hyphen","173"]
,"macr" : ["Macron accent","175"]
,"deg" : ["Degrees","176"]
,"dagger" : ["Dagger","8224"]
,"Dagger" : ["Double dagger","8225"]
,"sup1" : ["Superscript 1","185"]
,"sup2" : ["Superscript 2","178"]
,"sup3" : ["Superscript 3","179"]
,"acute" : ["Accent acute","180"]
,"micro" : ["Micro sign","181"]
,"para" : ["Paragraph symbol (pilcrow)","182"]
,"middot" : ["Middle dot","183"]
,"cedil" : ["Cedilla","184"]
,"cent" : ["Cents sign","162"]
,"pound" : ["Pound Sterling","163"]
,"curren" : ["General currency","164"]
,"yen" : ["Yen","165"]
,"euro" : ["Euro","8364"]
}

,"Math and Logic Symbols" : {
 "plusmn" : ["Plus or minus","177"]
,"times" : ["Multiplication sign","215"]
,"divide" : ["Division sign","247"]
,"and" : ["Logical AND","8743"]
,"or" : ["Logical OR","8744"]
,"ang" : ["Angle","8736"]
,"cup" : ["Union","8746"]
,"cap" : ["Intersection","8745"]
,"empty" : ["Empty set/null set/diameter","8709"]
,"exist" : ["There exists","8707"]
,"fnof" : ["Small f with hook (function)","402"]
,"forall" : ["For all","8704"]
,"frasl" : ["Fraction slash","8260"]
,"le" : ["Less-than or equal-to","8804"]
,"ge" : ["Greater-than or equal-to","8805"]
,"ne" : ["Not equal to","8800"]
,"cong" : ["Approximately equal to","8773"]
,"asymp" : ["Almost equal to","8776"]
,"equiv" : ["Identical to","8801"]
,"infin" : ["Infinity","8734"]
,"int" : ["Integral","8747"]
,"isin" : ["Element of","8712"]
,"notin" : ["Not an element of","8713"]
,"ni" : ["Contains as a member","8715"]
,"sub" : ["Subset of","8834"]
,"nsub" : ["Not a subset of","8836"]
,"sube" : ["Subset of or equal to","8838"]
,"sup" : ["Superset of","8835"]
,"supe" : ["Superset of or equal to","8839"]
,"lang" : ["Left angle bracket","9001"]
,"rang" : ["Right angle bracket (ket)","9002"]
,"rceil" : ["Right ceiling","8969"]
,"rfloor" : ["Right floor","8971"]
,"lceil" : ["Left ceiling","8968"]
,"lfloor" : ["Left floor","8970"]
,"lowast" : ["Asterisk operator","8727"]
,"minus" : ["Minus sign","8722"]
,"nabla" : ["Nabla","8711"]
,"oplus" : ["Circled plus (direct sum)","8853"]
,"otimes" : ["Circled times (vector product)","8855"]
,"part" : ["Partial differential","8706"]
,"permil" : ["Per mille sign","8240"]
,"perp" : ["Orthogonal to/perpendicular","8869"]
,"piv" : ["Greek Pi symbol","982"]
,"prod" : ["N-ary product (product sign)","8719"]
,"sum" : ["N-ary summation","8721"]
,"prop" : ["Proportional to","8733"]
,"radic" : ["Square root/radical","8730"]
,"sdot" : ["Dot operator","8901"]
,"sim" : ["Tilde operator","8764"]
,"there4" : ["Therefore","8756"]
,"thetasym" : ["Small letter theta symbol","977"]
,"upsih" : ["Upsilon with hook symbol","978"]
}

,"Fractions" : {
 "frac14" : ["Fraction 1/4"," 188"]
,"frac12" : ["Fraction 1/2","189"]
,"frac34" : ["Fraction 3/4","190"]
}

,"Arrows" : {
 "larr" : ["Leftward arrow","8592"]
,"rarr" : ["Rightward arrow","8594"]
,"uarr" : ["Upward arrow","8593"]
,"darr" : ["Downward arrow","8595"]
,"harr" : ["Left right arrow","8596"]
,"lArr" : ["Leftward double arrow","8656"]
,"rArr" : ["Rightward double arrow","8658"]
,"uArr" : ["Upward double arrow","8657"]
,"dArr" : ["Downward double arrow","8659"]
,"hArr" : ["Left right double arrow","8660"]
}

}