/***************************************************************************
- File: new_form_fields.js
- Version: 13.3.26
***************************************************************************/

$m.t.new_form_fields={name:"new_form_fields",data_att:"new_form_fields",data_att_close:"new_form_fields_close",nff_att:"data-mjf_nff",good_tags:["input","textarea"],good_types:["text","radio","checkbox","file"],construct:function(b){$m.is.alive($m.lang.new_form_fields)===!1&&$m.ajax_init===!1?$m.insert_link.script($m.config.basedir+"tricks/new_form_fields/lang/"+$m.config.lang+".js",function(){$m.t.new_form_fields.init(b)}):$m.t.new_form_fields.init(b)},exec:function(b){$m.id(b);for(var a={},c=$m.attr.get(b,
$m.t.new_form_fields.nff_att).split("|"),d=!1,b=0,h=c.length;b<h;b++)att_entry=c[b].split(":"),a[att_entry[0]]=att_entry[1];if(a.tag===void 0)$m.t.new_form_fields.missing_att("tag"),d=!0;else if($m.is.in_array($m.t.new_form_fields.good_tags,a.tag)===!1)$m.t.new_form_fields.invalid_att("tag",a.tag),d=!0;else{var g=a.tag;delete a.tag}a.type!==void 0&&a.tag!=="textarea"&&$m.is.in_array($m.t.new_form_fields.good_types,a.type)===!1&&($m.t.new_form_fields.invalid_att("type",a.type),d=!0);$m.is.alive(a.name)===
!1&&($m.t.new_form_fields.missing_att("name"),d=!0);if($m.is.alive(a.parent)===!1)$m.t.new_form_fields.missing_att("parent"),d=!0;else{var e=a.parent;delete a.parent}if(d===!0)return!1;$m.id(a.id)!==!1&&(a.id+="_"+$m.ut.rand_num());if(a.type==="radio"||a.type==="checkbox")if(a.value=prompt($m.lang.new_form_fields.prompt_field_value,""),$m.is.alive(a.value)===!0)a.value="Unknown";c="field_"+a.id+"_"+$m.ut.rand_num();$m.tag.create(e,"span",{id:c});b=e=!1;if(a.br_after_field!==void 0)e=a.br_after_field,
delete a.br_after_field;if(a.label!==void 0){var f=prompt($m.lang.new_form_fields.prompt_label_value,""),i=a.label;delete a.label;$m.is.alive(f)===!0&&(f+=" ",b=!0);if(a.id!==void 0)a.id=a.name}d="img_"+a.id+"_"+$m.ut.rand_num();$m.tag.create(c,"img",{src:$m.config.basedir+"images/icons/icon_trash.png","class":"new_field_close_img",title:"Remove this field",id:d,"data-mjf":"new_form_fields_close","data-mjf_nff_parent":c});$m.id(d);if(b===!0)if(d=!1,a.br_after_label!==void 0&&(delete a.br_after_label,
d=!0),i=="before"){$m.tag.create(c,"label",{"for":a.id,id:a.id+"_"+$m.ut.rand_num()},f);if(d!==!1)for(b=0;b<d;b++)$m.tag.create(c,"br");$m.tag.create(c,g,a)}else $m.tag.create(c,g,a),$m.tag.create(c,"label",{"for":a.id,id:a.id+"_"+$m.ut.rand_num()},f);else $m.tag.create(c,g,a);if(e!==!1)for(b=0;b<e;b++)$m.tag.create(c,"br");$m.init_children(!1)},missing_att:function(b){$m.de.throw_browser_error("Whoops, you have forgotten to include the attribute `"+b+"` for your new field")},invalid_att:function(b,
a){$m.de.throw_browser_error("Whoops, `"+a+"` currently is not an allowed "+b)},close:function(b){$m.tag.remove($m.attr.get(b,"data-mjf_nff_parent"))},init:function(){$m.elements.bind($m.tags.a,this.data_att,"click",this.exec);$m.elements.bind($m.tags.img,this.data_att_close,"click",this.close)}};
