/***************************************************************************
- File: magic.js - Let's have some magic
- Version: 14.7.24
***************************************************************************/

var $m={timer:(new Date).getTime(),timer_ajax:!1,wand:{},trick:{},h:{},t:{},lang:{},vd:{},ready:!1,ajax_init:!1,data_att:"data-mjf",document:document,head_tag:document.getElementsByTagName("head")[0],body_id:"magic_body",ga:!1,debugger_css_version:"12.4.19",xhttp:!1,ajax_ids:{},html_singletons:["area","base","br","col","command","embed","hr","img","iframe","input","link","meta","param","source"],app_cache:{available:!!window.applicationCache},error_wrapper:{open:'<span class="field_error_msg_on">',
close:"</span>"},ajax:function(){this.config={callback:"simple_content_update",element_id:!1,ga_track:!0,method:"get",password:"",query:"",timeout:$m.config.ajax.timeout,update_id:!1,update_id_action:"overwrite",update_id_scroll_top:!1,update_id_scroll_to:!1,url:!1,username:""};this.json_queue=[];this.request={response_text:!1,update_id_action:!1,errord:!1,timeout:{did:!1,id:!1},rs_msg:["0. UNSENT - Open hasn't been called","1. OPENED - Send hasn't been called","2. HEADERS RECEIVED - Send has been called",
"3. LOADING - Server responded; Downloading response data","4. DONE - Operation complete"],error_codes:{e0:"Your request wasn't sent. Something on your computer is blocking it.",e400:"400 Bad Request",e401:"401 Unauthorized",e403:"403 Forbidden",e404:"404 Not Found",e405:"405 Method Not Allowed",e408:"408 Request Timeout",e500:"500 Internal Server Error",e501:"501 Not Implemented",e502:"502 Bad Gateway",e503:"503 Service Unavailable",e504:"504 Gateway Timeout",e505:"505 HTTP Version Not Supported"}};
this.xhttp=$m.init_xml();$m.is.alive(this.xhttp)===!1&&$m.de.throw_browser_error("$m.ajax() unable to initialize AJAX");this.init=function(a){if($m.is.alive(a)===!1)return $m.de.throw_browser_error("Missing IN_VAR argument for $m.ajax.init()"),!1;if($m.is.string(a)===!0){var b={};b.callback=$m.attr.get(a,"data-mjf_ajax_call_on_success");b.element_id=a;b.ga_track=$m.attr.get(a,"data-mjf_ga_track");b.method=$m.attr.get(a,"data-mjf_ajax_method");b.password=$m.attr.get(a,"data-mjf_ajax_password");b.query=
$m.attr.get(a,"data-mjf_ajax_query");b.timeout=$m.attr.get(a,"data-mjf_ajax_timeout");b.update_id=$m.attr.get(a,"data-mjf_ajax_update_id");b.update_id_action=$m.attr.get(a,"data-mjf_ajax_update_id_action");b.update_id_scroll_top=$m.attr.get(a,"data-mjf_ajax_update_id_scroll_top")=="true";b.update_id_scroll_to=$m.attr.get(a,"data-mjf_ajax_update_id_scroll_to");b.url=$m.attr.get(a,"data-mjf_ajax_url");b.username=$m.attr.get(a,"data-mjf_ajax_username")}else b=a;$m.tag.get_name(a)=="form"?b.query=$m.query_string.create(a):
b.query===null?b.query="":(a=$m.query_string.parse(b.query),b.query=$m.query_string.create(a));for(var c in b)$m.is.alive(b[c])===!1||c=="interval"||(this.config[c]=b[c]);if(this.config.callback==="magic_json")this.config.callback="parse_returned_json";if(this.config.ga_track==="false")this.config.ga_track=!1;this.config.timeout=parseInt(this.config.timeout);if(this.config.update_id_scroll_top==="true")this.config.update_id_scroll_top=!0;if(this.config.update_id_scroll_to==="true")this.config.update_id_scroll_to=
!0};this.just_html_update=function(a){if($m.is.alive(a)===!1)return $m.de.throw_browser_error("$m.ajax.just_html_update() === in_this `' + in_this + '` does not exist."),!1;var b=$m.is.good_id(a.config.update_id),c=$m.ev.script(a.request.response_text);if(b===!1)return $m.de.throw_browser_error("$m.ajax.just_html_update() === update_id `' + this_object.config.update_id + '` does not exist."),!1;$m.config.ajax.debug===!0&&$m.de.add_item("$m.ajax.just_html_update() --- this_object.config.update_id = "+
a.config.update_id+" \n this_object.request.response_text = "+a.request.response_text);a.request.errord===!1&&(a.config.update_id_action==="append"?$m.tag.html(b,c,"append"):a.config.update_id_action==="prepend"?$m.tag.html(b,c,"prepend"):$m.tag.html(b,c,"replace"));a.config.update_id_scroll_top===!0&&$m.smooth_scroll_overflow.construct(a.config.update_id,"up");a.config.update_id_scroll_to===!0&&$m.smooth_scroll.construct(a.config.update_id)};this.parse_returned_json=function(a){if($m.is.alive(a)===
!1)return $m.de.throw_browser_error("$m.ajax.parse_returned_json() === in_this `' + in_this + '` does not exist."),!1;var b=$m.try_json_unpack(a.request.response_text),c="",d="",e="";$m.config.ajax.debug===!0&&($m.de.add_item("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \n Executing >>> $m.ajax.parse_returned_json()"),$m.de.add_item("this_object.request.response_text = "+a.request.response_text));if($m.is.alive(b)===!0){for(var f in b)c=b[f],e="replace",$m.config.ajax.debug===
!0&&(a="$m.ajax.parse_returned_json_update() --- current_json properties \n",a+=$m.is.alive(c.update_id)===!0?".update_id = "+c.update_id+"\n":".update_id doesn't exist \n",a+=$m.is.alive(c.update_html)===!0?".update_html = "+c.update_html+"\n":".update_html doesn't exist \n",a+=$m.is.alive(c.update_method)===!0?".update_method = "+c.update_method+"\n":".update_method doesn't exist \n",a+=$m.is.alive(c.update_callback)===!0?".update_callback = "+c.update_callback+"\n":".update_callback doesn't exist \n",
$m.de.add_item("current_json = "+a)),$m.config.ajax.visual===!0&&$m.css_class.add(c.update_id,"ajax_visual_content"),d=$m.is.good_id(c.update_id),$m.is.alive(c.update_method)===!0&&(c.update_method=="append"?e="append":c.update_method=="prepend"&&(e="prepend")),d!==!1&&$m.is.string(c.update_html)===!0&&$m.tag.html(d,c.update_html,e),$m.config.ajax.visual===!0&&setTimeout(function(a){return function(){$m.css_class.remove(a,"ajax_visual_content")}}(c.update_id),1500),$m.is.alive(c.update_callback)===
!0&&$m.ev.all(c.update_callback);$m.timer_ajax=(new Date).getTime();setTimeout(function(){$m.init_children(!0)},500)}else $m.de.throw_browser_error($m.lang.core.ajax.failed_msg)};this.exec=function(){var a=this;setTimeout(function(){a.send(a)},0)};this.send=function(a){$m.config.ajax.debug===!0&&$m.de.add_item("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \n Executing >>> $m.ajax.send()");if($m.config.ajax.debug===!0){var b=" Configuration:\n",c;for(c in a.config)b+=c+" = '"+a.config[c]+
"' \n";$m.de.add_item("$m.ajax.send() --- "+b)}$m.tag.get_name(a.config.element_id)=="a"&&$m.id(a.config.element_id).blur();$m.tag.get_name(a.config.element_id)=="form"&&(b=$m.attr.get(a.config.element_id,"data-mjf_ajax_form_reset"),b!==null&&b=="true"&&$m.id(a.config.element_id).reset());$m.config.ajax.visual===!0&&($m.is.good_id(a.config.element_id)&&($m.tag.get_name(a.config.element_id)=="form"?$m.css_class.add(a.config.element_id,"ajax_visual_form"):$m.css_class.add(a.config.element_id,"ajax_visual")),
$m.is.good_id(a.config.update_id)&&($m.css_class.add(a.config.update_id,"mjf_atrans"),$m.css_class.add(a.config.update_id,"ajax_visual_content")));b=($m.is.alive(a.config.query)===!0?a.config.query:"")+"&ajax_call="+(new Date).getTime();if(a.xhttp){a.xhttp.onreadystatechange=function(){switch(a.xhttp.readyState){case 0:$m.config.ajax.debug===!0&&$m.de.add_item("this_object.xhttp.onreadystatechange() --- xhttp.readyState = "+a.request.rs_msg[0]+" for '"+a.config.element_id+"'");break;case 1:$m.config.ajax.debug===
!0&&$m.de.add_item("this_object.xhttp.onreadystatechange() --- xhttp.readyState = "+a.request.rs_msg[1]+" for '"+a.config.element_id+"'");break;case 2:$m.config.ajax.debug===!0&&$m.de.add_item("this_object.xhttp.onreadystatechange() --- xhttp.readyState = "+a.request.rs_msg[2]+" for '"+a.config.element_id+"'");break;case 3:$m.config.ajax.debug===!0&&$m.de.add_item("this_object.xhttp.onreadystatechange() --- xhttp.readyState = "+a.request.rs_msg[3]+" for '"+a.config.element_id+"'");break;case 4:$m.config.ajax.debug===
!0&&($m.de.add_item("this_object.xhttp.onreadystatechange() --- xhttp.readyState = "+a.request.rs_msg[4]+" for '"+a.config.element_id+"'"),$m.de.add_item("this_object.xhttp.onreadystatechange()--- this_object.xhttp.status = "+a.xhttp.status));if(a.request.timeout.did===!0)a.request.response_text=$m.error_wrapper.open+$m.lang.core.ajax.timeout_msg+$m.error_wrapper.close,a.request.timeout.did=!1,a.request.errord=!0;else{var b="e"+a.xhttp.status;$m.is.alive(a.request.error_codes[b])===!0?(a.request.response_text=
'<span class="field_error_msg_on">'+a.request.error_codes[b]+"</span>",a.request.errord=!0):a.xhttp.status==200?a.request.response_text=a.xhttp.responseText==0?$m.error_wrapper.open+$m.lang.core.ajax.waiting_msg+$m.error_wrapper.close:a.xhttp.responseText:a.request.errord=!0}clearTimeout(a.request.timeout.id);if($m.is.alive(a[a.config.callback])===!0)a[a.config.callback](a);else if($m.is.alive(window[a.config.callback])===!0)window[a.config.callback](a);else $m.de.throw_browser_error("this_object.xhttp.onreadystatechange() === this_object.config.callback `' + this_object.config.callback + '` does not exist.");
a.request.errord=!1;a.config.ga_track===!0&&$m.track.ga({category:"MJF AJAX",action:a.config.element_id+" "+$m.ut.uppercase_first(a.config.method),label:a.config.url});$m.config.ajax.visual===!0&&($m.is.good_id(a.config.element_id)&&($m.tag.get_name(a.config.element_id)=="form"?$m.css_class.remove(a.config.element_id,"ajax_visual_form"):$m.css_class.remove(a.config.element_id,"ajax_visual")),$m.is.good_id(a.config.update_id)&&setTimeout(function(){$m.css_class.remove(a.config.update_id,"ajax_visual_content")},
1500))}};switch(a.config.method.toLowerCase()){case "get":a.xhttp.open("GET",a.config.url+"?"+b,!0,a.config.username,a.config.password);$m.config.ajax.debug===!0&&$m.de.add_item("$m.ajax.send() --- this_object.xhttp.open('GET', '"+a.config.url+"?"+b+"', true, "+a.config.username+", "+a.config.password+")");a.xhttp.send(null);break;case "post":a.xhttp.open("POST",a.config.url,!0,a.config.username,a.config.password),$m.config.ajax.debug===!0&&$m.de.add_item("$m.ajax.send() --- this_object.xhttp.open('POST', '"+
a.config.url+"', true, "+a.config.username+", "+a.config.password+")"),a.xhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded"),a.xhttp.send(b)}a.request.timeout.id=setTimeout(function(){a.timed_out(a)},a.config.timeout*1E3)}else a.request.response_text=$m.error_wrapper.open+$m.lang.core.ajax.failed_msg+$m.error_wrapper.close,a.config.update_id_action="overwrite",a.request.errord=!0,a.just_html_update();return!0};this.simple_content_update=function(a){if($m.is.alive(a)===!1)return $m.de.throw_browser_error("$m.ajax.simple_content_update() === in_this `' + in_this + '` does not exist."),
!1;var b=$m.is.good_id(a.config.update_id),c=$m.ev.script(a.request.response_text);if(b===!1)return $m.de.throw_browser_error("$m.ajax.simple_content_update() === update_id `' + this_object.config.update_id + '` does not exist."),!1;$m.config.ajax.debug===!0&&$m.de.add_item("$m.ajax.simple_content_update() --- $m.ajax.config.update_id = "+a.config.update_id+" \n $m.ajax.request.response_text = "+a.request.response_text);a.request.errord===!0?$m.tag.html(b,c,"prepend"):a.config.update_id_action===
"append"?$m.tag.html(b,c,"append"):a.config.update_id_action==="prepend"?$m.tag.html(b,c,"prepend"):$m.tag.html(b,c,"replace");a.config.update_id_scroll_top===!0&&$m.smooth_scroll_overflow.construct(a.config.update_id,"up");a.config.update_id_scroll_to===!0&&$m.smooth_scroll.construct(a.config.update_id);$m.timer_ajax=(new Date).getTime();setTimeout(function(){$m.init_children(!0)},500);a.request.errord=!1};this.timed_out=function(a){a.request.timeout.did=!0;a.xhttp.abort()}},animation:function(a,
b){this.position=a===void 0?0:a;this.target=b===void 0?0:b;this.velocity=0;this.interval=null;this.exec=function(a,b,e){this.interval&&window.clearInterval(this.interval);this.interval=window.setInterval(this.create_closure(b,e),a)};this.create_closure=function(a,b){var e=this;return function(){e.update();a(e.position,e);if(e.has_stopped())window.clearInterval(e.interval),e.interval=null,b&&b(e)}};this.update=function(){this.velocity<0?this.target>this.position-this.velocity*(this.velocity-1)/2?this.velocity++:
this.target<=this.position-(this.velocity-1)*(this.velocity-2)/2&&this.velocity--:this.target<this.position+this.velocity*(this.velocity+1)/2?this.velocity--:this.target>=this.position+(this.velocity+1)*(this.velocity+2)/2&&this.velocity++;this.position+=this.velocity;return this.position};this.has_stopped=function(){return this.position==this.target&&this.velocity==0};return this},animate:{opaque:function(a,b,c,d){if($m.config.animations.use===!0){var e=$m.is.string(a)===!0?$m.id(a):a,a=$m.is.alive(b)?
b:"up",f=b=0,c=$m.is.alive(c)?c:100,g=$m.is.alive(d)?d:function(){},h=1;a=="up"?(b=0,f=10,e.style.opacity=0,h=1):(b=10,f=0,e.style.opacity=1,h=0);(new $m.animation(b,f)).exec(c,function(a){a*=0.1;e.style.opacity=a},function(){e.style.opacity=h;g()})}else g()},css:{opacity:function(a){$m.config.animations.use===!0&&$m.css_class.add(a,"mjf_otrans")}}},array:{remove_value:function(a,b){var c=Array.prototype.indexOf?a.indexOf(b):$m.array.index_of(a,b);c!=-1?a.splice(c,1):$m.de.add_item("$m.array.remove_value() --- in_value ("+
b+") NOT FOUND!");return a},index_of:function(a,b,c){for(var c=c||0,d=a.length;c<d;){if(a[c]===b)return c;++c}return-1}},attr:{set:function(a,b){if($m.is.alive(a)===!1)return!1;var c=$m.is.string(a)===!0?$m.id(a):a,d;for(d in b){d=="class"&&$m.vd.is_msie7_or_lower&&(tmp_val=b[d],d="className",b[d]=tmp_val);try{c.setAttribute(d,b[d])}catch(e){$m.de.throw_fatal("$m.attr.set(`"+a+"`, `"+d+"="+b[d]+"`) --- failed because "+e)}}return!0},get:function(a,b){if($m.is.alive(a)===!1)return!1;var c=$m.is.string(a)===
!0?$m.id(a):a;return $m.vd.is_msie7_or_lower===!0?$m.is.alive(c.attributes)===!0&&$m.is.object(c.attributes[b])===!0&&$m.is.alive(c.attributes[b].nodeValue)===!0?c.attributes[b].nodeValue:null:c.getAttribute?(c=c.getAttribute(b),c===null?null:c):!1},get_tags_with:function(a,b,c){for(var d=[],e=0,f=a.length;e<f;e++)$m.attr.get(a[e],"id")!==null&&$m.attr.get(a[e],b)!==null&&$m.attr.has_value(a[e],b,c)===!0&&d.push(a[e]);return d},get_fields_with:function(a,b,c,d){var c=c||!1,d=d||!1,e=a=="document"?
$m.id($m.body_id):$m.id(a),a=[];$m.is.in_array(b,"text")!==!1&&(b=b.concat(["color","date","datetime","datetime-local","email","month","number","search","tel","time","url","week"]));if($m.is.in_array(b,["button","checkbox","file","password","radio","submit","text"])!==!1)for(var f=$m.tags.get(e,"input"),g=0,h=f.length;g<h;g++)for(var i in b)c===!1&&d===!1?a.push(f[g]):f[g].type==b[i]&&$m.attr.has_value(f[g],c,d)===!0&&a.push(f[g]);if($m.is.in_array(b,"textarea")!==!1){i=$m.tags.get(e,"textarea");
g=0;for(f=i.length;g<f;g++)c===!1&&d===!1?a.push(i[g]):$m.attr.has_value(i[g],c,d)===!0&&a.push(i[g])}if($m.is.in_array(b,"select")!==!1){b=$m.tags.get(e,"select");g=0;for(e=b.length;g<e;g++)c===!1&&d===!1?a.push(b[g]):$m.attr.has_value(b[g],c,d)===!0&&a.push(b[g])}return a},get_all:function(a){for(var a=$m.id(a),b={},c=a.attributes.length,d=0;d<c;d++)if($m.vd.is_msie7_or_lower){if(a.attributes[d].specified&&a.attributes[d].name)b[a.attributes[d].name]=a.attributes[d].value}else if(a.attributes[d].name)b[a.attributes[d].name]=
a.attributes[d].value;return b},has_value:function(a,b,c){if($m.is.alive(a)===!1)return!1;$m.is.string(a)===!0&&(a=$m.id(a));if(a.getAttribute)if(a=$m.attr.get(a,b),$m.is.alive(a)===!1)return!1;else{if(a.indexOf("|")!=-1)var d=a.split("|");else if(a.indexOf(" ")!=-1)d=a.split(" ");else if($m.is.string(a)===!0)return a==c?!0:!1;return $m.is.in_array(d,c)===!1?!1:!0}else return!1},remove:function(a,b){$m.id(a).removeAttribute(b)}},construct:function(a){$m.config="";$m.config.basedir="";$m.config=a;
$m.is.alive($m.config.basedir)===!1&&this.find_baseurl();if($m.is.alive($m.config.lang)===!1)$m.config.lang="en_us";$m.insert_link.script($m.config.basedir+"lang/"+$m.config.lang+".js",function(){$m.dt.localize()});typeof JSON!="object"&&$m.insert_link.script($m.config.basedir+"assist/json2.js");this.vd.construct();this.dt.calc_timezone();$m.config.create_html5===!0&&$m.vd.is_msie9_or_lower&&$m.create_html5()},create_html5:function(){for(var a=["abbr","article","aside","audio","bb","canvas","datagrid",
"datalist","details","dialog","eventsource","figure","footer","header","hgroup","mark","menu","meter","nav","output","progress","section","time","video"],b=0,c=a.length;b<c;b++)document.createElement(a[b])},css_class:{add:function(a,b){var c=$m.attr.get(a,"class");$m.is.alive(c)===!1?$m.attr.set(a,{"class":b}):(c=c.split(" "),$m.is.in_array(c,b)===!1&&(c.push(b),$m.attr.set(a,{"class":c.join(" ")})))},remove:function(a,b){var c=$m.attr.get(a,"class");if($m.is.alive(c)===!1)return!1;else{var c=c.split(" "),
d=$m.is.in_array(c,b);if(d!==!1)c.splice(d,1),$m.attr.set(a,{"class":c.join(" ")});else return!1}},replace:function(a,b,c){$m.css_class.remove(a,b);$m.css_class.add(a,c)},has:function(a,b){return $m.attr.has_value(a,"class",b)}},cursor:{set:function(a,b){var c=$m.id(a);if($m.is.alive(c)===!1)return!1;if(c.value.length==0)try{c.focus()}catch(d){$m.de.add_item("$m.cursor.get("+a+", "+b+") --- failed because "+d)}else{var e=0,e=b=="end"?c.value.length:b;if(c.setSelectionRange)try{c.focus(),c.setSelectionRange(c.value.length,
e)}catch(f){$m.de.add_item("$m.cursor.get("+a+", "+b+") --- failed during id.setSelectionRange")}else if(c.createTextRange)try{range=c.createTextRange(),range.collapse(!0),range.moveEnd("character",e),range.moveStart("character",c.value.length),range.select()}catch(g){$m.de.add_item("$m.cursor.get("+a+", "+b+") --- failed during id.createTextRange")}}},get:function(a){var b=$m.id(a);if($m.is.alive(b)===!1)return!1;if(b.selectionStart)return b.selectionStart;else if(document.selection){b.focus();a=
document.selection.createRange();if(a==null)return 0;var b=b.createTextRange(),c=b.duplicate();b.moveToBookmark(a.getBookmark());c.setEndPoint("EndToStart",b);return c.text.length}return 0}},de:{name:"magic_debugger",construct:function(){if($m.vd.is_mobile_touch!==!0){if(this.new_document===void 0){var a=window.open("","debug_win","toolbar=no,location=no,resizable=yes,scrollbars=yes,menubar=no,width=600,height=700");if(a===void 0||a===null)return setTimeout(function(){alert("Please allow pop-up windows if you'd like to use the Magic Debugger.")},
10),$m.config.global_debug=!1;this.new_document=a.document;this.new_document.write('<!DOCTYPE html><html><head><title>Magic Debugger</title><link href="'+$m.config.basedir+"stylesheets/magic_debugger."+$m.debugger_css_version+'.css" rel="stylesheet"></head><body><h1>Magic Debugger &raquo; '+$m.dt.get_date_now()+" "+$m.dt.get_time_now()+'</h1><p id="clear_debugger"><input type="button" value="clear" onclick="window.opener.$m.de.clear_debugger();"></p><div id="debug_box"></div></body></html>');this.new_document.close()}$m.vd.is_safari===
!0&&a.blur();this.debug_box_id=this.new_document.getElementById("debug_box")}},add_item:function(a){if($m.config.global_debug===!1)return!1;var a=a.replace(RegExp("<","gi"),"&lt;"),a=a.replace(RegExp(">","gi"),"&gt;"),a=a.replace(RegExp("\n","gi"),"<br>"),b=((new Date).getTime()-$m.timer)/1E3+"";b.length==3?b+="00":b.length==4&&(b+="0");$m.vd.is_mobile_touch===!0?console.log(b+" | "+a):$m.is.alive(this.debug_box_id)===!0?this.debug_box_id.innerHTML="<p>"+b+" | "+a+"</p>"+arguments.callee.trace()+
this.debug_box_id.innerHTML:$m.de.throw_browser_error("Magic Debugger not available. "+b+" | "+a)},clear_debugger:function(){this.debug_box_id.innerHTML=" ";return!1},throw_browser_error:function(a){setTimeout("throw new Error('MJS: "+a+"')",0)},get_wand:function(){var a="Debugging 'wand' ~~",b;for(b in $m.wand)$m.h[b]!==void 0&&(a+="$m.wand."+b+"="+$m.wand[b]+"; ");this.add_item(a)},get_tricks:function(){var a="Debugging 'tricks' ~~",b;for(b in $m.trick)$m.h[b]!==void 0&&(a+="$m.trick."+b+"="+$m.trick[b]+
"; ");this.add_item(a)},get_this:function(a,b){this.add_item("Debugging This '"+a+"' ~~");for(var c in b)this.add_item("k = "+c+" ~~> "+b[c])},get_array:function(a,b){this.add_item("Debugging Array '"+a+"' ~~");if($m.is.array(b))if(b.length==0)this.add_item(a+" is empty");else for(var c=0,d=b.length;c<d;c++)this.add_item(a+"["+c+"] = "+b[c]);else this.add_item("Oops! '"+a+"' isn't an array!")},get_object:function(a,b){this.add_item("Debugging Object '"+a+"' ~~");for(var c in b)this.add_item("Property='"+
c+"'; Type='"+typeof b[c]+"'; Value='"+b[c]+"' ~~~~~ ")},get_type:function(a,b){this.add_item("typeof ("+a+") == "+typeof b)},throw_error:function(a,b,c){$m.de.add_item("~~ JavaScript Error: "+a+" ~~ Line: "+c+" ~~ URL: "+b);return!0},throw_fatal:function(a){$m.de.add_item(a);$m.de.throw_browser_error(a)}},style:{get:function(a,b){if($m.is.alive(a)===!1)return!1;var c=$m.is.string(a)===!0?$m.id(a):a,d="";if(document.defaultView&&document.defaultView.getComputedStyle)try{d=document.defaultView.getComputedStyle(c,
null).getPropertyValue(b)}catch(e){return $m.de.throw_fatal("$m.style.get(`"+a+"`, `"+b+"`) --- failed because "+e),!1}else c.currentStyle&&(b=b.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()}),d=c.currentStyle[b]);return d},set:function(a,b){if($m.is.alive(a)===!1)return!1;var c=$m.is.string(a)===!0?$m.id(a):a,d="",e;for(e in b){if($m.is.alive(c.style)===!1)c.style={};try{d=$m.vd.is_firefox===!0&&e=="float"?"cssFloat":e,c.style[d]=b[e]}catch(f){$m.de.throw_fatal("$m.style.set(`"+a+"`, `"+
e+"="+b[e]+"`) --- failed because "+f)}}}},dt:{current_year:!1,current_month:!1,current_date:!1,current_hour:!1,current_minute:!1,current_second:!1,current_milliseconds:!1,am_pm:!1,timezone:!1,timezone_dst:!1,localize:function(){$m.dt.month_names=[$m.lang.core.months.long_name.jan,$m.lang.core.months.long_name.feb,$m.lang.core.months.long_name.mar,$m.lang.core.months.long_name.apr,$m.lang.core.months.long_name.may,$m.lang.core.months.long_name.jun,$m.lang.core.months.long_name.jul,$m.lang.core.months.long_name.aug,
$m.lang.core.months.long_name.sep,$m.lang.core.months.long_name.oct,$m.lang.core.months.long_name.nov,$m.lang.core.months.long_name.dec];$m.dt.month_names_short=[$m.lang.core.months.short_name.jan,$m.lang.core.months.short_name.feb,$m.lang.core.months.short_name.mar,$m.lang.core.months.short_name.apr,$m.lang.core.months.short_name.may,$m.lang.core.months.short_name.jun,$m.lang.core.months.short_name.jul,$m.lang.core.months.short_name.aug,$m.lang.core.months.short_name.sep,$m.lang.core.months.short_name.oct,
$m.lang.core.months.short_name.nov,$m.lang.core.months.short_name.dec];$m.dt.month_days=[31,28,31,30,31,30,31,31,30,31,30,31];$m.dt.weekdays=[$m.lang.core.weekdays.short_name.sun,$m.lang.core.weekdays.short_name.mon,$m.lang.core.weekdays.short_name.tue,$m.lang.core.weekdays.short_name.wed,$m.lang.core.weekdays.short_name.thu,$m.lang.core.weekdays.short_name.fri,$m.lang.core.weekdays.short_name.sat,"","","","",""]},get_date_now:function(){this.obj_date=new Date;this.current_year=this.obj_date.getFullYear();
this.current_month=this.obj_date.getMonth();this.current_month++;if(this.current_month<10)this.current_month="0"+this.current_month;this.current_date=this.obj_date.getDate();if(this.current_date<10)this.current_date="0"+this.current_date;return this.current_year+"-"+this.current_month+"-"+this.current_date},get_time_now:function(){this.obj_date=new Date;this.current_hour=this.obj_date.getHours();this.am_pm=this.current_hour<12?"am":"pm";if(this.current_hour==0)this.current_hour=12;this.current_hour>
12&&(this.current_hour-=12);this.current_minute=this.obj_date.getMinutes();this.current_minute+="";if(this.current_minute.length==1)this.current_minute="0"+this.current_minute;this.current_second=this.obj_date.getSeconds();this.current_second+="";if(this.current_second.length==1)this.current_second="0"+this.current_second;this.current_milliseconds=this.obj_date.getMilliseconds();this.current_milliseconds=this.current_second+"";if(this.current_milliseconds.length==1)this.current_milliseconds="0"+this.current_milliseconds;
return this.current_hour+":"+this.current_minute+":"+this.current_second+this.am_pm},calc_timezone:function(){var a=new Date,b=new Date(a.getFullYear(),0,1,0,0,0,0),a=new Date(a.getFullYear(),6,1,0,0,0,0),c=b.toGMTString(),d=new Date(c.substring(0,c.lastIndexOf(" ")-1)),c=a.toGMTString(),c=new Date(c.substring(0,c.lastIndexOf(" ")-1)),b=(b-d)/36E5,a=(a-c)/36E5;b==a?this.timezone_dst="0":(b-a>=0&&(b=a),this.timezone_dst="1");this.timezone=b;$m.config.send_timezone_to!==!1&&$m.insert_link.script($m.config.send_timezone_to+
"?tz="+this.timezone)},convert:function(a){var b=parseInt(a);a-=parseInt(a);a*=60;var c=parseInt(a);a-=parseInt(a);a*=60;parseInt(a);a=b;a=b==0?"00":b>0?b<10?"+0"+b:"+"+b:b>-10?"-0"+Math.abs(b):b;return a+":"+(c<10?"0"+c:c)}},element:{bind:function(a,b,c){var a=$m.is.string(a)===!0?$m.id(a):a,b="on"+b,d=a[b];a[b]=typeof a[b]=="function"?function(a){d(a);c(a)}:c},attach:function(a,b,c){a=$m.is.string(a)===!0?$m.id(a):a;if(document.addEventListener)a.addEventListener(b,c,!0);else if(document.attachEvent)a.attachEvent("on"+
b,c);else return!1},detach:function(a,b,c){a=$m.is.string(a)===!0?$m.id(a):a;if(document.removeEventListener)a.removeEventListener(b,c,!0);else if(document.detachEvent)a.detachEvent("on"+b,c);else return!1}},elements:{listeners:[],bind:function(a,b,c,d){var c="on"+c,e="",f="",f="";if(a.length===void 0){var g=[];g[0]=a}else $m.is.alive(a.tagName)===!0&&a.tagName.toLowerCase()=="select"?(g=[],g[0]=a):g=a;for(var a=0,h=g.length;a<h;a++)if($m.attr.has_value(g[a],$m.data_att,b)===!0){for(var e=$m.attr.get(g[a],
"id"),f=$m.attr.get(g[a],$m.data_att),f=f.split("|"),i=0,j=f.length;i<j;i++)if(f[i]==b)break;$m.is.array(this.listeners[e])!==!0&&(this.listeners[e]=[]);$m.is.array(this.listeners[e][c])!==!0&&(this.listeners[e][c]=[]);g[a][c]=$m.exec[c];this.listeners[e][c][i]=d;$m.attr.has_value(g[a],$m.data_att,"return_false")===!0&&$m.attr.set(e,{"data-mjf_return_value":"false"})}}},ev:{all:function(a){return eval(a)},script:function(a){var b="",c=/<script\s?(.|\n)*?>(.|\n)*?<\/script>/gi,d=a.match(c);if(d){for(var a=
a.replace(c,""),c=0,e=d.length;c<e;c++)b+=$m.tags.strip.from_cont(d[c]);$m.ev.all(b)}return a}},event:{get:function(a){if($m.is.alive(a)===!1)a=window.event;$m.is.alive(a.originalEvent);return a},get_target:function(a){if($m.is.alive(a)===!1)return!1;return a.target||a.srcElement}},exec:{go:function(a,b,c){for(var d in $m.elements.listeners[a][b])if($m.elements.listeners[a][b][d](a,c)===!1)return!1;return $m.returnd.get(a)===!1?!1:!0},onabort:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,
"id"),"onabort",a)},onblur:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onblur",a)},onclick:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onclick",a)},onchange:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onchange",a)},ondblclick:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"ondblclick",a)},onfocus:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onfocus",a)},onkeydown:function(a){a=
a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onkeydown",a)},onkeypress:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onkeypress",a)},onkeyup:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onkeyup",a)},onload:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onload",a)},onmousemove:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onmousemove",a)},onmousedown:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,
"id"),"onmousedown",a)},onmouseup:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onmouseup",a)},onmouseover:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onmouseover",a)},onmouseout:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onmouseout",a)},onreset:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onreset",a)},onresize:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onresize",
a)},onselect:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onselect",a)},onsubmit:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onsubmit",a)},onunload:function(a){a=a||window.event;return $m.exec.go($m.attr.get(this,"id"),"onunload",a)}},execute:function(){if($m.ready!==!0)$m.ready=!0,$m.config.global_debug!==!1&&$m.de.construct(),$m.is.alive($m.config.geo)===!0&&$m.config.geo.use!==!1&&$m.geo.construct(),$m.set_body_id(),$m.storage.construct(),
$m.init_children(!1),$m.config.global_debug==="high"&&$m.de.add_item("$m.vd.ua = "+$m.vd.ua),$m.de.add_item("~ MJS initialized in "+((new Date).getTime()-$m.timer)/1E3+" seconds")},find_baseurl:function(){for(var a=$m.tags.get("document","script"),b="",c=/magic.(\d{1,2}\.\d{1,2}\.\d{1,2}|src).js$/,d=0,e=a.length;d<e;d++)if($m.vd.is_msie7_or_lower===!0){if(b=a[d].getAttribute("src",4),$m.is.alive(b)===!0&&a[d].src.match(c)){b=b.replace("http(s)?://"+window.location.hostname,"");$m.config.basedir=b.replace(c,
"");break}}else if($m.is.alive(a[d].src)===!0&&a[d].src.match(c)){$m.config.basedir=a[d].src.replace("http(s)?://"+window.location.hostname,"").replace(c,"");break}},fix_msie:function(){if($m.vd.is_msie7_or_lower)document.nativeGetElementById=document.getElementById,document.getElementById=function(a){var b=document.nativeGetElementById(a);if(b)if(b.attributes.id.value==a)return b;else for(b=1;b<document.all[a].length;b++)if(document.all[a][b].attributes.id.value==a)return document.all[a][b];return null}},
geo:{name:"geo",has:!1,watch_id:!1,defaults:{keep_watching:!1,max_age:300,timeout:15},error_codes:{0:"Unknown error",1:"Permission denied",2:"Position unavailable",3:"Timed out"},request:{callback_success:!1,element_id:!1,error:!1,found_location:!1,keep_watching:!1,max_age:!1,timeout:!1,update_id:!1},pos:{},construct:function(){$m.config.geo.debug===!0&&$m.de.add_item("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \n Executing >>> $m.geo.construct()");"geolocation"in navigator?
($m.geo.has=!0,$m.geo.get_pos()):$m.de.add_item("navigator.geolocation doesn't exist in this browser.")},init_settings:function(a){$m.config.geo.debug===!0&&$m.de.add_item("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \n Executing >>> $m.geo.init_settings()");var b=$m.attr.get(a,"data-mjf_geo_call_on_success"),c=$m.attr.get(a,"data-data-mjf_geo_max_age"),d=$m.attr.get(a,"data-data-mjf_geo_timeout");return{callback_success:b===null?"$m.geo.simple_content_update()":b,keep_watching:$m.attr.get(a,
"data-data-mjf_geo_keep_watching")=="true"?!0:!1,max_age:parseInt($m.is.alive(c)===!0?c:$m.geo.defaults.max_age)*1E3,timeout:parseInt($m.is.alive(d)===!0?d:$m.geo.defaults.timeout)*1E3,update_id:$m.attr.get(a,"data-mjf_geo_update_id")}},send_request:function(a,b){$m.config.geo.debug===!0&&$m.de.add_item("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \n Executing >>> $m.geo.send_request()");$m.geo.request.element_id=b;if($m.geo.has===!0)$m.css_class.add($m.geo.request.element_id,
"geo_visual"),$m.css_class.add($m.geo.request.update_id,"geo_visual_content"),$m.geo.request.callback_success=a.callback_success,$m.geo.request.keep_watching=a.keep_watching,$m.geo.request.max_age=a.max_age,$m.geo.request.timeout=a.timeout,$m.geo.request.update_id=a.update_id,$m.geo.get_pos();else return!1},get_pos:function(){$m.config.geo.debug===!0&&$m.de.add_item("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \n Executing >>> $m.geo.get_pos()");$m.geo.watch_id=navigator.geolocation.watchPosition(function(a){$m.geo.get_watch(a)},
function(a){$m.geo.get_error(a)},{maximumAge:$m.geo.request.max_age,timeout:$m.geo.request.timeout});$m.config.geo.debug===!0&&$m.de.add_item("$m.geo.watch_id = "+$m.geo.watch_id)},get_watch:function(a){$m.config.geo.debug===!0&&$m.de.add_item("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \n Executing >>> $m.geo.get_watch()");$m.geo.clear_watch();$m.config.geo.visual===!0&&($m.css_class.remove($m.geo.request.element_id,"geo_visual"),$m.css_class.remove($m.geo.request.update_id,
"geo_visual_content"));if($m.is.alive(a)===!0){$m.geo.request.found_location=!0;$m.geo.pos.timestamp=$m.is.alive(a.timestamp)===!0?a.timestamp:!1;$m.geo.pos.coords={};$m.is.alive(a.coords)===!0?($m.geo.pos.coords.latitude=$m.is.alive(a.coords.latitude)===!0?a.coords.latitude:!1,$m.geo.pos.coords.longitude=$m.is.alive(a.coords.longitude)===!0?a.coords.longitude:!1,$m.geo.pos.coords.accuracy=$m.is.alive(a.coords.accuracy)===!0?a.coords.accuracy:!1,$m.geo.pos.coords.altitude=$m.is.alive(a.coords.altitude)===
!0?a.coords.altitude:!1,$m.geo.pos.coords.altitudeAccuracy=$m.is.alive(a.coords.altitudeAccuracy)===!0?a.coords.altitudeAccuracy:!1,$m.geo.pos.coords.heading=$m.is.alive(a.coords.heading)===!0&&isNaN(a.coords.heading)===!1?a.coords.heading:!1,$m.geo.pos.coords.speed=$m.is.alive(a.coords.speed)===!0&&isNaN(a.coords.speed)===!1?a.coords.speed:!1):($m.geo.pos.coords.latitude=!1,$m.geo.pos.coords.longitude=!1,$m.geo.pos.coords.accuracy=!1,$m.geo.pos.coords.altitude=!1,$m.geo.pos.coords.altitudeAccuracy=
!1,$m.geo.pos.coords.heading=!1,$m.geo.pos.coords.speed=!1);if($m.config.geo.debug===!0){var a=" coordinates:\n",b;for(b in $m.geo.pos.coords)a+=b+" = '"+$m.geo.pos.coords[b]+"' \n";$m.de.add_item("$m.geo.get_watch() --- "+a)}$m.ev.all($m.geo.request.callback_success)}else $m.geo.request.found_location=!1,$m.geo.get_error(2);$m.config.geo.debug===!0&&$m.de.add_item("$m.geo.request.found_location = "+$m.geo.request.found_location)},get_error:function(a){if($m.geo.request.found_location===!1)$m.config.geo.debug===
!0&&$m.de.add_item("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \n Executing >>> $m.geo.get_error()"),$m.geo.clear_watch(),$m.config.geo.visual===!0&&($m.css_class.remove($m.geo.request.element_id,"geo_visual"),$m.css_class.remove($m.geo.request.update_id,"geo_visual_content")),$m.is.good_id($m.geo.request.update_id)?$m.tag.html($m.geo.request.update_id,$m.error_wrapper.open+"Error getting location: "+$m.geo.error_codes[a.code]+"."+$m.error_wrapper.close,"prepend"):$m.de.throw_browser_error("$m.geo.get_error() $m.geo.request.update_id `"+
$m.geo.request.update_id+"` does not exist."),$m.geo.request.error=!0},simple_content_update:function(){$m.config.geo.debug===!0&&$m.de.add_item("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \n Executing >>> $m.geo.simple_content_update()");var a=$m.is.good_id($m.geo.request.update_id);if($m.is.alive(a)===!0){var b='<table class="general_table">';b+='<tr><td class="align_right">Timestamp</td><td>'+($m.is.alive($m.geo.pos.timestamp)?$m.geo.pos.timestamp:"&mdash;")+"</td></tr>";
b+='<tr><td class="align_right">Latitude</td><td>'+($m.is.alive($m.geo.pos.coords.latitude)?$m.geo.pos.coords.latitude:"&mdash;")+"</td></tr>";b+='<tr><td class="align_right">Longitude</td><td>'+($m.is.alive($m.geo.pos.coords.longitude)?$m.geo.pos.coords.longitude:"&mdash;")+"</td></tr>";b+='<tr><td class="align_right">Accuracy</td><td>'+($m.is.alive($m.geo.pos.coords.accuracy)?$m.geo.pos.coords.accuracy+" meters":"&mdash;")+"</td></tr>";b+='<tr><td class="align_right">Altitude</td><td>'+($m.is.alive($m.geo.pos.coords.altitude)?
$m.geo.pos.coords.altitude+" meters":"&mdash;")+"</td></tr>";b+='<tr><td class="align_right">Altitude Accuracy</td><td>'+($m.is.alive($m.geo.pos.coords.altitudeAccuracy)?$m.geo.pos.coords.altitudeAccuracy+" meters":"&mdash;")+"</td></tr>";b+='<tr><td class="align_right">Heading</td><td>'+($m.is.alive($m.geo.pos.coords.heading)?$m.geo.pos.coords.heading+" degrees":"&mdash;")+"</td></tr>";b+='<tr><td class="align_right">Speed</td><td>'+($m.is.alive($m.geo.pos.coords.speed)?$m.geo.pos.coords.speed+" meters per second":
"&mdash;")+"</td></tr>";b+="<table>";$m.tag.html(a,b,"replace")}else $m.de.throw_browser_error("$m.geo.simple_content_update() $m.geo.request.update_id `"+$m.geo.request.update_id+"` does not exist.")},clear_watch:function(){$m.config.geo.debug===!0&&($m.de.add_item("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \n Executing >> $m.geo.clear_watch("+$m.geo.watch_id+")"),$m.de.add_item("$m.geo.request.keep_watching = "+$m.geo.request.keep_watching));$m.geo.request.keep_watching===
!1&&navigator.geolocation.clearWatch($m.geo.watch_id)}},get_flash_object:function(a){return $m.vd.is_msie===!0?window[a]:document[a]},get_form_fields:function(a,b){return $m.attr.get_fields_with(a,b)},get_keycode:function(a){var b="";if(!a)a=window.event;return b=a.keyCode?a.keyCode:a.which?a.which:!1},id:function(a){return $m.is.object(a)===!0?a:$m.is.alive(a)===!1?!1:document.getElementById(a)===void 0||document.getElementById(a)===null?!1:document.getElementById(a)},init_children:function(a){if(a===
!0)$m.ajax_init=!0;$m.document=document;$m.tags.a=$m.tags.get("document","a");$m.tags.all=$m.tags.get("document","*");$m.tags.img=$m.tags.get("document","img");$m.tags.form=$m.tags.get("document","form");$m.config.global_debug==="high"&&$m.de.add_item("$m.init_children() -- starting wand init");for(var b in $m.wand)this.h[b]===void 0?(a='$m.wand "'+b+'" is not initialized correctly',$m.de.throw_browser_error(a)):(this.h[b].construct($m.wand[b]),$m.config.global_debug==="high"&&$m.de.add_item("Executed >> $m.h."+
b+".construct("+$m.wand[b]+")"));$m.config.global_debug==="high"&&$m.de.add_item("$m.init_children() -- starting trick init");for(var c in $m.trick)if($m.t[c]===void 0)a='trick "'+c+'" is not initialized correctly!',$m.de.throw_browser_error(a);else{$m.t[c].construct($m.trick[c]);for(var d in $m.trick[c])d=="config"||d=="toJSON"||($m.t[c][d]===void 0?(a='$m.trick "'+c+"."+d+'" is not initialized correctly',$m.de.throw_browser_error(a)):($m.t[c][d].construct($m.trick[c][d]),$m.config.global_debug===
"high"&&$m.de.add_item("Executed >> $m.t["+c+"]["+d+"].construct($m.trick["+c+"]["+d+"])")))}$m.config.global_debug==="high"&&$m.de.add_item("$m.init_children() -- finished trick init");$m.config.global_debug&&$m.ajax_init&&$m.de.add_item("~ MJS re-initialized in "+((new Date).getTime()-$m.timer_ajax)/1E3+" seconds");$m.ajax_init=!1},init_xml:function(){var a=!1;try{a=new ActiveXObject("Msxml2.XMLHTTP")}catch(b){try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(c){a=new XMLHttpRequest}}return a},
insert_link:{stylesheet:function(a){$m.head_tag.appendChild($m.tag.init("link",{rel:"stylesheet",type:"text/css",href:a}))},script:function(a,b){var c={charset:"UTF-8",type:"text/javascript"};if($m.is.alive(a)===!0)c.src=a;var d=$m.tag.init("script",c);if($m.is.alive(b)===!0)d.addEventListener?d.addEventListener("load",function(){b()},!1):d.onreadystatechange=function(){if(d.readyState in{loaded:1,complete:1})d.onreadystatechange=null,b()};$m.head_tag.appendChild(d)}},is:{alive:function(a){if(a===
void 0||a===null||a===!1)return!1;else if($m.is.object(a)===!0)return!0;else if($m.is.array(a)===!0){if(a<=0)return!1}else return a===""?!1:!0},array:function(a){return typeof a=="object"&&a instanceof Array},in_array:function(a,b){if($m.is.object(b)===!0)for(var c=0,d=b.length;c<d;c++){if($m.is.string(b[c])===!0)for(var e=0,f=a.length;e<f;e++)if($m.is.string(a[e])===!0&&b[c]==a[e])return!0}else{c=0;for(f=a.length;c<f;c++)if(a[c]==b)return c}return!1},good_id:function(a){if($m.is.alive(a)===!1)return!1;
a=$m.is.object(a)===!0?a:$m.id(a);if($m.is.alive(a)===!1)return!1;return a},func:function(a){return typeof a=="function"},number:function(a){return typeof a=="number"},object:function(a){return typeof a=="object"},string:function(a){return typeof a=="string"},good_string:function(a){return typeof a=="string"&&a!=""?!0:!1}},keycode:{get:function(a){var b="";if(!a)a=window.event;return b=a.keyCode?a.keyCode:a.which?a.which:!1},is_worthy:function(a){return a==8||a==16||a==46||a==188||a>=48&&a<=90||a>=
96&&a<=107||a>=109&&a<=111||a>=190&&a<=192||a>=219&&a<=222?!0:!1}},query_string:{create:function(a){if($m.is.alive(a)===!1)return $m.de.throw_browser_error("$m.query_string.create() === in_object `' + in_object + '` does not exist."),!1;var b=$m.is.string(a)===!0||$m.is.array(a)!==!1?$m.id(a):a;if($m.tag.get_name(b)=="form"){for(var c="",d=$m.tags.get(b,"input"),a=0,e=d.length;a<e;a++)d[a].type=="radio"&&d[a].checked===!0?c+="&"+$m.attr.get(d[a],"name")+"="+encodeURIComponent(d[a].value):d[a].type==
"checkbox"&&d[a].checked===!0?c+="&"+$m.attr.get(d[a],"name")+"="+encodeURIComponent(d[a].value):(d[a].type=="radio"||d[a].type=="checkbox")&&d[a].checked!==!0||(c+="&"+$m.attr.get(d[a],"name")+"="+encodeURIComponent(d[a].value));d=$m.tags.get(b,"textarea");a=0;for(e=d.length;a<e;a++)$m.is.alive(d[a].value)!==!1&&(c+="&"+$m.attr.get(d[a],"name")+"="+encodeURIComponent(d[a].value));b=$m.tags.get(b,"select");a=0;for(d=b.length;a<d;a++)for(var e=0,f=b[a].length;e<f;e++)b[a][e].selected===!0&&(c+="&"+
$m.attr.get(b[a],"name")+"="+encodeURIComponent(b[a][e].value));return c}else{c=[];for(d in a)a.hasOwnProperty(d)&&c.push(encodeURIComponent(d)+"="+encodeURIComponent(a[d]));return c.join("&")}},parse:function(a){if($m.is.string(a)===!1)return $m.de.throw_browser_error("$m.query_string.parse() === in_string argument does not exist."),!1;for(var a=a.substring(a.indexOf("?")+1).split("&"),b=[],c={},d=0;d<a.length;d++)b=a[d].split("="),c[decodeURIComponent(b[0])]=decodeURIComponent(b[1]);return c}},
media:{supports:{h264:function(){if(!$m.media.supports.video())return!1;return document.createElement("video").canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"')},theora:function(){if(!$m.media.supports.video())return!1;return document.createElement("video").canPlayType('video/ogg; codecs="theora, vorbis"')},vorbis:function(){if(!$m.media.supports.video())return!1;return document.createElement("video").canPlayType('video/webm; codecs="vp8, vorbis"')},flash:function(){return typeof navigator.plugins!=
"undefined"&&typeof navigator.plugins["Shockwave Flash"]=="object"||window.ActiveXObject&&new ActiveXObject("ShockwaveFlash.ShockwaveFlash")!=!1},video:function(){return!!document.createElement("video").canPlayType}}},mouse_btn:{get:function(a){var b="";if($m.is.alive(a)===!1)a=window.event;return b=$m.is.alive(a.button)===!0?a.button:$m.is.alive(a.which)===!0?a.which:!1}},position:{is_scrolled_into_view:function(){},get_x:function(a){for(var b=$m.id(a),a=b.offsetLeft,b=b.offsetParent;b!=null;)a+=
b.offsetLeft,b=b.offsetParent;return a},get_x2:function(a){var a=$m.id(a),b=0;do b+=a.offsetLeft;while(a=a.offsetParent);return b},get_y:function(a){for(var b=$m.id(a),a=b.offsetTop,b=b.offsetParent;b!=null;)a+=b.offsetTop,b=b.offsetParent;return a},get_y2:function(a){var a=$m.id(a),b=0;do b+=a.offsetTop;while(a=a.offsetParent);return b},get_xy:function(a){for(var b=$m.id(a),a=b.offsetLeft,c=b.offsetTop,b=b.offsetParent;b!=null;)a+=b.offsetLeft,c+=b.offsetTop,b=b.offsetParent;return[a,c]},get_xy2:function(a){var a=
$m.id(a),b=pos_y=0;do b+=a.offsetLeft,pos_y+=a.offsetTop;while(a=a.offsetParent);return[b,pos_y]}},returnd:{set:function(a,b){$m.attr.set(a,{"data-mjf_return_value":b})},get:function(a){return $m.attr.get(a,"data-mjf_return_value")==="false"?!1:!0}},set_body_id:function(){$m.body_tag=document.getElementsByTagName("body")[0];var a=$m.attr.get($m.body_tag,"id");a===null?$m.attr.set($m.body_tag,{id:$m.body_id}):$m.body_id=a},selection:{get:function(a){return $m.is.alive(a)===!0?a.getSelection():window.getSelection()},
replace:function(a,b){if($m.is.alive(b)===!0)var c=b.getSelection(),d=b;else c=window.getSelection(),d=document;var e="",f="";if(c.getRangeAt&&c.rangeCount){e=c.getRangeAt(0);e.deleteContents();if(e.createContextualFragment)f=e.createContextualFragment(a);else{c=d.createElement("div");c.innerHTML=a;for(f=d.createDocumentFragment();d=c.firstChild;)f.appendChild(d)}e.insertNode(f)}else if(d.selection&&d.selection.type!="Control")try{d.body.focus(),e=d.selection.createRange(),e.pasteHTML(a)}catch(g){return $m.de.throw_browser_error("$m.selection.replace() --- cannot pasteHTML()"),
!1}}},shortcut:{shift_nums:{"`":"~",1:"!",2:"@",3:"#",4:"$",5:"%",6:"^",7:"&",8:"*",9:"(",0:")","-":"_","=":"+",";":":","'":'"',",":"<",".":">","/":"?","\\":"|"},special_keys:{esc:27,escape:27,tab:9,space:32,"return":13,enter:13,backspace:8,scrolllock:145,scroll_lock:145,scroll:145,capslock:20,caps_lock:20,caps:20,numlock:144,num_lock:144,num:144,pause:19,"break":19,insert:45,home:36,"delete":46,end:35,pageup:33,page_up:33,pu:33,pagedown:34,page_down:34,pd:34,left:37,up:38,right:39,down:40,f1:112,
f2:113,f3:114,f4:115,f5:116,f6:117,f7:118,f8:119,f9:120,f10:121,f11:122,f12:123},default_opt:{type:"keydown",propagate:!1,target:document,keycode:!1},bind:function(a,b,c){if($m.vd.is_mobile_touch!==!0&&a!==!1){a=a.toLowerCase();if($m.is.alive(c)===!0)for(var d in $m.shortcut.default_opt)$m.is.alive(c[d])===!1&&(c[d]=$m.shortcut.default_opt[d]);else c=$m.shortcut.default_opt;var e=c,c=$m.is.alive(e.target)===!0?$m.id(e.target):e.target;$m.element.attach(c,e.type,function(c){$m.shortcut.modifiers={shift:{wanted:!1,
pressed:!1},ctrl:{wanted:!1,pressed:!1},alt:{wanted:!1,pressed:!1},meta:{wanted:!1,pressed:!1}};var c=c||window.event,d;if(c.target)d=c.target;else if(c.srcElement)d=c.srcElement;if(d.nodeType==3)d=d.parentNode;if(!(d.tagName=="INPUT"||d.tagName=="TEXTAREA")){d=$m.get_keycode(c);var h=String.fromCharCode(d).toLowerCase();d==188&&(h=",");d==190&&(h=".");var i=a.split("+"),j=0;if(c.ctrlKey)$m.shortcut.modifiers.ctrl.pressed=!0;if(c.shiftKey)$m.shortcut.modifiers.shift.pressed=!0;if(c.altKey)$m.shortcut.modifiers.alt.pressed=
!0;if(c.metaKey)$m.shortcut.modifiers.meta.pressed=!0;for(var l=0;k=i[l],l<i.length;l++)k=="ctrl"||k=="control"?($m.shortcut.modifiers.ctrl.wanted=!0,j++):k=="shift"?($m.shortcut.modifiers.shift.wanted=!0,j++):k=="alt"?($m.shortcut.modifiers.alt.wanted=!0,j++):k=="cmd"||k=="command"?($m.shortcut.modifiers.meta.wanted=!0,j++):k.length>1?$m.shortcut.special_keys[k]==d&&j++:e.keycode?e.keycode==d&&j++:h==k?j++:$m.shortcut.shift_nums[h]&&c.shiftKey&&(h=$m.shortcut.shift_nums[h],h==k&&j++);if(j==i.length&&
$m.shortcut.modifiers.ctrl.pressed==$m.shortcut.modifiers.ctrl.wanted&&$m.shortcut.modifiers.shift.pressed==$m.shortcut.modifiers.shift.wanted&&$m.shortcut.modifiers.alt.pressed==$m.shortcut.modifiers.alt.wanted&&$m.shortcut.modifiers.meta.pressed==$m.shortcut.modifiers.meta.wanted&&($m.is.string(b)===!0?$m.ev.all(b):b(c),e.propagate===!1))return $m.stop_bubble(c),!1}})}}},smooth_scroll:{steps:25,interval:!1,pos_x:!1,pos_y:!1,size:0,start_cur_y_pos:0,now_cur_y_pos:0,is_above:!1,is_above_now:!1,construct:function(a,
b,c){$m.id(a);b=$m.is.alive(b)===!0?b:0;c=$m.is.alive(c)===!0?c:0;clearInterval($m.smooth_scroll.interval);$m.smooth_scroll.size=0;$m.vd.get_view_port();var d=$m.vd.scrolled_top,a=$m.position.get_xy(a);$m.smooth_scroll.pos_x=a[0]-c;$m.smooth_scroll.pos_y=a[1]-b;$m.vd.is_kindle===!0&&window.scrollTo($m.smooth_scroll.pos_x,$m.smooth_scroll.pos_y);$m.smooth_scroll.size=parseInt(($m.smooth_scroll.pos_y-d)/$m.smooth_scroll.steps);$m.smooth_scroll.interval=setInterval(function(){$m.smooth_scroll.exec()},
10)},exec:function(){$m.vd.get_view_port();$m.smooth_scroll.start_cur_y_pos=$m.vd.scrolled_top;$m.smooth_scroll.is_above=$m.smooth_scroll.start_cur_y_pos<$m.smooth_scroll.pos_y;window.scrollTo($m.smooth_scroll.pos_x,$m.smooth_scroll.start_cur_y_pos+$m.smooth_scroll.size);$m.vd.get_view_port();$m.smooth_scroll.now_cur_y_pos=$m.vd.scrolled_top;$m.smooth_scroll.is_above_now=$m.smooth_scroll.now_cur_y_pos<$m.smooth_scroll.pos_y;if($m.smooth_scroll.is_above!=$m.smooth_scroll.is_above_now||$m.smooth_scroll.start_cur_y_pos==
$m.smooth_scroll.now_cur_y_pos)clearInterval($m.smooth_scroll.interval),setTimeout(function(){window.scrollTo($m.smooth_scroll.pos_x,$m.smooth_scroll.pos_y)},500)}},smooth_scroll_overflow:{steps:25,interval:!1,scroll_id:!1,way:!1,pos_x:!1,pos_y:!1,size:0,start_cur_y_pos:0,now_cur_y_pos:0,is_above:!1,is_above_now:!1,construct:function(a,b){var c=$m.id(a);clearInterval($m.smooth_scroll_overflow.interval);$m.smooth_scroll_overflow.scroll_id=c;if($m.vd.is_kindle===!0)$m.smooth_scroll_overflow.scroll_id.scrollTop=
b=="down"?$m.smooth_scroll_overflow.scroll_id.scrollHeight:0;$m.smooth_scroll_overflow.size=0;$m.smooth_scroll_overflow.pos_y=b=="down"?$m.smooth_scroll_overflow.scroll_id.scrollHeight:0;$m.smooth_scroll_overflow.size=parseInt(($m.smooth_scroll_overflow.pos_y-$m.smooth_scroll_overflow.scroll_id.scrollTop)/$m.smooth_scroll_overflow.steps);$m.smooth_scroll_overflow.interval=setInterval(function(){$m.smooth_scroll_overflow.exec()},10)},exec:function(){$m.smooth_scroll_overflow.start_cur_y_pos=$m.smooth_scroll_overflow.scroll_id.scrollTop;
$m.smooth_scroll_overflow.is_above=$m.smooth_scroll_overflow.start_cur_y_pos<$m.smooth_scroll_overflow.pos_y;$m.smooth_scroll_overflow.scroll_id.scrollTop=$m.smooth_scroll_overflow.start_cur_y_pos+$m.smooth_scroll_overflow.size;$m.smooth_scroll_overflow.now_cur_y_pos=$m.smooth_scroll_overflow.scroll_id.scrollTop;$m.smooth_scroll_overflow.is_above_now=$m.smooth_scroll_overflow.now_cur_y_pos<$m.smooth_scroll_overflow.pos_y;($m.smooth_scroll_overflow.is_above!=$m.smooth_scroll_overflow.is_above_now||
$m.smooth_scroll_overflow.start_cur_y_pos==$m.smooth_scroll_overflow.now_cur_y_pos)&&clearInterval($m.smooth_scroll_overflow.interval)}},stop_bubble:function(a){if($m.is.object(a)===!1)a=window.event;if($m.is.alive(a)===!1)return $m.de.add_item("$m.stop_bubble() --- returning false. 'in_event' is dead."),!1;a.cancelBubble=!0;a.returnValue=!1;a.stopPropagation&&(a.stopPropagation(),a.preventDefault())},storage:{name:"storage",db_magic:"magic_js.",db_wand:"wand.",construct:function(){if($m.is.alive(window.webkitIndexedDB)===
!0)$m.storage.indexed_db.available=!0,$m.storage.indexed_db.init(window.webkitIndexedDB);if($m.is.alive(window.mozIndexedDB)===!0)$m.storage.indexed_db.available=!0,$m.storage.indexed_db.init(window.mozIndexedDB);if($m.is.alive(window.msIndexedDB)===!0)$m.storage.indexed_db.available=!0,$m.storage.indexed_db.init(window.msIndexedDB);if($m.is.alive(window.indexedDB)===!0)$m.storage.indexed_db.available=!0,$m.storage.indexed_db.init(window.indexedDB);if($m.is.alive(window.localStorage)===!0)$m.storage.local.available=
!0;if($m.vd.cookies_enabled===!0)$m.storage.cookies.available=!0},compare:function(a,b,c){switch(b){case "=":if(a==c)return!0;break;case "!=":if(a!=c)return!0;break;case "%":if(a.match(c))return!0;break;case ">":if(a>c)return!0;break;case ">=":if(a>=c)return!0;break;case "<":if(a<c)return!0;break;case "<=":if(a<=c)return!0}return!1},create:{data_record:function(a,b,c){var a=$m.storage.create.full_page_id(a),d={};d[a]={};d[a][b]=c;return d},full_page_id:function(a){return $m.ut.friendly_url(window.location)+
"|"+a}},debug:function(a){if($m.is.alive(a)===!0)$m.is.alive($m.storage.local.available)===!0?$m.storage.local.debug(a):$m.is.alive($m.storage.cookies.available)===!0&&$m.storage.cookies.debug(a);else return $m.de.throw_browser_error("Magic Storage: Missing TABLE NAME argument for $m.storage.debug()"),!1},drop:function(a){if($m.is.alive(a)===!0)$m.is.alive($m.storage.local.available)===!0?$m.storage.local.drop(a):$m.is.alive($m.storage.cookies.available)===!0&&$m.storage.cookies.drop(a);else return $m.de.throw_browser_error("Magic Storage: Missing TABLE NAME argument for $m.storage.drop()"),
!1},get:{page_tiny_id:function(a){return a.replace(RegExp($m.ut.friendly_url(window.location)+"\\|","gm"),"")},page_code:function(a){a=a.split("|");return $m.is.alive(a[0])===!0?a[0]:!1},records:function(a,b,c,d){if($m.is.alive(a)===!1)return $m.de.throw_browser_error("Magic Storage: Missing TABLE NAME argument for $m.storage.get.records()"),!1;if($m.is.alive(b)===!1)return $m.de.throw_browser_error("Magic Storage: Missing COLUMN argument for $m.storage.get.records()"),!1;if($m.is.alive(c)===!1)return $m.de.throw_browser_error("Magic Storage: Missing OPERATOR argument for $m.storage.get.records()"),
!1;if($m.is.alive(d)===!1)return $m.de.throw_browser_error("Magic Storage: Missing VALUE argument for $m.storage.get.records()"),!1;var e=[];$m.is.alive($m.storage.local.available)===!0?e=$m.storage.local.get(a):$m.is.alive($m.storage.cookies.available)===!0&&(e=$m.storage.cookies.get(a));a=$m.try_json_unpack(e);if(a===!1)return $m.de.throw_browser_error("Magic Storage: Records cannot be unpacked during $m.storage.get.records()"),!1;for(var f in a)for(var g in a[f])g==b&&(found_record=$m.storage.compare(a[f][g],
c,d),found_record===!0&&e.push(a[f]));e.length==0&&(e=null);return e},table:function(a){var b=[];$m.is.alive($m.storage.local.available)===!0?b=$m.storage.local.get(a):$m.is.alive($m.storage.cookies.available)===!0&&(b=$m.storage.cookies.get(a));a=$m.try_json_unpack(b);if(a===!1)return $m.de.throw_browser_error("Magic Storage: Records cannot be unpacked during $m.storage.get.records()"),!1;return a}},remove:function(a,b){if($m.is.alive(a)===!1)return $m.de.throw_browser_error("Magic Storage: Missing TABLE NAME argument for $m.storage.remove()"),
!1;if($m.is.alive(b)===!1)return $m.de.throw_browser_error("Magic Storage: Missing ID argument for $m.storage.remove()"),!1;var c=$m.storage.create.full_page_id(b),d=!1,e=!1;$m.is.alive($m.storage.local.available)===!0?d=$m.storage.local.get(a):$m.is.alive($m.storage.cookies.available)===!0&&(d=$m.storage.cookies.get(a));if($m.is.alive(d)===!0){d=$m.try_json_unpack(d);if(d===!1)return $m.de.throw_browser_error("Magic Storage: Records cannot be unpacked during $m.storage.remove()"),!1;for(var f in d)f==
c&&delete d[f];c=$m.try_json_pack(d);if(c===!1)return $m.de.throw_browser_error("Magic Storage: Records cannot be packed during $m.storage.remove()"),!1;else $m.is.alive($m.storage.local.available)===!0?$m.storage.local.set(a,c):$m.is.alive($m.storage.cookies.available)===!0&&$m.storage.cookies.set(a,c)}},set:function(a,b){if($m.is.alive(a)===!1)return $m.de.throw_browser_error("Magic Storage: Missing TABLE NAME argument for $m.storage.set()"),!1;if($m.is.alive(b)===!1)return $m.de.throw_browser_error("Magic Storage: Missing RECORDS argument for $m.storage.set()"),
!1;var c=!1,d=!1;$m.is.alive($m.storage.local.available)===!0?c=$m.storage.local.get(a):$m.is.alive($m.storage.cookies.available)===!0&&(c=$m.storage.cookies.get(a));if($m.is.alive(c)===!0){c=$m.try_json_unpack(c);d=!1;if(c===!1)return $m.de.throw_browser_error("Magic Storage: Records cannot be unpacked during $m.storage.set()"),!1;for(var e in c){for(var f in b)e==f&&(c[e]=b[f],d=!0);d===!1?c[f]=b[f]:d=!1}d=c}else d=b;e=$m.try_json_pack(d);if(e===!1)return $m.de.throw_browser_error("Magic Storage: Records cannot be packed during $m.storage.set()"),
!1;else $m.is.alive($m.storage.local.available)===!0?$m.storage.local.set(a,e):$m.is.alive($m.storage.cookies.available)===!0&&$m.storage.cookies.set(a,e)},truncate:function(a){if($m.is.alive(a)===!0)$m.is.alive($m.storage.local.available)===!0?$m.storage.local.truncate(a):$m.is.alive($m.storage.cookies.available)===!0&&$m.storage.cookies.truncate(a);else return $m.de.throw_browser_error("Magic Storage: Missing TABLE NAME argument for $m.storage.truncate()"),!1},indexed_db:{available:!1,driver:!1,
debug:function(){},drop:function(a){window.localStorage.removeItem($m.storage.db_magic+a)},get:function(a){a=window.localStorage.getItem($m.storage.db_magic+a);return $m.is.alive(a)===!0?a:null},init:function(a){$m.storage.indexed_db.driver=a},set:function(a,b){window.localStorage.setItem($m.storage.db_magic+a,b)},truncate:function(a){window.localStorage.setItem($m.storage.db_magic+a,"")}},local:{available:!1,debug:function(){},drop:function(a){window.localStorage.removeItem($m.storage.db_magic+a)},
get:function(a){a=window.localStorage.getItem($m.storage.db_magic+a);return $m.is.alive(a)===!0?a:null},set:function(a,b){window.localStorage.setItem($m.storage.db_magic+a,b)},truncate:function(a){window.localStorage.setItem($m.storage.db_magic+a,"")}},cookies:{available:!1,debug:function(){},drop:function(a){$m.storage.cookies.freeze($m.storage.db_magic+a,"","",-1)},freeze:function(a,b,c,d){$m.is.alive(b)===!1&&(b="");a=escape(a)+"="+escape(b);a+=";path=";a+=$m.is.alive(c)===!0?c:"/";$m.is.alive(d)===
!0&&(c=new Date,c.setTime(c.getTime()+d*864E5),a+=";expires="+c.toGMTString());document.cookie=a;return!0},get:function(a){a=$m.storage.cookies.thaw($m.storage.db_magic+a);return $m.is.alive(a)===!0?a:null},set:function(a,b){$m.storage.cookies.freeze($m.storage.db_magic+a,b)},thaw:function(a){for(var b=document.cookie.split("; "),c="",a=escape(a),d=0,e=b.length;d<e;d++)if(c=b[d].split("="),c[0]==a)return unescape(c[1]);return!1},truncate:function(a){$m.storage.cookies.freeze($m.storage.db_magic+a,
"","",30)}}},tag:{get_body:function(a){a=a=="document"?document:$m.id(a);$m.is.alive(a)===!1&&(a=document);a=a.getElementsByTagName("body");return $m.is.alive(a[0])===!0?a[0]:!1},get_head:function(a){a=a=="document"?document:$m.id(a);$m.is.alive(a)===!1&&(a=document);a=a.getElementsByTagName("head");return $m.is.alive(a[0])===!0?a[0]:!1},get_name:function(a){a=$m.is.string(a)===!0?$m.id(a):a;if($m.is.alive(a)===!1||$m.is.alive(a.nodeName)===!1)return!1;return a.nodeName.toLowerCase()},get_iframe_doc:function(a){if($m.is.alive(a)===
!1)return $m.de.throw_browser_error("Missing IN_ID argument for $m.tag.get_iframe_doc()"),!1;var b=$m.id(a),c=!1;try{if(b.contentWindow&&b.contentWindow.document)c=b.contentWindow.document;else if(b.contentDocument&&b.contentDocument.document)c=b.contentDocument.document}catch(d){}return $m.is.alive(c)===!0?c:($m.de.throw_browser_error('$m.tag.get_iframe_doc("'+a+'") is NOT part of the DOM'),!1)},get_prev_sibling:function(a){a=$m.is.string(a)===!0?$m.id(a):a;if($m.is.alive(a)===!1||$m.is.alive(a.previousSibling)===
!1)return!1;do a=a.previousSibling;while(a&&a.nodeType!=1);return a},get_next_sibling:function(a){a=$m.is.string(a)===!0?$m.id(a):a;if($m.is.alive(a)===!1||$m.is.alive(a.nextSibling)===!1)return!1;do a=a.nextSibling;while(a&&a.nodeType!=1);return a},init:function(a,b,c){if($m.is.alive(a)===!1)return!1;$m.is.alive(c)===!1&&(c=document);a=c.createElement(a);$m.is.alive(b)===!0&&$m.attr.set(a,b);return a},create:function(a,b,c,d,e,f){if($m.is.alive(b)===!1)return!1;$m.is.alive(f)===!1&&(f=document);
b=f.createElement(b);$m.attr.set(b,c);$m.is.object(a)===!1&&(a=$m.id(a));if($m.is.alive(e)===!0)e==="first"&&a.insertBefore(b,a.firstChild),e==="last"&&a.appendChild(b);else try{a.appendChild(b)}catch(g){return $m.de.throw_browser_error("Unable to appendChild in $m.tag.create() --- failed because "+g),!1}if($m.is.alive(d)===!0)b.innerHTML=d;return b},insert_after:function(a,b){if($m.is.alive(a)===!1||$m.is.alive(b)===!1)return!1;$m.is.alive(a.parentNode)===!0?a.nextSibling?a.parentNode.insertBefore(b,
a.nextSibling):a.parentNode.appendChild(b):$m.de.add_item("$m.tag.insert_after() parentNode does not exist")},insert_before:function(a,b){if($m.is.alive(a)===!1||$m.is.alive(b)===!1)return!1;$m.is.alive(a.parentNode)===!0?a.previousSibling?a.parentNode.insertBefore(b,a):a.parentNode.appendChild(b):$m.de.add_item("$m.tag.insert_before() "+a+".parentNode does not exist")},clone:function(a,b){if($m.is.alive(a)===!1)return!1;var c=$m.is.string(a)===!0?$m.id(a):a,d=$m.is.alive(b)===!1?!1:!0;return c.cloneNode(d)},
replace:function(a,b){if($m.is.alive(a)===!1)return $m.de.throw_browser_error("Missing `in_old` argument for $m.tag.replace()"),!1;if($m.is.alive(b)===!1)return $m.de.throw_browser_error("Missing `in_new` argument for $m.tag.replace()"),!1;var c=$m.is.string(a)===!0?$m.id(a):a;if($m.is.alive(c.parentNode)===!1)return $m.de.throw_browser_error("`old_element.parentNode does not exist for $m.tag.replace()"),!1;try{return c.parentNode.replaceChild(b,c)}catch(d){return $m.de.throw_browser_error("Unable to replace nodes in $m.tag.replace() --- failed because "+
d),!1}},remove:function(a){if($m.is.alive(a)===!1)return!1;var a=$m.is.string(a)===!0?$m.id(a):a,b=!1;try{b=a.parentNode.removeChild(a)}catch(c){b=!1}return b},remove_children:function(a){if($m.is.alive(a)===!1)return!1;for(var a=$m.is.string(a)===!0?$m.id(a):a,b=[];a.hasChildNodes();)b.push(a.removeChild(a.lastChild));return b},html:function(a,b,c,d){if($m.is.alive(a)===!1)return $m.de.throw_fatal("$m.tag.html(`"+a+"`) --- failed because the argument does not exist"),!1;$m.is.alive(c)===!1&&(c="replace");
$m.is.alive(d)===!1&&(d=!1);d!==!1&&(b=decodeURIComponent(b));a=$m.is.string(a)===!0?$m.id(a):a;if(a.value!==void 0&&$m.tag.get_name(a)!="li")c=="append"?a.value+=b:a.value=c=="prepend"?b+a.value:b;else{var d=document.createDocumentFragment(),e=d.appendChild(document.createElement("div"));if($m.is.object(b)===!0){for(var f=[],g=0,h=b.length;g<h;g++)f.push(b[g]);g=0;for(h=f.length;g<h;g++)e.appendChild(f[g])}else e.innerHTML=b;if($m.is.alive(e.childNodes)===!0){c=="replace"&&$m.tag.remove_children(a);
if(c=="prepend")var i=a.firstChild;g=0;for(h=e.childNodes.length;g<h;g++)c=="prepend"?a.insertBefore(e.childNodes[g].cloneNode(!0),i):a.appendChild(e.childNodes[g].cloneNode(!0))}$m.tag.remove(d)}}},tags:{get:function(a,b){var c=a=="document"?document:$m.id(a);$m.is.alive(c)===!1&&(c=document);return c.getElementsByTagName(b.toUpperCase())},strip:{from_cont:function(a){return a.replace(/<\/?[^>]+(>|$)/g,"")},from_id:function(a){return $m.id(a).innerHTML.replace(/<\/?[^>]+(>|$)/g,"")}},remove:{these:[],
exec:function(){var a=0;did_work=!1;for(var b=0,c=$m.tags.remove.these.length;b<c;b++)did_work=$m.is.alive($m.tags.remove.these[b])===!0?$m.tag.remove($m.tags.remove.these[b]):!1,did_work!==!1&&a++;return a},empty:{has_good_children:!1,construct:function(a){if($m.is.alive(a)===!1)return!1;a=$m.is.string(a)===!0?$m.id(a):a;removed_cnt=0;$m.tags.remove.empty.populate(a);removed_cnt=$m.tags.remove.exec();$m.tags.remove.these=[];return removed_cnt},populate:function(a){for(var b=a.childNodes,a=a.childNodes.length,
c=0;c<a;c++){$m.tags.remove.empty.has_good_children=!1;var d=b[c];d.hasChildNodes()&&$m.tags.remove.empty.populate(d);if($m.is.alive(d.nodeName)===!0&&$m.is.in_array($m.html_singletons,d.nodeName.toLowerCase())===!1){if(d.textContent==""||d.innerText=="")$m.tags.remove.empty.has_good_children===!1?$m.tags.remove.these.push(d):$m.tags.remove.empty.has_good_children=!0}else $m.tags.remove.empty.has_good_children=!0}}}}},track:{ga:function(a){if($m.is.alive(a)===!1)return!1;typeof pageTracker=="object"&&
typeof pageTracker._trackPageview=="function"?pageTracker._trackEvent(a.category,a.action,a.label):typeof _gaq=="object"&&_gaq.push(["_trackEvent",a.category,a.action,a.label]);setTimeout(function(){},100)}},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},try_json_pack:function(a){try{return JSON.stringify(a)}catch(b){return!1}},try_json_unpack:function(a){try{return JSON.parse(a)}catch(b){return!1}},ut:{add_commas:function(a){if($m.is.alive(a)===!1)return!1;for(var a=a.replace(/,/g,"")+"",b=
a.split("."),a=b[0],b=b.length>1?"."+b[1]:"",c=/(\d+)(\d{3})/;c.test(a);)a=a.replace(c,"$1,$2");return a+b},array_unique:function(a){if($m.is.alive(a)===!1)return!1;var b=[],c=0,d=a.length;a:for(;c<d;c++){for(var e=0,f=b.length;e<f;e++)if(b[e]==a[c])continue a;b[b.length]=a[c]}return b},friendly_url:function(a){if($m.is.alive(a)===!1)return!1;for(var b=a.toString(a),a="",a=$m.trim(b.toLowerCase()),b=[8216,8217,8220,8221],c="",d=0,e=b.length;d<e;d++)c=RegExp(String.fromCharCode(b[d]),"gm"),a=a.replace(c,
"");a=a.replace(/'+/g,"");a=a.replace(/[^\w]+/g,"_");return a=a.replace(/^_+|_+$/g,"")},obj_merge:function(a,b){if($m.is.alive(a)===!1||$m.is.alive(b)===!1)return!1;for(var c in b)try{b[c].constructor==Object?a[c]=$m.ut.obj_merge(a[c],b[c]):a[c]=b[c]}catch(d){a[c]=b[c]}return a},set_prop_to_val:function(a,b,c){if($m.is.alive(a)===!1||$m.is.alive(b)===!1||$m.is.alive(c)===!1)return!1;a[b]=c},dash_space_to_underscore:function(a){if($m.is.alive(a)===!1)return!1;return a.replace(/[\-\s]/g,"_")},dash_underscore_to_space:function(a){if($m.is.alive(a)===
!1)return!1;return a.replace(/[\-_\s]/g," ")},dash_underscore_space_to_slash:function(a){if($m.is.alive(a)===!1)return!1;return a.replace(/[\-_\s]/g,"/")},initial_uppercase:function(a){if($m.is.alive(a)===!1)return!1;return a.replace(/([A-Za-z]+)/g,function(a,c){return c.substr(0,1).toUpperCase()+c.toLowerCase().substr(1,c.length)})},uppercase_first:function(a){if($m.is.alive(a)===!1)return!1;a.toLowerCase();return a.substr(0,1).toUpperCase()+a.substr(1)},decode_entities:function(a){if($m.is.alive(a)===
!1)return"";var b=document.createElement("div");b.innerHTML=a;return b.firstChild===null||b.firstChild.nodeValue===null?"":b.firstChild.nodeValue},rand_num:function(a){$m.is.alive(a)===!1&&(a=10);for(var b="",c="",d=0;d<a;d++)b=Math.floor(Math.random()*10),c+=b+"";return c}},vd:{name:"visitor_data",browser:!1,version:"?",version_major:"?",screen_height:!1,screen_width:!1,screen_depth:!1,visible_page_height:!1,visible_page_width:!1,scrolled_left:!1,scrolled_top:!1,total_page_height:!1,total_page_width:!1,
cookies_enabled:!1,ua:navigator.userAgent,is_mobile_touch:!1,is_online:!0,match_windows:"Windows",is_windows:!1,match_macintosh:"Macintosh",is_macintosh:!1,match_linux:"Linux",is_linux:!1,match_iphone:"iPhone",is_iphone:!1,match_ipad:"iPad",is_ipad:!1,match_android:"Android",is_android:!1,match_webos:"webOS",is_webos:!1,match_blackberry:"BlackBerry",is_blackberry:!1,match_maemo:"Tablet browser",is_maemo:!1,match_kindle:"Kindle",is_kindle:!1,match_wii:"Nintendo Wii",is_wii:!1,match_trident:"Trident",
is_trident:!1,match_msie:"MSIE",is_msie:!1,is_msie6_or_lower:!1,match_msie6:"MSIE 6",is_msie6:!1,is_msie6_or_lower:!1,match_msie7:"MSIE 7",is_msie7:!1,is_msie7_or_lower:!1,match_msie8:"MSIE 8",is_msie8:!1,is_msie8_or_lower:!1,match_msie9:"MSIE 9",is_msie9_or_lower:!1,is_msie9:!1,match_gecko:"Gecko",is_gecko:!1,match_firefox:"Firefox",is_firefox:!1,match_firefox2:"Firefox/2",is_firefox2:!1,match_firefox3:"Firefox/3",is_firefox3:!1,match_firefox3_5:"Firefox/3.5",is_firefox3_5:!1,match_firefox3_6:"Firefox/3.6",
is_firefox3_6:!1,match_firefox4:"Firefox/4",is_firefox4:!1,match_webkit:"AppleWebKit",is_webkit:!1,match_safari:"Safari",is_safari:!1,match_mobile_safari:"Mobile Safari",is_mobile_touch_safari:!1,match_chrome:"Chrome",is_chrome:!1,match_pre:"Pre/1.0",is_pre:!1,match_opera:"Opera",is_opera:!1,construct:function(){var a="";this.is_online=navigator.onLine&&navigator.onLine===!0?!0:!1;if(this.ua.match(this.match_windows))this.is_windows=!0;if(this.ua.match(this.match_macintosh))this.is_macintosh=!0;if(this.ua.match(this.match_linux))this.is_linux=
!0;if(this.ua.match(this.match_iphone))this.is_mobile_touch=this.is_iphone=!0;if(this.ua.match(this.match_ipad))this.is_mobile_touch=this.is_ipad=!0;if(this.ua.match(this.match_android))this.is_mobile_touch=this.is_android=!0;if(this.ua.match(this.match_webos))this.is_mobile_touch=this.is_webos=!0;if(this.ua.match(this.match_blackberry))this.is_mobile_touch=this.is_blackberry=!0,this.browser=this.match_blackberry;if(this.ua.match(this.match_maemo))this.is_mobile_touch=this.is_maemo=!0,this.browser=
this.match_maemo;if(this.ua.match(this.match_kindle))this.is_mobile_touch=this.is_kindle=!0,this.browser=this.match_kindle;if(this.ua.match(this.match_wii))this.is_mobile_touch=this.is_wii=!0,this.browser=this.match_wii;if((a=this.ua.indexOf("Opera"))!=-1)this.is_opera=!0,this.browser=this.match_opera,this.version=parseFloat(this.ua.substring(a+6)),this.version_major=parseInt(""+this.version);if(this.ua.match(this.match_trident))this.is_trident=!0;if(this.ua.match(this.match_gecko)){this.is_gecko=
!0;this.browser=this.match_gecko;if(this.ua.match(this.match_firefox))this.is_firefox=!0,this.browser=this.match_firefox;if(this.ua.match(this.match_firefox2))this.is_firefox2=!0,this.browser=this.match_firefox2;if(this.ua.match(this.match_firefox3))this.is_firefox3=!0,this.browser=this.match_firefox3;if(this.ua.match(this.match_firefox3_5))this.is_firefox3=!1,this.is_firefox3_5=!0,this.browser=this.match_firefox3_5;if(this.ua.match(this.match_firefox3_6))this.is_firefox3_5=this.is_firefox3=!1,this.is_firefox3_6=
!0,this.browser=this.match_firefox3_6;if(this.ua.match(this.match_firefox4))this.is_firefox4=!0,this.browser=this.match_firefox4}if(this.ua.match(this.match_webkit)){this.is_gecko=!1;this.is_webkit=!0;this.browser=this.match_webkit;if(this.ua.match(this.match_safari))this.is_safari=!0,this.browser=this.match_safari;if(this.ua.match(this.match_mobile_safari))this.is_safari=!1,this.is_mobile_touch=!0,this.browser=this.match_mobile_safari;if(this.ua.match(this.match_chrome))this.is_safari=!1,this.is_chrome=
!0,this.browser=this.match_chrome;if(this.ua.match(this.match_pre))this.is_safari=!1,this.is_mobile_touch=this.is_pre=!0,this.browser=this.match_pre}if((a=this.ua.indexOf("MSIE"))!=-1){this.is_msie=!0;this.is_msie9_or_lower=this.is_msie8_or_lower=this.is_msie7_or_lower=this.is_msie6_or_lower=!1;this.browser=this.match_msie;this.version=parseFloat(this.ua.substring(a+5));this.version_major=parseInt(""+this.version);if(this.ua.match(this.match_msie6))this.is_msie6=this.is_msie7_or_lower=this.is_msie8_or_lower=
this.is_msie9_or_lower=!0,this.browser=this.match_msie6;if(this.ua.match(this.match_msie7))this.is_msie7_or_lower=this.is_msie7=this.is_msie8_or_lower=this.is_msie9_or_lower=!0,this.browser=this.match_msie7;if(this.ua.match(this.match_msie8))this.is_msie8_or_lower=this.is_msie8=this.is_msie9_or_lower=!0,this.browser=this.match_msie8;if(this.ua.match(this.match_msie9))this.is_msie9_or_lower=this.is_msie9=!0,this.browser=this.match_msie8;$m.fix_msie()}if("ontouchstart"in document.documentElement)this.is_mobile_touch=
!0;this.screen_height=screen.height;this.screen_width=screen.width;this.screen_depth=screen.colorDepth;this.cookies_enabled=navigator.cookieEnabled},get_view_port:function(){$m.vd.visible_page_height=document.documentElement&&document.documentElement.clientHeight||window.innerHeight||self.innerHeight||document.body.clientHeight;$m.vd.visible_page_width=document.documentElement&&document.documentElement.clientWidth||window.innerWidth||self.innerWidth||document.body.clientWidth;$m.vd.scrolled_left=
document.documentElement&&document.documentElement.scrollLeft||window.pageXOffset||self.pageXOffset||document.body.scrollLeft;$m.vd.scrolled_top=document.documentElement&&document.documentElement.scrollTop||window.pageYOffset||self.pageYOffset||document.body.scrollTop;$m.vd.total_page_height=document.documentElement&&document.documentElement.scrollHeight?document.documentElement.scrollHeight:document.body.scrollHeight>document.body.offsetHeight?document.body.scrollHeight:document.body.offsetHeight;
$m.vd.total_page_width=document.documentElement&&document.documentElement.scrollWidth?document.documentElement.scrollWidth:document.body.scrollWidth>document.body.offsetWidth?document.body.scrollWidth:document.body.offsetWidth}},when_ready:function(){document.addEventListener&&document.addEventListener("DOMContentLoaded",$m.execute,!1);$m.win.bind("load",function(){$m.execute()})},win:{bind:function(a,b){var c="on"+a,d=window[c];window[c]=typeof window[c]=="function"?function(a){d(a);b(a)}:b}}};
Function.prototype.trace=function(){for(var a=[],b="<ul>",c=this,d="";c;)d=((new Date).getTime()-$m.timer)/1E3+"",d.length==3?d+="00":d.length==4&&(d+="0"),a.push(d+" | "+c.signature()),c=c.caller;a.shift();c=0;for(d=a.length;c<d;c++)b+="<li>"+a[c]+"</li>";b+="</ul>";return b};
Function.prototype.signature=function(){var a={name:this.getName(),params:[],toString:function(){return this.name+"("+(this.params.length>0?"'"+this.params.join("', '")+"'":"")+")"}};if(this.arguments)for(var b=0,c=this.arguments.length;b<c;b++)a.params.push(this.arguments[b]);return a};Function.prototype.getName=function(){if(this.name)return this.name;var a=this.toString().split("\n")[0],b=/^function ([^\s(]+).+/;if(b.test(a))return a.split("\n")[0].replace(b,"$1")||"anonymous";return"anonymous"};
$m.when_ready();
