/***************************************************************************
- File: wand.js - Let's use the wand
- Version: 14.7.14
***************************************************************************/

$m.h.add_commas={name:"add_commas",data_att:"add_commas",timeout:!1,construct:function(){var a=$m.attr.get_fields_with("document",["text","textarea"],$m.data_att,this.data_att);$m.elements.bind(a,this.data_att,"keyup",this.exec);$m.elements.bind(a,this.data_att,"change",this.exec)},exec:function(a){var b=$m.id(a);clearTimeout($m.h.add_commas.timeout);if($m.is.alive(b.value)===!0)$m.h.add_commas.timeout=setTimeout(function(){b.value=$m.ut.add_commas(b.value)},750)}};
$m.h.ajax_click={name:"ajax_click",data_att:"ajax_click",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){var b=new $m.ajax;b.init(a);b.exec()}};
$m.h.ajax_field_submit_click={name:"ajax_field_submit_click",data_att:"ajax_field_submit_click",data_att_group:"data-mjf_afsc",allowed_fields:["text","password","file","textarea","select","radio","checkbox"],timer:!1,construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){var b=new $m.ajax,c=$m.attr.get(a,$m.h.ajax_field_submit_click.data_att_group),d=[];b.init(a);d=$m.attr.get_fields_with($m.body_id,$m.h.ajax_field_submit_click.allowed_fields,$m.h.ajax_field_submit_click.data_att_group,
c);a=0;for(c=d.length;a<c;a++)if($m.tag.get_name(d[a])=="select"){d[a]=d[a];for(var e=0,f=d[a].length;e<f;e++)d[a][e].selected===!0&&(b.config.query+="&"+$m.attr.get(d[a],"name")+"="+encodeURIComponent(d[a][e].value))}else(d[a].type=="radio"||d[a].type=="checkbox")&&d[a].checked===!0?b.config.query+="&"+$m.attr.get(d[a],"name")+"="+encodeURIComponent(d[a].value):(d[a].type=="radio"||d[a].type=="checkbox")&&d[a].checked!==!0||(b.config.query+="&"+$m.attr.get(d[a],"name")+"="+encodeURIComponent(d[a].value));
b.method="post";b.exec();if(b.request.errord===!0)return clearTimeout($m.h.ajax_field_submit_click.timer),!1}};
$m.h.ajax_field_submit_kc={name:"ajax_field_submit_kc",data_att:"ajax_field_submit_kc",data_att_group:"data-mjf_afskc",allowed_simple_fields:["text","password","file","textarea","select"],allowed_checked_fields:["radio","checkbox"],allowed_all_fields:[],timer:!1,construct:function(){var a=$m.attr.get_fields_with($m.body_id,this.allowed_simple_fields,$m.data_att,this.data_att);$m.elements.bind(a,this.data_att,"keyup",this.init);$m.elements.bind(a,this.data_att,"change",this.init);a=$m.attr.get_fields_with($m.body_id,
this.allowed_checked_fields,$m.data_att,this.data_att);$m.elements.bind(a,this.data_att,"click",this.exec);this.allowed_all_fields=this.allowed_simple_fields.concat(this.allowed_checked_fields)},init:function(a,b){clearTimeout($m.h.ajax_field_submit_kc.timer);if($m.keycode.is_worthy($m.keycode.get(b))===!0||$m.tag.get_name(a)=="select")$m.h.ajax_field_submit_kc.timer=setTimeout(function(){$m.h.ajax_field_submit_kc.exec(a)},750)},exec:function(a){var b=new $m.ajax,c=$m.attr.get(a,$m.h.ajax_field_submit_kc.data_att_group),
d=[];b.init(a);$m.is.alive(c)===!0?d=$m.attr.get_fields_with($m.body_id,$m.h.ajax_field_submit_kc.allowed_all_fields,$m.h.ajax_field_submit_kc.data_att_group,c):d.push($m.id(a));a=0;for(c=d.length;a<c;a++)if($m.tag.get_name(d[a])=="select"){d[a]=d[a];for(var e=0,f=d[a].length;e<f;e++)d[a][e].selected===!0&&(b.config.query+="&"+$m.attr.get(d[a],"name")+"="+encodeURIComponent(d[a][e].value))}else(d[a].type=="radio"||d[a].type=="checkbox")&&d[a].checked===!0?b.config.query+="&"+$m.attr.get(d[a],"name")+
"="+encodeURIComponent(d[a].value):(d[a].type=="radio"||d[a].type=="checkbox")&&d[a].checked!==!0||(b.config.query+="&"+$m.attr.get(d[a],"name")+"="+encodeURIComponent(d[a].value));b.method="post";b.exec();if(b.request.errord===!0)return clearTimeout($m.h.ajax_field_submit_kc.timer),!1}};
$m.h.ajax_change={name:"ajax_change",data_att:"ajax_change",timer:!1,construct:function(){var a=$m.attr.get_fields_with($m.body_id,["text","password","file","textarea","select"],$m.data_att,this.data_att);$m.elements.bind(a,this.data_att,"change",this.exec)},exec:function(a){clearTimeout($m.h.ajax_change.timer);$m.h.ajax_change.timer=setTimeout(function(){var b=new $m.ajax;b.init(a);b.config.query+="&"+$m.attr.get(a,"name")+"="+encodeURIComponent($m.id(a).value);b.exec();if(b.request.errord===!0)return clearTimeout($m.h.ajax_change.timer),
!1},750)}};
$m.h.ajax_kc={name:"ajax_kc",data_att:"ajax_kc",timer:!1,construct:function(){var a=$m.attr.get_fields_with($m.body_id,["text","password","file","textarea","select"],$m.data_att,this.data_att);$m.elements.bind(a,this.data_att,"keyup",this.exec);$m.elements.bind(a,this.data_att,"change",this.exec)},exec:function(a,b){clearTimeout($m.h.ajax_kc.timer);if($m.keycode.is_worthy($m.keycode.get(b))===!0||$m.tag.get_name(a)=="select")$m.h.ajax_kc.timer=setTimeout(function(){var b=new $m.ajax;b.init(a);b.config.query+=
"&"+$m.attr.get(a,"name")+"="+encodeURIComponent($m.id(a).value);b.exec();if(b.request.errord===!0)return clearTimeout($m.h.ajax_kc.timer),!1},750)}};$m.h.ajax_onload={construct:function(a){if($m.is.alive(a.element_id)===!1)$m.de.throw_browser_error("$m.wand.ajax_onload.element_id is required.");else if($m.is.alive(a.url)===!1)$m.de.throw_browser_error("$m.wand.ajax_onload.url is required.");else if($m.ajax_init===!1){var b=new $m.ajax;b.init(a);b.exec()}}};
$m.h.ajax_polling={running_polls:[],timer:!1,construct:function(a){if($m.is.alive(a.element_id)===!1)$m.de.throw_browser_error("$m.wand.ajax_polling.element_id is required.");else if($m.is.alive(a.interval)===!1)$m.de.throw_browser_error("$m.wand.ajax_polling.interval is required.");else if($m.is.alive(a.url)===!1)$m.de.throw_browser_error("$m.wand.ajax_polling.url is required.");else if($m.is.in_array(this.running_polls,a.element_id)===!1){this.running_polls.push(a.element_id);var b=new $m.ajax;
b.init(a);b.delete_xhttp=!1;setInterval(function(){b.exec();if(b.request.errord===!0)return clearTimeout($m.h.ajax_polling.timer),!1},a.interval*1E3)}}};$m.h.ajax_submit={name:"ajax_submit",data_att:"ajax_submit",construct:function(){$m.elements.bind($m.tags.form,this.data_att,"submit",this.exec)},exec:function(a,b,c){b=new $m.ajax;b.init(a);b.config.method=$m.attr.get(a,"method");b.config.url=$m.is.alive(c)===!0?c:$m.attr.get(a,"action");b.exec();if(b.request.errord===!0)return!1}};
$m.h.ajax_submit_kc={name:"ajax_submit_kc",data_att:"ajax_submit_kc",timer:!1,construct:function(){var a=$m.attr.get_fields_with($m.body_id,["text","password","file","textarea","select"],$m.data_att,this.data_att);$m.elements.bind(a,this.data_att,"keyup",this.exec);$m.elements.bind(a,this.data_att,"change",this.exec)},exec:function(a,b){clearTimeout($m.h.ajax_submit_kc.timer);if($m.keycode.is_worthy($m.keycode.get(b))===!0||$m.tag.get_name(a)=="select")$m.h.ajax_submit_kc.timer=setTimeout(function(){new $m.ajax;
var c=$m.attr.get(a,"data-mjf_askc_form_id");$m.id(c);var d=$m.attr.get(a,"data-mjf_askc_action"),d=$m.is.alive(d)?d:$m.attr.get(c,"action");if($m.is.alive(d)===!1)return $m.de.throw_browser_error("$m.h.ajax_submit_kc.exec() -- could not determine the form action"),!1;$m.is.alive($m.h.form_required.valid_forms[c])===!0?$m.h.form_required.exec(c)===!0&&$m.h.ajax_submit.exec(c,b,d):$m.h.ajax_submit.exec(c,b,d)},750)}};
$m.h.ajax_submit_link={name:"ajax_submit_link",data_att:"ajax_submit_link",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a,b){var c=$m.attr.get(a,"data-mjf_asl_form_id");$m.id(c);var d=$m.attr.get(a,"data-mjf_asl_action"),e=$m.attr.get(a,"data-mjf_asl_name_value"),d=$m.is.alive(d)?d:$m.attr.get(c,"action");if($m.is.alive(d)===!1)return $m.de.throw_browser_error("$m.h.ajax_submit_link.exec() -- could not determine the form action"),!1;$m.tag.get_name(a)==
"a"&&$m.id(a).blur();$m.is.alive(e)===!0&&(d+=d.indexOf("?")==-1?"?":"&",d+=e);$m.is.alive($m.h.form_required.valid_forms[c])===!0?$m.h.form_required.exec(c)===!0&&$m.h.ajax_submit.exec(c,b,d):$m.h.ajax_submit.exec(c,b,d)}};
$m.h.ajax_unload={construct:function(a){$m.is.alive(a.element_id)===!1?$m.de.throw_browser_error("$m.wand.ajax_unload.element_id is required."):$m.is.alive(a.url)===!1?$m.de.throw_browser_error("$m.wand.ajax_unload.url is required."):$m.win.bind("beforeunload",function(){if($m.is.alive(a.update_id)===!1)a.update_id=$m.body_id;var b=new $m.ajax;b.init(a);b.exec()})}};
$m.h.change_field_type={name:"change_field_type",data_att:"change_field_type",data_att_cft:"data-mjf_cft",data_att_cft_clear:"data-mjf_cft_clear",construct:function(){$m.elements.bind($m.tags.get($m.document,"input"),this.data_att,"focus",this.exec)},exec:function(a){var b=$m.id(a),c=$m.attr.get_all(b),d=$m.attr.get(a,$m.h.change_field_type.data_att_cft_clear);c.type=$m.attr.get(a,$m.h.change_field_type.data_att_cft);b.onfocus=null;if(d!==!1)c.value="";b.parentNode.insertBefore($m.tag.init("input",
c),b.nextSibling).focus();b.parentNode.removeChild(b)}};
$m.h.check_all_boxes={name:"check_all_boxes",data_att:"check_all_boxes",checkall_att:"data-mjf_checkall",construct:function(){for(var a=[],b=[],c=0,d=$m.tags.form.length;c<d;c++)a=$m.attr.get_fields_with($m.tags.form[c],["checkbox"],$m.data_att,this.data_att),b=b.concat(a);$m.elements.bind(b,this.data_att,"click",this.exec)},exec:function(a){for(var b=[],c=[],d=$m.id(a).checked===!0?!0:!1,e=0,f=$m.tags.form.length;e<f;e++)b=$m.attr.get_fields_with($m.tags.form[e],["checkbox"],$m.h.check_all_boxes.checkall_att,
a),c=c.concat(b);e=0;for(a=c.length;e<a;e++)if(c[e].disabled===!1)c[e].checked=d===!1?!0:!1,c[e].click()}};
$m.h.check_other_onfocus={name:"check_other_onfocus",data_att:"check_other_onfocus",check_other_onfocus_id_att:"data-mjf_check_other_onfocus_id",construct:function(){for(var a=[],b=[],c=0,d=$m.tags.form.length;c<d;c++)a=$m.attr.get_fields_with($m.tags.form[c],["text","password","textarea","file","select"],$m.data_att,this.data_att),b=b.concat(a);$m.elements.bind(b,this.data_att,"focus",this.exec)},exec:function(a){$m.id($m.attr.get(a,$m.h.check_other_onfocus.check_other_onfocus_id_att)).checked=!0}};
$m.h.checked_picker={name:"checked_picker",data_att:"checked_picker",data_att_grp:"data-mjf_checked_picker_group",data_att_lbl:"data-mjf_checked_picker_label",check_sets:{},timer:"",delay:150,construct:function(){if($m.vd.is_mobile_touch!==!0){for(var a=$m.attr.get_tags_with($m.tags.get($m.document,"input"),$m.data_att,this.data_att),b="",c=0,d=a.length;c<d;c++)$m.attr.get(a[c],"type")=="checkbox"&&(tmp_check_grp=$m.attr.get(a[c],this.data_att_grp),$m.ajax_init===!0&&$m.is.object(this.check_sets[tmp_check_grp])===
!0&&(this.check_sets[tmp_check_grp]={}));c=0;for(d=a.length;c<d;c++)$m.attr.get(a[c],"type")=="checkbox"&&(tmp_check_grp=$m.attr.get(a[c],this.data_att_grp),tmp_check_id=$m.attr.get(a[c],"id"),$m.is.object(this.check_sets[tmp_check_grp])===!1&&(this.check_sets[tmp_check_grp]={}),b=$m.attr.get(a[c],this.data_att_lbl),this.check_sets[tmp_check_grp][tmp_check_id]={state:a[c].checked===!0?!0:!1,label:b,text:$m.tags.strip.from_id(b).toLowerCase(),display:"block"});$m.elements.bind($m.tags.get($m.document,
"input"),this.data_att,"click",this.exec)}},exec:function(a){var b=$m.id(a),c=$m.attr.get(a,$m.h.checked_picker.data_att_grp),d=$m.attr.get(a,$m.h.checked_picker.data_att_lbl),e="",f="";(b.checked===!0?!1:!0)===!0?(f=$m.id("checked_picker_list_"+c+"_off"),e=!1):(f=$m.id("checked_picker_list_"+c+"_on"),e=!0);b.checked=e;$m.h.checked_picker.check_sets[c][a].state=e;setTimeout(function(){var a=$m.tag.remove(d);f.appendChild(a)},$m.h.checked_picker.delay)},test:function(a){clearTimeout($m.h.checked_picker.timer);
return $m.get_keycode(a)==13?!1:!0},search:function(a,b){clearTimeout($m.h.checked_picker.timer);$m.h.checked_picker.timer=setTimeout(function(){$m.h.checked_picker.filter(a,b)},750)},filter:function(a,b){var c="";query=b.toLowerCase();for(var d in $m.h.checked_picker.check_sets[a])c=$m.h.checked_picker.check_sets[a][d].text.indexOf(query)==-1?"none":"block",$m.h.checked_picker.check_sets[a][d].display=c,$m.id($m.h.checked_picker.check_sets[a][d].label).style.display=c},clear:function(a){$m.id(a+
"_search").value="";$m.h.checked_picker.filter(a,"")},toggle_all:function(a,b){$m.h.checked_picker.delay=0;var c="",d="";id_string="checked_picker_list_"+a;b===!0?(c=!1,d=!0,id_string+="_off"):(c=!0,d=!1,id_string+="_on");for(var e in $m.h.checked_picker.check_sets[a])if($m.h.checked_picker.check_sets[a][e].state==c&&$m.h.checked_picker.check_sets[a][e].display=="block")$m.id(e).checked=d,$m.h.checked_picker.exec(e);$m.h.checked_picker.delay=150}};
$m.h.clear_onclick={name:"clear_onclick",data_att:"clear_onclick",data_att_form:"data-mjf_coc_form",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){var b=$m.attr.get(a,$m.h.clear_onclick.data_att_form);$m.id(b);for(var c="",d=$m.tags.get(b,"input"),a=0,e=d.length;a<e;a++)if(c=$m.attr.get(d[a],"type"),c=="checkbox"||c=="radio")d[a].checked=!1;else if(!(c=="submit"||c=="reset"||c=="button"))d[a].value="";c=$m.tags.get(b,"textarea");a=0;for(d=c.length;a<
d;a++)c[a].value="";b=$m.tags.get(b,"select");a=0;for(c=b.length;a<c;a++)b[a].selectedIndex=-1}};
$m.h.clear_onfocus={name:"clear_onfocus",data_att:"clear_onfocus",construct:function(){for(var a=[],b=[],c=0,d=$m.tags.form.length;c<d;c++)a=$m.attr.get_fields_with($m.tags.form[c],["text","password","textarea"],$m.data_att,this.data_att),b=b.concat(a);$m.elements.bind(b,this.data_att,"focus",this.do_focus);$m.elements.bind(b,this.data_att,"blur",this.do_blur)},do_blur:function(a){a=$m.id(a);if($m.is.alive(a.value)===!1)a.value=a.defaultValue},do_focus:function(a){a=$m.id(a);if(a.defaultValue==a.value)a.value=
""}};$m.h.clear_onload={name:"clear_onload",data_att:"clear_onload",construct:function(){setTimeout(function(){for(var a=$m.attr.get_fields_with($m.body_id,["text","password","textarea"],$m.data_att,$m.h.clear_onload.data_att),b=0,c=a.length;b<c;b++)a[b].value=""},500)}};
$m.h.deferred_load={name:"deferred_load",data_att:"deferred_load",data_att_src:"data-mjf_deferred_load_src",construct:function(){for(var a=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),b="",c="",d=0,e=a.length;d<e;d++){b=$m.tag.get_name(a[d]);c=$m.attr.get(a[d],this.data_att_src);if($m.is.alive(c)===!1)return $m.de.throw_browser_error("Deferred Load: Missing data-mjf_deferred_load_src attribute for $m.h.deferred_load.construct() -- "+a[d]),!1;if(b=="img"||b=="iframe")a[d].src=c}}};
$m.h.click_enable_disable={name:"click_enable",data_att:"click_enable_disable",data_att_enable_id:"data-mjf_click_enable_id",data_att_disable_id:"data-mjf_click_disable_id",data_att_enable_disable_id:"data-mjf_click_enable_disable_id",data_att_enable_group:"data-mjf_click_enable_group",data_att_disable_group:"data-mjf_click_disable_group",data_att_enable_disable_group:"data-mjf_click_enable_disable_group",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){var b=
$m.attr.get(a,$m.h.click_enable_disable.data_att_enable_id),c=$m.attr.get(a,$m.h.click_enable_disable.data_att_disable_id),d=$m.attr.get(a,$m.h.click_enable_disable.data_att_enable_disable_id),e=$m.attr.get(a,$m.h.click_enable_disable.data_att_enable_group),f=$m.attr.get(a,$m.h.click_enable_disable.data_att_disable_group),g=$m.attr.get(a,$m.h.click_enable_disable.data_att_enable_disable_group),h=["text","password","textarea","file","select","radio","checkbox"];if($m.is.alive(b)===!0)$m.id(b).disabled=
!1;else if($m.is.alive(c)===!0)$m.id(c).disabled=!0;else if($m.is.alive(d)===!0)$m.id(a).checked===!0?$m.id(d).disabled=!1:$m.id(d).disabled=!0;else if($m.is.alive(e)===!0){b=$m.attr.get_fields_with($m.body_id,h,$m.h.click_enable_disable.data_att_enable_group,e);a=0;for(c=b.length;a<c;a++)if($m.attr.get(b[a],$m.data_att)!==$m.h.click_enable_disable.data_att)$m.id(b[a]).disabled=!1}else if($m.is.alive(f)===!0){b=$m.attr.get_fields_with($m.body_id,h,$m.h.click_enable_disable.data_att_disable_group,
f);a=0;for(c=b.length;a<c;a++)if($m.attr.get(b[a],$m.data_att)!==$m.h.click_enable_disable.data_att)$m.id(b[a]).disabled=!0}else if($m.is.alive(g)===!0){b=$m.attr.get_fields_with($m.body_id,h,$m.h.click_enable_disable.data_att_enable_disable_group,g);d=$m.id(a).checked===!0?!1:!0;a=0;for(c=b.length;a<c;a++)if($m.attr.get(b[a],$m.data_att)!==$m.h.click_enable_disable.data_att)$m.id(b[a]).disabled=d}}};
$m.h.confirm_click={name:"confirm_click",data_att:"confirm_click",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){return confirm($m.id(a).title)}};$m.h.confirm_unload={name:"confirm_unload",construct:function(a){if($m.is.alive($m.lang.core)===!1)$m.lang.core.msgs.navigate_away.general="";var b=$m.is.string(a)===!0?a:$m.lang.core.msgs.navigate_away.general;$m.win.bind("beforeunload",function(a){if(a=a||window.event)a.returnValue=b;return b})}};
$m.h.copy_fields={name:"copy_fields",data_att:"copy_fields",data_att_on:"data-mjf_cf_on",data_att_master:"data-mjf_cf_master",data_att_slaves:"data-mjf_cf_slaves",data_att_slave:"data-mjf_cf_slave",data_att_m2s:"data-mjf_cf_m2s",data_att_m2slave:"data-mjf_cf_m2slave",data_att_only_empty:"data-mjf_cf_only_empty",timeout:!1,construct:function(){for(var a=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),b=0,c=a.length;b<c;b++)$m.elements.bind(a[b],this.data_att,$m.attr.get(a[b],this.data_att_on),
this.exec)},exec:function(a){var b=$m.id(a),c="",d=!1,e=$m.attr.get(a,$m.h.copy_fields.data_att_master),f=$m.is.alive(e)===!0?$m.id(e):!1,g=$m.attr.get(a,$m.h.copy_fields.data_att_slave),h=$m.attr.get(a,$m.h.copy_fields.data_att_m2s),i="";$m.tag.get_name(a)=="input"&&$m.attr.get(a,"type")=="checkbox"&&b.checked===!1&&(d=!0);clearTimeout($m.h.copy_fields.timeout);$m.h.copy_fields.timeout=setTimeout(function(){if($m.is.alive(g)===!0){if(i=$m.attr.get(g,$m.h.copy_fields.data_att_only_empty),!(i=="true"&&
$m.is.alive($m.id(g).value)===!0))d===!0?$m.id(g).value="":$m.id(g).value=$m.tag.get_name(a)=="select"?f[f.selectedIndex].value:f.value}else if($m.is.alive(h)===!0)for(var l=$m.attr.get_tags_with($m.tags.all,$m.h.copy_fields.data_att_m2s,h),k="",j=k="",m=0,n=l.length;m<n;m++){if(k=$m.attr.get(l[m],"id"),a!=k&&(k=$m.id(k),j=$m.attr.get(k,$m.h.copy_fields.data_att_m2slave),i=$m.attr.get(j,$m.h.copy_fields.data_att_only_empty),!(i=="true"&&$m.is.alive($m.id(j).value)===!0)))$m.id(j).value=d===!0?"":
k.value}else{l=$m.attr.get(a,$m.h.copy_fields.data_att_slaves);l=$m.attr.get_tags_with($m.tags.all,$m.h.copy_fields.data_att_slaves,l);m=0;for(n=l.length;m<n;m++)if(i=$m.attr.get(l[m],$m.h.copy_fields.data_att_only_empty),!(i=="true"&&$m.is.alive(l[m].value)===!0))c=$m.attr.get(l[m],"id"),d===!0&&e!=c?$m.id(c).value="":f===!1?$m.id(c).value=$m.tag.get_name(a)=="select"?b[b.selectedIndex].value:b.value:$m.id(c).value=f.value}},1E3)}};
$m.h.copy_value_to_html={name:"copy_value_to_html",data_att:"copy_value_to_html",construct:function(){var a=$m.attr.get_fields_with("document",["text","textarea"],$m.data_att,this.data_att);$m.elements.bind(a,this.data_att,"keyup",this.exec);$m.elements.bind(a,this.data_att,"change",this.exec)},exec:function(a){$m.id($m.attr.get(a,"data-mjf_cvth_id")).innerHTML=$m.id(a).value}};
$m.h.css_class_update={name:"css_class_update",data_att:"css_class_update",data_att_ccu_id:"data-mjf_ccu_id",data_att_ccu_exec:"data-mjf_ccu_exec",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){var b=$m.attr.get(a,$m.h.css_class_update.data_att_ccu_id),c=$m.attr.get(a,$m.h.css_class_update.data_att_ccu_exec),d=c.match(/\((.+?)\)/);$m.is.alive(d[0])===!0&&($m.tag.get_name(a)=="a"&&$m.id(a).blur(),d=d[0].replace(/\(|\)|\s/g,""),c.indexOf("add")===
0?$m.css_class.add(b,d):c.indexOf("replace")===0?(a=d.split(","),$m.css_class.replace(b,a[0],a[1])):c.indexOf("remove")===0&&$m.css_class.remove(b,d))}};
$m.h.dropdown_menu={name:"dropdown_menu",data_att:"dropdown_menu",uls_tag:{},lis:[],timeout:!1,timeout_setting:!1,construct:function(){var a=$m.attr.get_tags_with($m.tags.get($m.document,"ul"),$m.data_att,this.data_att),b=[],c="",d="";this.uls_tag={};this.lis=[];for(var e=0,f=a.length;e<f;e++)for(var b=$m.tags.get($m.attr.get(a[e],"id"),"li"),g=0,h=b.length;g<h;g++)c=$m.attr.get(b[g],"id"),this.lis.push(c),$m.is.alive(c)===!0&&(d=$m.tags.get(c,"ul"),d[0]!==void 0&&(this.uls_tag[c]=d[0],tmp_lis_id_obj=
$m.id(c),$m.attr.set(tmp_lis_id_obj,{"class":"ddm_li_off","data-mjf_ddm":"off"}),$m.vd.is_mobile_touch===!0?tmp_lis_id_obj.setAttribute("onclick","$m.h.dropdown_menu.show('"+c+"')"):(tmp_lis_id_obj.setAttribute("onmouseover","$m.h.dropdown_menu.show('"+c+"')"),tmp_lis_id_obj.setAttribute("onmouseout","$m.h.dropdown_menu.hide('"+c+"')"))));$m.element.attach($m.body_id,"touchstart",this.hide_all)},show:function(a){clearTimeout($m.h.dropdown_menu.timeout);var b=$m.id(a),c=$m.attr.get(a,"data-mjf_ddm"),
d;for(d in $m.h.dropdown_menu.uls_tag)$m.attr.set(d,{"class":"ddm_li_off"}),$m.attr.set($m.h.dropdown_menu.uls_tag[d],{"class":""});$m.vd.is_mobile_touch===!0?c=="off"?($m.attr.set($m.h.dropdown_menu.uls_tag[a],{"class":"ddm_ul_on"}),$m.attr.set(b,{"class":"ddm_li_on","data-mjf_ddm":"on"})):($m.attr.set($m.h.dropdown_menu.uls_tag[a],{"class":""}),$m.attr.set(b,{"class":"ddm_li_off","data-mjf_ddm":"off"})):($m.attr.set(b,{"class":"ddm_li_on"}),$m.attr.set($m.h.dropdown_menu.uls_tag[a],{"class":"ddm_ul_on"}))},
hide:function(a){var b=$m.is.good_string(a)===!0?a:this.id;$m.h.dropdown_menu.timeout=setTimeout(function(){$m.attr.set(b,{"class":"ddm_li_off"});$m.attr.set(b,{"data-mjf_ddm":"off"});$m.attr.set($m.h.dropdown_menu.uls_tag[b],{"class":""})},400)},hide_all:function(){for(var a=0,b=$m.h.dropdown_menu.lis.length;a<b;a++)$m.h.dropdown_menu.hide($m.h.dropdown_menu.lis[a])}};
$m.h.dynamic_tabs={name:"dynamic_tabs",data_att:"dynamic_tabs",dtabs:{},dtab_anchors_id:[],dtab_anchors:[],dtab_groups:[],construct:function(a){var b=$m.attr.get_tags_with($m.tags.a,$m.data_att,this.data_att),c=[],d="",e="",e=!1,f=$m.storage.get.table($m.storage.db_wand+"dynamic_tabs"),e=!1;this.dtab_anchors_id=[];this.dtab_anchors=[];this.dtab_groups=[];for(var d=0,g=b.length;d<g;d++)$m.attr.get(b[d],"data-mjf_dtab_set")!==null&&(e=$m.attr.get(b[d],"data-mjf_dtab_set"),$m.is.array(this.dtab_anchors[e])!==
!0&&(this.dtab_anchors[e]=[]),this.dtab_anchors[e].push($m.attr.get(b[d],"id")),c.push(b[d]),this.dtab_anchors_id.push($m.attr.get(b[d],"id")));if($m.is.array(a)===!0)for(var e=b=!1,h=0,d=a.length;h<d;h++)$m.is.alive(a[h].name)!==!1&&(b=$m.is.alive(a[h].autostart)===!0?a[h].autostart:!1,e=$m.is.alive(a[h].delay)===!0?a[h].delay:0,this.dtabs[a[h].name]={autostart:b,delay:e*1E3,timeout:!1,ids:this.dtab_anchors[a[h].name]});a=0;for(b=this.dtab_anchors_id.length;a<b;a++)e=$m.attr.get(this.dtab_anchors_id[a],
"data-mjf_dtab_shct"),e!==null&&$m.shortcut.bind(e,"$m.h.dynamic_tabs.exec('"+this.dtab_anchors_id[a]+"');");$m.elements.bind(c,this.data_att,"click",this.exec);c=0;for(a=$m.tags.all.length;c<a;c++)$m.attr.has_value($m.tags.all[c],$m.data_att,this.data_att)||(d=$m.attr.get($m.tags.all[c],"id"),d!==null&&$m.attr.get($m.tags.all[c],"data-mjf_dtab_set")!==null&&($m.animate.css.opacity(d),$m.css_class.has(d,"display_block")===!1&&$m.css_class.add(d,"mjf_hide"),e=$m.attr.get($m.tags.all[c],"data-mjf_dtab_set"),
$m.is.array(this.dtab_groups[e])!==!0&&(this.dtab_groups[e]=[]),this.dtab_groups[e].push(d)));if($m.is.alive(window.location.hash)&&(c=window.location.hash.replace(/^#/,""),$m.id(c)&&$m.is.in_array(this.dtab_anchors_id,c)!==!1))this.exec(c),window.location="#";if($m.is.alive(f)===!0)for(h in c=b="",a=$m.ut.friendly_url(window.location),f){b=$m.storage.get.page_tiny_id(h);c=$m.storage.get.page_code(h);if($m.is.alive(this.dtabs[b])===!0&&$m.is.alive(this.dtabs[b].autostart)===!0)this.dtabs[b].autostart=
!1;e=$m.id(f[h].id);$m.is.alive(e)===!0&&a==c&&this.exec(f[h].id)}for(h in this.dtabs)this.dtabs[h].autostart===!0&&this.cycle(h,0)},exec:function(a,b){var c=$m.id(a),d="",e=$m.attr.get(a,"data-mjf_ga_track"),f=$m.attr.get(a,"data-mjf_dtab_set");$m.is.alive(b)===!0&&$m.is.alive($m.h.dynamic_tabs.dtabs[f])===!0&&clearTimeout($m.h.dynamic_tabs.dtabs[f].timeout);if($m.is.alive($m.h.dynamic_tabs.dtabs[f])===!0)for(var g=0,d=$m.h.dynamic_tabs.dtabs[f].ids.length;g<d;g++)$m.css_class.remove($m.h.dynamic_tabs.dtabs[f].ids[g],
"tab_link_active");else{g=0;for(d=$m.h.dynamic_tabs.dtab_anchors[f].length;g<d;g++)$m.css_class.remove($m.h.dynamic_tabs.dtab_anchors[f][g],"tab_link_active")}$m.css_class.add(c,"tab_link_active");c.blur();g=0;for(c=$m.h.dynamic_tabs.dtab_groups[f].length;g<c;g++)d=$m.h.dynamic_tabs.dtab_groups[f][g],$m.css_class.has(d,"mjf_hide")===!1&&$m.css_class.add(d,"mjf_hide"),$m.css_class.remove(d,"display_block");g=$m.attr.get(a,"data-mjf_dtab_id");$m.css_class.replace(g,"mjf_hide","display_block");$m.attr.get(a,
"data-mjf_dtab_cookie")===!1||$m.attr.get(a,"data-mjf_dtab_cookie")!="false"?$m.storage.set($m.storage.db_wand+"dynamic_tabs",$m.storage.create.data_record(f,"id",a)):$m.storage.remove($m.storage.db_wand+"dynamic_tabs",f);e!==null&&$m.track.ga({category:"MJF Dynamic Tabs",action:a+" Click",label:g})},cycle:function(a,b){$m.h.dynamic_tabs.dtabs[a].timeout=setTimeout(function(){$m.h.dynamic_tabs.exec($m.h.dynamic_tabs.dtabs[a].ids[b]);b++;b>=$m.h.dynamic_tabs.dtabs[a].ids.length&&(b=0);$m.h.dynamic_tabs.cycle(a,
b)},$m.h.dynamic_tabs.dtabs[a].delay)}};
$m.h.elastic_textareas={name:"elastic_textareas",data_att:"elastic_textareas",data_att_max_h:"data-mjf_elastic_textareas_max_height",is_resizing:!1,resize_timer:!1,construct:function(){for(var a=$m.attr.get_fields_with("document",["textarea"],$m.data_att,this.data_att),b="",c=0,d=a.length;c<d;c++)b=$m.attr.get(a[c],"id"),$m.style.set(b,{overflow:"hidden"}),$m.style.set(b,{resize:"none"}),$m.h.elastic_textareas.exec(b);$m.elements.bind(a,this.data_att,"keyup",this.test);$m.elements.bind(a,this.data_att,
"change",this.exec);$m.win.bind("resize",function(){$m.h.elastic_textareas.resize_all()})},resize_all:function(){clearTimeout($m.h.elastic_textareas.resize_timer);$m.h.elastic_textareas.resize_timer=setTimeout(function(){$m.h.elastic_textareas.construct()},500)},test:function(a,b){var c=$m.keycode.get(b);c>=37&&c<=40||c>=16&&c<=18||$m.h.elastic_textareas.exec(a)},exec:function(a){var b=$m.id(a),c=$m.attr.get(a,$m.h.elastic_textareas.exec.data_att_max_h);$m.vd.get_view_port();$m.is.alive(c)===!0?c>
$m.vd.visible_page_height&&(c=$m.vd.visible_page_height-30):c=$m.vd.visible_page_height-30;b.style.height="30px";var d=b.clientHeight;if($m.is.alive(c)===!1||c>d)d=Math.max(b.scrollHeight,d),c&&(d=Math.min(c,d)),d>b.clientHeight&&$m.style.set(a,{height:d+"px"})}};
$m.h.empty_onclick={name:"empty_onclick",data_att:"empty_onclick",data_att_empty_id:"data-mjf_empty_click_id",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){var b=$m.is.string(a)===!0?$m.id(a):a;if($m.is.alive(b)===!0){var a=$m.attr.get(a,$m.h.empty_onclick.data_att_empty_id),c=$m.is.good_id(a);if($m.is.alive(c)===!0)$m.vd.is_mobile_touch===!0?c.innerHTML="":$m.animate.opaque(c,"down",30,function(){c.innerHTML="";c.style.opacity=1})}}};
$m.h.fire_event={name:"fire_event",data_att:"fire_event",data_att_on:"data-mjf_fe_on",data_att_exe:"data-mjf_fe_exe",data_att_id:"data-mjf_fe_id",construct:function(){for(var a=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),b=0,c=a.length;b<c;b++)$m.elements.bind(a[b],this.data_att,$m.attr.get(a[b],this.data_att_on),this.exec)},exec:function(a){var b=$m.id(a),c=$m.attr.get(a,$m.h.fire_event.data_att_exe),d=$m.attr.get(a,$m.h.fire_event.data_att_id);try{$m.id(d)[c]()}catch(e){$m.de.throw_browser_error("$m.h.fire_event.exec("+
a+") failed")}$m.tag.get_name(a)=="a"&&b.blur()}};
$m.h.form_changed_alert={name:"form_changed_alert",data_att:"form_changed_alert",watch_forms:[],construct:function(){var a=$m.attr.get_tags_with($m.tags.form,$m.data_att,this.data_att);$m.elements.bind(a,this.data_att,"submit",this.ignore);for(var b=0,c=a.length;b<c;b++)$m.is.object(this.watch_forms[a[b].id])===!1&&(this.watch_forms[a[b].id]={}),this.watch_forms[a[b].id].should_confirm=!1;$m.win.bind("beforeunload",function(b){for(var c=!1,f=!1,g=!1,h=$m.tags.get($m.document,"option"),i=0,l=a.length;i<
l;i++)for(var f=$m.get_form_fields(a[i],["text","password","file","textarea","select","radio","checkbox"]),k=0,j=f.length;k<j;k++)$m.is.alive(f[k].type)===!0&&(f[k].type=="radio"||f[k].type=="checkbox")?f[k].defaultChecked!=f[k].checked&&(c=!0):$m.tag.get_name(f[k])=="select"?(g=f[k].selectedIndex,h[g].defaultSelected!=h[g].selected&&(c=!0)):f[k].defaultValue!=f[k].value&&(c=!0);if(c===!0){if(b=b||window.event)b.returnValue=$m.lang.core.msgs.navigate_away.form;return $m.lang.core.msgs.navigate_away.form}})},
ignore:function(a){$m.h.form_changed_alert.watch_forms[a].should_confirm=!1}};
$m.h.form_required={name:"form_required",data_att:"form_required",required_att:"field_required",required_msg_append:"_required_msg",valid_forms:[],construct:function(){for(var a=$m.attr.get_tags_with($m.tags.form,$m.data_att,this.data_att),b=0,c=a.length;b<c;b++)tmp_form_id=$m.attr.get(a[b],"id"),$m.attr.set(a[b],{name:tmp_form_id}),this.valid_forms[tmp_form_id]=!0;$m.elements.bind(a,this.data_att,"submit",this.exec)},exec:function(a){$m.trick.darkroom==!0&&$m.is.in_array($m.t.darkroom.dr_forms,a)===
!1&&$m.attr.get(a,"data-mjf_dr_hide")!=="false"&&$m.t.darkroom.hide_all();var b=$m.id(a),c=!0,d=[],e=!1,f=[],e="",f=0,g="",h="",i=!1,l=!1,k=!1,f=$m.attr.get_fields_with(a,["text","password","textarea","file"],$m.data_att,$m.h.form_required.required_att),j;for(j in f)if($m.is.good_id(f[j].id)!==!1){g=$m.attr.get(f[j],"data-mjf_err_parent");$m.is.alive(g)===!0?$m.css_class.remove(g,"field_error_parent"):$m.css_class.remove(f[j].parentNode,"field_error_parent");$m.css_class.remove(f[j].id,"field_error");
l=f[j].id+$m.h.form_required.required_msg_append;k=$m.id(l);$m.is.alive(k)===!0&&$m.css_class.replace(l,"field_error_msg_on","field_error_msg_off");if(f[j].type!="file")f[j].value=$m.trim(f[j].value);if($m.is.alive(f[j].value)===!1&&f[j].disabled===!1&&f[j].readOnly===!1){if(i===!1)h=f[j].parentNode,i=!0;$m.is.alive(g)===!0?$m.css_class.add(g,"field_error_parent"):$m.css_class.add(f[j].parentNode,"field_error_parent");$m.css_class.add(f[j].id,"field_error");c=!1;$m.is.alive(k)===!0&&$m.css_class.replace(l,
"field_error_msg_off","field_error_msg_on")}}f=$m.attr.get_fields_with(b,["select"],$m.data_att,$m.h.form_required.required_att);for(j in f)if($m.is.good_id(f[j].id)!==!1&&(g=$m.attr.get(f[j],"data-mjf_err_parent"),$m.is.alive(g)===!0?$m.css_class.remove(g,"field_error_parent"):$m.css_class.remove(f[j].parentNode,"field_error_parent"),$m.css_class.remove(f[j].id,"field_error"),l=f[j].id+$m.h.form_required.required_msg_append,k=$m.id(l),$m.is.alive(k)===!0&&$m.css_class.replace(l,"field_error_msg_on",
"field_error_msg_off"),$m.is.alive(f[j].value)===!1&&f[j].disabled===!1)){if(i===!1)h=f[j].parentNode,i=!0;$m.is.alive(g)===!0?$m.css_class.add(g,"field_error_parent"):$m.css_class.add(f[j].parentNode,"field_error_parent");$m.css_class.add(f[j].id,"field_error");c=!1;$m.is.alive(k)===!0&&$m.css_class.replace(l,"field_error_msg_off","field_error_msg_on")}f=$m.attr.get_fields_with(b,["radio","checkbox"],$m.data_att,$m.h.form_required.required_att);b=0;for(g=f.length;b<g;b++)e!=$m.attr.get(f[b],"name")&&
(e=$m.attr.get(f[b],"name"),d.push(document[a][$m.attr.get(f[b],"name")]));for(j in d){f=0;if($m.is.alive(d[j].length)===!0){b=0;for(a=d[j].length;b<a;b++)d[j][b].checked===!0&&f++;e=$m.id($m.attr.get(d[j][0],"id"))}else{if($m.is.good_id(d[j].id)===!1)continue;e=$m.id($m.attr.get(d[j],"id"));e.checked===!0&&f++}g=$m.attr.get(e,"data-mjf_err_parent");l=e.id+$m.h.form_required.required_msg_append;k=$m.id(l);$m.is.alive(k)===!0&&$m.css_class.replace(l,"field_error_msg_on","field_error_msg_off");if(f==
0){if(i===!1)h=e.parentNode,i=!0;$m.is.alive(g)===!0?$m.css_class.add(g,"field_error_parent"):$m.css_class.add(e.parentNode,"field_error_parent");c=!1;$m.is.alive(k)===!0&&$m.css_class.replace(l,"field_error_msg_off","field_error_msg_on")}else $m.is.alive(g)===!0?$m.css_class.remove(g,"field_error_parent"):$m.css_class.remove(e.parentNode,"field_error_parent")}return c===!0?!0:($m.smooth_scroll.construct(h,20),!1)}};
$m.h.frame_reload={name:"frame_reload",data_att:"frame_reload",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){var b=$m.id(a),a=$m.attr.get(a,"data-mjf_frame_id"),c=$m.id(a);$m.is.alive(c)===!0?c.src=c.src:$m.de.throw_browser_error('Frame ID "'+a+'" does not exist!');b.blur()}};
$m.h.ga_click_track={name:"ga_click_track",data_att:"ga_click_track",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){var b=$m.attr.get(a,"href");$m.is.alive(b)===!0&&$m.track.ga({category:"MJF GA Click",action:a+" Click",label:b})}};
$m.h.geo_get={name:"geo_get",data_att:"geo_get",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){var b=$m.id(a),c=$m.geo.init_settings(a);$m.tag.get_name(a)=="a"&&b.blur();$m.geo.request.found_location=!1;if($m.geo.send_request(c,a)===!1)return $m.geo.get_error("Error getting location."),!1}};
$m.h.html5_audio={name:"html5_audio",data_att:"html5_audio",construct:function(){for(var a=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),b="",c="",d="",e="",f="",g=0,h=a.length;g<h;g++)b="audio/"+$m.attr.get(a[g],"data-mjf_h5a_type"),c=$m.attr.get(a[g],"href"),d=$m.attr.get(a[g],"data-mjf_h5a_id"),e=$m.attr.get(a[g],"data-mjf_h5a_autoplay"),f=$m.attr.get(a[g],"data-mjf_h5a_loop"),document.createElement("audio").canPlayType&&document.createElement("audio").canPlayType(b)?(autoplay_html=
$m.is.alive(e)===!0&&e=="true"?'autoplay="autoplay"':"",loop_html=$m.is.alive(f)===!0&&f=="true"?'loop="loop"':"",audio_html='<audio controls="controls" '+autoplay_html+" "+loop_html+' preload="auto"><source src="'+c+'" type="'+b+'"></audio>'):(autoplay_html=$m.is.alive(e)===!0&&e=="true"?"true":"false",loop_html=$m.is.alive(f)===!0||f=="true"?"true":"false",audio_html='<object width="300" height="50" type="'+b+'" classid="clsid:22D6F312-B0F6-11D0-94AB-0080C74C7E95" codebase="http://activex.microsoft.com/activex/controls/mplayer/en/nsmp2inf.cab#Version=6,0,02,902"><param name="src" value="'+
c+'"><param name="autoplay" value="'+autoplay_html+'"><param name="autoStart" value="'+autoplay_html+'"><param name="controller" value="true"><param name="loop" value="'+loop_html+'"><embed src="'+c+'" width="300" height="50" autostart="'+autoplay_html+'" controller="true" loop="'+loop_html+'"></object>'),$m.id(d).innerHTML=audio_html}};
$m.h.html5_video={name:"html5_video",data_att:"html5_video",data_att_play:"html5_video_play",data_att_pause:"html5_video_pause",data_att_stop:"html5_video_stop",data_att_seek:"html5_video_seek",data_att_end:"html5_video_end",uses_flash:!1,construct:function(){var a={},b=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),c="",d="",e="",f;a.path="";a.poster="";a.flv="";a.mp4="";a.good_mp4=!1;a.ogg="";a.good_ogg=!1;a.webm="";a.good_webm=!1;a.color_bg="";a.color_fg="";a.dims="";a.js_callback=
"";a.autoload="";a.autoplay="";a.update_id="";a.does_video=$m.media.supports.video();for(var g=0,h=b.length;g<h;g++){a.path=$m.attr.get(b[g],"data-mjf_h5v_path");a.poster=$m.attr.get(b[g],"data-mjf_h5v_poster");a.poster_html=$m.is.alive(a.poster)===!0?'poster="'+a.poster+'"':"";a.flv=$m.attr.get(b[g],"data-mjf_h5v_flv");a.color_bg=$m.attr.get(b[g],"data-mjf_h5v_color_bg");a.color_bg_html=$m.is.alive(a.color_bg)===!0?a.color_bg:"000000";a.color_fg=$m.attr.get(b[g],"data-mjf_h5v_color_fg");a.color_fg_html=
$m.is.alive(a.color_fg)===!0?a.color_fg:"991517";f=$m.attr.get(b[g],"data-mjf_h5v_dims").split("x");a.video_width=parseInt(f[0]);a.video_height=parseInt(f[1]);a.js_callback=$m.attr.get(b[g],"data-mjf_h5v_js_callback");a.autoload=$m.attr.get(b[g],"data-mjf_h5v_autoload");a.autoload_html=$m.is.alive(a.autoload)===null||a.autoload=="false"?'preload="meta"':'preload="auto"';a.autoplay=$m.attr.get(b[g],"data-mjf_h5v_autoplay");a.autoplay_html=$m.is.alive(a.autoplay)===!0&&a.autoplay=="true"?'autoplay="autoplay"':
"";a.update_id=$m.attr.get(b[g],"id");if(a.does_video){f=[];a.mp4=$m.attr.get(b[g],"data-mjf_h5v_mp4");if($m.is.alive(a.mp4)===!0){var i=$m.media.supports.h264();if($m.is.alive(i)===!0)f.push('<source src="'+a.path+a.mp4+'" type="video/mp4"></source>'),a.good_mp4=!0}a.ogg=$m.attr.get(b[g],"data-mjf_h5v_ogg");if($m.is.alive(a.ogg)===!0&&(i=$m.media.supports.theora(),$m.is.alive(i)===!0))f.push('<source src="'+a.path+a.ogg+'" type="video/ogg"></source>'),a.good_ogg=!0;a.webm=$m.attr.get(b[g],"data-mjf_h5v_webm");
if($m.is.alive(a.webm)===!0&&(i=$m.media.supports.vorbis(),$m.is.alive(i)===!0))f.push('<source src="'+a.path+a.webm+'" type="video/webm"></source>'),a.good_webm=!0;if(a.good_mp4===!0||a.good_ogg===!0||a.good_webm===!0){for(var c=$m.is.alive(a.video_width)===!0?'width="'+a.video_width+'"':"",e=$m.is.alive(a.video_height)===!0?'height="'+a.video_height+'"':"",c="<video "+c+" "+e+' controls="controls" '+a.autoplay_html+" "+a.autoload_html+" "+a.poster_html+'id="'+a.update_id+'_video">',e="</video>",
i=0,l=f.length;i<l;i++)d+=f[i];$found_support=!0}else $found_support=!1;$found_support===!1&&$m.is.alive(a.flv)===!0&&(d+=$m.h.html5_video.get_flv_html(a))}else d=$m.h.html5_video.get_flv_html(a);$m.id(a.update_id).innerHTML=c+d+e;a.js_callback!==null&&(a.good_mp4===!0||a.good_ogg===!0||a.good_webm===!0)&&$m.win.bind("load",function(){document.getElementById(a.update_id+"_video").addEventListener("ended",function(){$m.ev.all(a.js_callback)},!1)})}$m.elements.bind($m.tags.all,this.data_att_play,"click",
this.play);$m.elements.bind($m.tags.all,this.data_att_pause,"click",this.pause);$m.elements.bind($m.tags.all,this.data_att_stop,"click",this.stop);$m.elements.bind($m.tags.all,this.data_att_seek,"click",this.seek);$m.elements.bind($m.tags.all,this.data_att_end,"click",this.end)},get_flv_html:function(a){if($m.is.alive(a.flv)===!0){$m.h.html5_video.uses_flash=!0;var b=$m.config.basedir+"flash/",c=$m.is.alive(a.autoload)===null||a.autoload=="false"?"off":"on",d=$m.is.alive(a.autoplay)===!0&&a.autoplay==
"true"?"on":"off",e=$m.is.alive(a.js_callback)===!0?"on":"off",b=b+"player_flv.swf?movie="+a.path+a.flv+"&amp;bgcolor=0x"+a.color_bg_html+"&amp;fgcolor=0x"+a.color_fg_html+"&amp;volume=100&amp;autoplay="+d+"&amp;autoload="+c+"&amp;mute=off&amp;autorewind=on&amp;js_callback="+e;a.video_height+=40;video_html='<object width="'+a.video_width+'" height="'+a.video_height+'"';$m.vd.is_msie===!0&&(video_html+='type="application/x-shockwave-flash"');video_html+=' id="'+a.update_id+'_video"><param name="movie" value="'+
b+'"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always">';$m.vd.is_msie===!1&&(video_html+='<embed name="'+a.update_id+'_video" src="'+b+'" width="'+a.video_width+'" height="'+a.video_height+'" allowFullScreen="true" allowScriptAccess="always" type="application/x-shockwave-flash"></embed>');video_html+="</object>";a.js_callback!==null&&(player_callback=function(){$m.ev.all(a.js_callback)})}else video_html='<p><img src="'+$m.config.basedir+'images/misc/broken_video.png" alt="Darn, unable to load this video." width="300" height="240"></p>';
return video_html},play:function(a){var b=$m.attr.get(a,"data-mjf_h5v_video_id")+"_video";setTimeout(function(){$m.h.html5_video.uses_flash===!0?$m.get_flash_object(b).play_video():$m.id(b).play()},1E3)},pause:function(a){a=$m.attr.get(a,"data-mjf_h5v_video_id")+"_video";$m.h.html5_video.uses_flash===!0?$m.get_flash_object(a).pause_video():$m.id(a).pause()},stop:function(a){a=$m.attr.get(a,"data-mjf_h5v_video_id")+"_video";$m.h.html5_video.uses_flash===!0?(a=$m.get_flash_object(a),a.stop_video()):
(a=$m.id(a),a.pause(),a.currentTime=0)},seek:function(a){var b=$m.attr.get(a,"data-mjf_h5v_video_id")+"_video",a=parseFloat($m.attr.get(a,"data-mjf_h5v_seek_time"));$m.h.html5_video.uses_flash===!0?$m.get_flash_object(b).seek_video(a):$m.id(b).currentTime=a},end:function(a){a=$m.attr.get(a,"data-mjf_h5v_video_id")+"_video";$m.h.html5_video.uses_flash===!0?(a=$m.get_flash_object(a),a.end_video()):(a=$m.id(a),a.currentTime=a.duration)}};
$m.h.img_rollovers={name:"img_rollovers",data_att:"img_rollovers",increments:15,construct:function(){if($m.vd.is_mobile_touch!==!0){for(var a="",b="",c=0,d=$m.tags.img.length;c<d;c++)if($m.attr.has_value($m.tags.img[c],$m.data_att,this.data_att))a=$m.id($m.tags.img[c]),b=new Image,b.src=$m.attr.get(a,"data-mjf_img_on"),$m.attr.set(a,{"data-mjf_img_off":$m.tags.img[c].src});$m.elements.bind($m.tags.img,this.data_att,"mouseover",this.do_rollover);$m.elements.bind($m.tags.img,this.data_att,"mouseout",
this.undo_rollover)}},do_rollover:function(a){$m.id(a).src=$m.attr.get(a,"data-mjf_img_on")},undo_rollover:function(a){$m.id(a).src=$m.attr.get(a,"data-mjf_img_off")}};
$m.h.img_slideshow={name:"img_slideshow",data_att:!1,img_folder:!1,imgs:[],img_id:{},cnt:0,delay:!1,animate:!1,increments:25,timeout:!1,construct:function(a){$m.h.img_slideshow.click.construct();this.imgs=a.imgs;this.img_id=$m.id(a.img_id);this.img_folder=this.img_id.src.slice(0,this.img_id.src.lastIndexOf("/")+1);this.delay=a.delay*1E3;this.animate=a.animate;for(var b=0,c=this.imgs.length;b<c;b++)a=new Image,a.src=this.img_folder+this.imgs[b];this.start()},start:function(){this.timeout=setTimeout("$m.h.img_slideshow.cycle()",
$m.h.img_slideshow.delay)},cycle:function(){$m.h.img_slideshow.cnt++;if($m.h.img_slideshow.cnt==$m.h.img_slideshow.imgs.length)$m.h.img_slideshow.cnt=0;$m.h.img_slideshow.animate===!0?$m.animate.opaque($m.h.img_slideshow.img_id,"down",$m.h.img_slideshow.increments,function(){$m.h.img_slideshow.img_id.src=$m.h.img_slideshow.img_folder+$m.h.img_slideshow.imgs[$m.h.img_slideshow.cnt];$m.animate.opaque($m.h.img_slideshow.img_id,"up",$m.h.img_slideshow.increments)}):$m.h.img_slideshow.img_id.src=$m.h.img_slideshow.img_folder+
$m.h.img_slideshow.imgs[$m.h.img_slideshow.cnt];$m.h.img_slideshow.timeout=setTimeout(function(){$m.h.img_slideshow.cycle()},$m.h.img_slideshow.delay)},click:{name:"click",data_att:"img_slideshow_click",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){$m.h.img_slideshow.animate===!0?$m.animate.opaque($m.h.img_slideshow.img_id,"down",$m.h.img_slideshow.increments,function(){$m.h.img_slideshow.img_id.src=$m.h.img_slideshow.img_folder+a;$m.animate.opaque($m.h.img_slideshow.img_id,
"up",$m.h.img_slideshow.increments)}):$m.h.img_slideshow.img_id.src=$m.h.img_slideshow.img_folder+a;clearTimeout($m.h.img_slideshow.timeout)}}};
$m.h.lightswitch={name:"lightswitch",data_att:"lightswitch",single_clickers:[],css:{block:"lightswitch_block",none:"lightswitch_none"},construct:function(){var a=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),b="",c=[],d=b=b="",e=[],f="",g=!1,h=$m.storage.get.table($m.storage.db_wand+"lightswitch"),b="",d=!1,f="",g=$m.ut.friendly_url(window.location);this.single_clickers=[];if($m.is.alive(h)===!0&&$m.ajax_init===!1)for(var i in h)b=$m.storage.get.page_tiny_id(i),d=$m.id(b),f=$m.storage.get.page_code(i),
$m.is.alive(d)===!0&&g==f&&($m.attr.set(b,{"data-mjf_lswitch_state":h[i].state}),e.push(b));i=0;for(h=a.length;i<h;i++)if(b=$m.attr.get(a[i],"data-mjf_lswitch_all"),b=="collapse")b=$m.attr.get(a[i],"data-mjf_lswitch_use_css"),$m.is.alive(b)&&b=="false"||$m.css_class.add(a[i],this.css.block),c.push(a[i]);else if(b=="expand")b=$m.attr.get(a[i],"data-mjf_lswitch_use_css"),$m.is.alive(b)&&b=="false"||$m.css_class.add(a[i],this.css.none),c.push(a[i]);else if(this.single_clickers.push(a[i]),d=$m.attr.get(a[i],
"id"),b=$m.id(d),current_id_use_css=$m.attr.get(b,"data-mjf_lswitch_use_css"),g=$m.tag.get_name(b)=="input"&&$m.attr.get(b,"type")=="checkbox",g===!0&&(current_id_use_css="false",$m.attr.set(d,{"data-mjf_lswitch_use_css":"false"})),$m.is.in_array(e,d)===!1)if(f=$m.attr.get(b,"data-mjf_lswitch_id"),$m.css_class.has(f,"display_block")){if(g===!0)b.checked=!0;$m.is.alive(current_id_use_css)&&current_id_use_css=="false"||$m.css_class.add(d,this.css.block);$m.attr.set(d,{"data-mjf_lswitch_state":"block"})}else if($m.css_class.has(f,
"display_inline"))$m.is.alive(current_id_use_css)&&current_id_use_css=="false"||$m.css_class.add(d,this.css.block),$m.attr.set(d,{"data-mjf_lswitch_state":"inline"});else if($m.css_class.has(f,"table-row"))$m.is.alive(current_id_use_css)&&current_id_use_css=="false"||$m.css_class.add(d,this.css.block),$m.attr.set(d,{"data-mjf_lswitch_state":"table-row"});else{if(g===!0)b.checked=!1;$m.is.alive(current_id_use_css)&&current_id_use_css=="false"||$m.css_class.add(d,this.css.none);$m.attr.set(b,{"data-mjf_lswitch_state":"none"})}else $m.h.lightswitch.update(d,
$m.attr.get(b,"data-mjf_lswitch_state"),!1);$m.elements.bind(this.single_clickers,this.data_att,"click",this.exec);$m.elements.bind(c,this.data_att,"click",this.toggle_all)},toggle_all:function(a){var b="",c="";switch($m.attr.get(a,"data-mjf_lswitch_all")){case "collapse":$m.css_class.replace(a,$m.h.lightswitch.css.block,$m.h.lightswitch.css.none);$m.attr.set(a,{"data-mjf_lswitch_all":"expand"});b="none";break;case "expand":$m.css_class.replace(a,$m.h.lightswitch.css.none,$m.h.lightswitch.css.block),
$m.attr.set(a,{"data-mjf_lswitch_all":"collapse"}),b="block"}for(var a=0,d=$m.h.lightswitch.single_clickers.length;a<d;a++)b=="block"&&(c=$m.attr.get($m.h.lightswitch.single_clickers[a],"data-mjf_lswitch_display"),c=="inline"?b="inline":c=="table-row"&&(b="table-row")),$m.h.lightswitch.update($m.h.lightswitch.single_clickers[a],b,!0)},exec:function(a){var b=$m.id(a),c=$m.attr.get(a,"data-mjf_lswitch_state");$m.attr.get(a,"data-mjf_lswitch_id");var d=$m.attr.get(a,"data-mjf_lswitch_display"),d=d===
null?"":d;if(c=="none")switch(d){case "":case "block":new_state="block";break;case "inline":new_state="inline";break;case "table-row":new_state="table-row";break;default:new_state="none"}else new_state="none";$m.tag.get_name(a)=="a"&&b.blur();$m.h.lightswitch.update(a,new_state,!0);$m.attr.set(a,{"data-mjf_lswitch_state":new_state})},update:function(a,b,c){$m.id("in_id");var d=$m.attr.get(a,"data-mjf_lswitch_use_css"),e=$m.attr.get(a,"data-mjf_lswitch_id"),f=$m.attr.get(a,"data-mjf_lswitch_animate_increments"),
g=$m.id(e);$m.is.alive(f)===!1&&(f=5);if(f==0||$m.vd.is_mobile_touch===!0)c=!1;switch(b){case "none":(d===null||d!="false")&&$m.css_class.replace(a,$m.h.lightswitch.css.block,$m.h.lightswitch.css.none);$m.css_class.has(e,"display_block")===!0?($m.css_class.replace(e,"overflow_auto","overflow_hidden"),c===!0&&$m.config.animations.use===!0?(c=new $m.animation(g.offsetHeight,0),c.exec(f,function(a){g.style.height=a+"px"},function(){g.style.height=0;$m.css_class.replace(e,"display_block","display_none")})):
(g.style.height=0,$m.css_class.replace(e,"display_block","display_none"))):$m.css_class.has(e,"display_table-row")===!0?$m.css_class.replace(e,"display_table-row","display_none"):$m.css_class.replace(e,"display_inline","display_none");break;case "block":(d===null||d!="false")&&$m.css_class.replace(a,$m.h.lightswitch.css.none,$m.h.lightswitch.css.block);c===!0&&$m.config.animations.use===!0?($m.css_class.replace(e,"overflow_auto","overflow_hidden"),g.style.height="auto",$m.css_class.replace(e,"display_none",
"display_block"),c=new $m.animation(0,g.offsetHeight),g.style.height=0,c.exec(f,function(a){g.style.height=a+"px"},function(){$m.css_class.remove(e,"overflow_hidden");g.style.height="auto"})):(g.style.height="auto",$m.css_class.replace(e,"display_none","display_block"));break;case "inline":(d===null||d!="false")&&$m.css_class.replace(a,$m.h.lightswitch.css.none,$m.h.lightswitch.css.block);$m.css_class.replace(e,"display_none","display_inline");break;case "table-row":(d===null||d!="false")&&$m.css_class.replace(a,
$m.h.lightswitch.css.none,$m.h.lightswitch.css.block),$m.css_class.replace(e,"display_none","display_table-row")}f=$m.attr.get(a,"data-mjf_lswitch_cookie");f===null||f!="false"?$m.storage.set($m.storage.db_wand+"lightswitch",$m.storage.create.data_record(a,"state",b)):$m.storage.remove($m.storage.db_wand+"lightswitch",a)}};
$m.h.open_new_win={name:"open_new_win",data_att:"open_new_win",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){var b=$m.id(a),c="new_win_"+a,d=$m.attr.get(a,"data-mjf_win_dim"),e=$m.attr.get(a,"href"),f=$m.attr.get(a,"data-mjf_ga_track");$m.is.alive(e)===!0&&f!==null&&$m.track.ga({category:"MJF Open New Win",action:a+" Click",label:e});d=="normal"?window.open(e,c):(a=d.split("x"),window.open(e,c,"toolbar=no,location=no,resizable=yes,scrollbars=yes,menubar=no,width="+
a[0]+",height="+a[1]));b.blur()}};
$m.h.password_strength_checker={name:"password_strength_checker",data_att:"password_strength_checker",timer:!1,construct:function(){for(var a=$m.attr.get_fields_with($m.body_id,["text","password"],$m.data_att,this.data_att),b=0,c=a.length;b<c;b++)$m.attr.has_value(a[b],"data-mjf_pass_check_has","true")===!1&&($m.tag.insert_after(a[b],$m.tag.init("span",{id:a[b].id+"_score_title"})),$m.tag.insert_after(a[b],$m.tag.init("span",{"class":"mjf_password_strength_checker_container",id:a[b].id+"_score_visual"})),
$m.tag.insert_after(a[b],$m.tag.init("br")),$m.attr.set(a[b],{"data-mjf_pass_check_has":"true"}));$m.elements.bind(a,this.data_att,"keyup",this.exec);$m.elements.bind(a,this.data_att,"change",this.exec)},exec:function(a){clearTimeout($m.h.password_strength_checker.timer);$m.h.password_strength_checker.timer=setTimeout(function(){$m.h.password_strength_checker.render(a,$m.h.password_strength_checker.score($m.id(a).value))},750)},score:function(a){var b=0;if($m.is.alive(a)===!1)return b;for(var c={},
d=0,e=a.length;d<e;d++)c[a[d]]=(c[a[d]]||0)+1,b+=5/c[a[d]];a={digits:/\d/.test(a),lower:/[a-z]/.test(a),upper:/[A-Z]/.test(a),non_words:/\W/.test(a)};variation_cnt=0;for(var f in a)variation_cnt+=a[f]==!0?1:0;b+=(variation_cnt-1)*10;return parseInt(b)},render:function(a,b){if($m.is.alive(a)===!1)return!1;if($m.is.alive(b)===!1)return!1;var c=$m.lang.core.msgs.passwords.too_short,d="0";if(b>80)c=$m.lang.core.msgs.passwords.strong,d="100";else if(b>60)c=$m.lang.core.msgs.passwords.good,d="80";else if(b>=
30)c=$m.lang.core.msgs.passwords.weak,d="30";$m.id(a+"_score_visual").innerHTML='<span class="bg_colors_blue" style="width:'+d+'%;"></span>';$m.id(a+"_score_title").innerHTML=$m.lang.core.msgs.passwords.strength+c}};$m.h.print_onclick={name:"print_onclick",data_att:"print_onclick",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){window.print&&window.print();$m.tag.get_name(a)=="a"&&$m.id(a).blur()}};
$m.h.print_onload={name:"print_onload",data_att:"print_onload",construct:function(){window.print&&window.print()}};
$m.h.remove_onclick={name:"remove_onclick",data_att:"remove_onclick",data_att_remove_id:"data-mjf_remove_click_id",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){var b=$m.is.string(a)===!0?$m.id(a):a;if($m.is.alive(b)===!0){var c=$m.attr.get(a,$m.h.remove_onclick.data_att_remove_id);$m.vd.is_mobile_touch===!0?$m.tag.remove(c):$m.animate.opaque(c,"down",30,function(){$m.tag.remove(c)})}}};
$m.h.same_height={name:"same_height",data_att:"same_height",data_att_kids:"same_height_child",construct:function(a){a=$m.is.number(a)===!0?a*1E3:1;setTimeout(function(){$m.h.same_height.exec()},a)},exec:function(){for(var a=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),b=[],c=[],d=0,e=0,f=a.length;e<f;e++){for(var b=$m.tags.get(a[e],"*"),g=0,h=b.length;g<h;g++)$m.attr.has_value(b[g],$m.data_att,this.data_att_kids)!==!1&&c.push(b[g]);g=0;for(h=c.length;g<h;g++)if(c[g].offsetHeight>d)d=
c[g].offsetHeight;g=0;for(h=c.length;g<h;g++)c[g].style.height=d+"px"}}};
$m.h.smooth_scroll_to={name:"smooth_scroll_to",data_att:"smooth_scroll_to",data_att_to:"data-mjf_smooth_scroll_to_id",data_att_top:"data-mjf_smooth_scroll_to_top",data_att_left:"data-mjf_smooth_scroll_to_left",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){var b=$m.id(a),c=$m.id($m.attr.get(a,$m.h.smooth_scroll_to.data_att_to));b.blur();$m.is.alive(c)===!0&&(b=$m.attr.get(a,$m.h.smooth_scroll_to.data_att_top),b=$m.is.alive(b)?b:0,a=$m.attr.get(a,
$m.h.smooth_scroll_to.data_att_left),a=$m.is.alive(a)?a:0,$m.smooth_scroll.construct(c,b,a))}};$m.h.s2lcus={name:"s2lcus",data_att:"s2lcus",construct:function(){for(var a=[],b=[],c=0,d=$m.tags.form.length;c<d;c++)a=$m.attr.get_fields_with($m.tags.form[c],["text","textarea"],$m.data_att,this.data_att),b=b.concat(a);$m.elements.bind(b,this.data_att,"keyup",this.exec);$m.elements.bind(b,this.data_att,"change",this.exec)},exec:function(a){$m.id($m.attr.get(a,"data-mjf_s2lcus")).value=$m.ut.friendly_url($m.id(a).value)}};
$m.h.submit_onclick={name:"submit_onclick",data_att:"submit_onclick",construct:function(){$m.elements.bind($m.tags.all,this.data_att,"click",this.exec)},exec:function(a){var b=$m.attr.get(a,"data-mjf_soc_id"),c=$m.id(b),d=$m.attr.get(a,"data-mjf_soc_name_value");$m.tag.get_name(a)=="a"&&$m.id(a).blur();d!==null&&(a=$m.attr.get(b,"action"),a.indexOf("?")==-1?$m.attr.set(c,{action:a+"?"+d}):$m.attr.set(c,{action:a+"&"+d}));$m.is.alive($m.h.form_required.valid_forms[b])===!0?$m.h.form_required.exec(b)===
!0&&c.submit():c.submit()}};
$m.h.text_resize={name:"text_resize",data_att:"text_resize",data_att_resize_id:"data-mjf_resize_id",data_att_resize_amt:"data-mjf_resize_amt",default_size:12,construct:function(){var a=$m.storage.get.table($m.storage.db_wand+"text_resize"),b=!1,c=b="",d=$m.ut.friendly_url(window.location);if($m.is.alive(a)===!0&&$m.ajax_init===!1)for(var e in a)if(b=$m.storage.get.page_tiny_id(e),b=$m.id(b),c=$m.storage.get.page_code(e),$m.is.alive(b)===!0&&d==c)b.style.fontSize=a[e].font_size_final;this.default_size=
$m.wand.text_resize;$m.elements.bind($m.tags.a,this.data_att,"click",this.exec)},exec:function(a){var b=$m.attr.get(a,$m.h.text_resize.data_att_resize_id),c=$m.id(b),a=$m.attr.get(a,$m.h.text_resize.data_att_resize_amt),d=0;if(!($m.is.alive(c.style)===!0&&$m.is.alive(c.style.fontSize)===!0))c.style.fontSize=$m.h.text_resize.default_size+"px";d=parseInt(c.style.fontSize);switch(a){case "-1":font_size_final=d<8?8:d-1;break;case "+1":font_size_final=d+1;break;default:font_size_final=$m.h.text_resize.default_size}font_size_final+=
"px";c.style.fontSize=font_size_final;$m.storage.set($m.storage.db_wand+"text_resize",$m.storage.create.data_record(b,"font_size_final",font_size_final))}};
$m.h.tool_tip={name:"tool_tip",data_att:"tool_tip",data_att_cont:"data-mjf_tt_id",all:[],css:{all:"tool_tip_cont",on:"tool_tip_cont_on"},increments:25,timeout:!1,construct:function(){var a=$m.vd.is_mobile_touch===!0?"click":"mouseover",b=$m.vd.is_mobile_touch===!0?"blur":"mouseout",c=$m.attr.get_tags_with($m.tags.all,$m.data_att,this.data_att),d="";this.all=[];for(var e=0,f=c.length;e<f;e++)d=$m.attr.get(c[e],this.data_att_cont),this.all.push(d),$m.element.bind(d,a,this.show_tip_cont),$m.element.bind(d,
b,this.hide_tip_cont);$m.elements.bind(c,this.data_att,a,this.show_tip);$m.elements.bind(c,this.data_att,b,this.hide_tip);$m.element.attach($m.body_id,"keypress",this.hide_all);$m.element.attach($m.body_id,"mousedown",this.hide_all);$m.element.attach($m.body_id,"touchstart",this.hide_all)},show_tip:function(a){clearTimeout($m.h.tool_tip.timeout);$m.h.tool_tip.hide_all();a=$m.attr.get(a,$m.h.tool_tip.data_att_cont);tip_cont_id=$m.id(a);tip_cont_id.style.opacity=0;$m.css_class.add(tip_cont_id,$m.h.tool_tip.css.on);
$m.animate.opaque(a,"up",$m.h.tool_tip.increments)},hide_tip:function(a){a=$m.attr.get(a,$m.h.tool_tip.data_att_cont);tip_cont_id=$m.id(a);$m.h.tool_tip.timeout=setTimeout(function(){$m.animate.opaque(tip_cont_id,"down",$m.h.img_rollovers.increments,function(){$m.css_class.remove(tip_cont_id,$m.h.tool_tip.css.on)})},1E3)},show_tip_cont:function(){clearTimeout($m.h.tool_tip.timeout);$m.css_class.add(this.id,$m.h.tool_tip.css.on)},hide_tip_cont:function(){var a=this.id;$m.h.tool_tip.timeout=setTimeout(function(){$m.css_class.remove(a,
$m.h.tool_tip.css.on)},1E3)},hide_all:function(){for(var a=0,b=$m.h.tool_tip.all.length;a<b;a++)$m.css_class.remove($m.h.tool_tip.all[a],$m.h.tool_tip.css.on)}};
